### ISSUE TITLE
MSSQL failure when executing a prepared query that leads to an error

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-sql-client#1000]
This is a probably a regression introduced in https://github.com/eclipse-vertx/vertx-sql-client/pull/994/commits/14796611ddc07667c32fd377053be86b8fb2bcad

For example, if you execute the prepared query `delete from Basic` and the table does not exist, the client fails with:

```
java.lang.UnsupportedOperationException: Unsupported token: 0
	at io.vertx.mssqlclient.impl.codec.MSSQLCommandCodec.decode(MSSQLCommandCodec.java:80)
	at io.vertx.mssqlclient.impl.codec.TdsMessageDecoder.decodeMessage(TdsMessageDecoder.java:65)
	at io.vertx.mssqlclient.impl.codec.TdsMessageDecoder.channelRead(TdsMessageDecoder.java:43)
```

**Comment by DavideD** [comment]
Is there an estimate date for this? We basically cannot use the Hibernate Reactive with MSSQL because of this

**Comment by vietj** [comment]
have you tried the PR that Thomas provided to confirm it works ?

we can plan a 4.1.2 release with this fix back-ported

**Comment by DavideD** [comment]
I think @tsegismont tested it but I will double check

**Comment by vietj** [comment]
thanks @DavideD

**Comment by DavideD** [comment]
I can confirm that the PR works and fixes the issue with Hibernate Reactive

**Comment by DavideD** [comment]
By the way, if you release a snapshot (4.1.2-SNAPSHOT) with this patch our CI will confirm it as well

**Comment by vietj** [comment]
I will merge this asap and we will discuss a 4.1.2 release

**Comment by vietj** [comment]
here is the backport to 4.1 branch https://github.com/eclipse-vertx/vertx-sql-client/pull/1003

**Comment by DavideD** [comment]
Awesome! Thanks a lot
