### ISSUE TITLE
Cursor Issue

### ISSUE THREAD

**Issue by rac021** [eclipse-vertx/vertx-sql-client#1012]
### Which version(s) did you encounter this bug ?

4.1.1

### Context

I encountered an exception which looks suspicious :

 With Corsor, the **while ( cursor.hasMore() )** loop runs once where it should run multiple times.

### Do you have a reproducer?

https://gist.github.com/rac021/3b0d3a54537bf5174ff7e8bdfd5ef1d6

### Steps to reproduce

1. Have just to set the **sqlQuery** and **PgConnectOptions** in the main method

### Extra

JAVA 11

https://github.com/eclipse-vertx/vertx-sql-client/issues/121

**Comment by rac021** [comment]
Hi,

@vietj , will this bug be fixed in the 4.2.0 release ?

Thanks

**Comment by vietj** [comment]
I can't see a bug but instead a misuse of vertx sql client with blocking code
