### ISSUE TITLE
expose ColumnDescriptor.getTypeName()

### ISSUE THREAD

**Issue by gavinking** [eclipse-vertx/vertx-sql-client#1020]
See discussion here: https://github.com/hibernate/hibernate-reactive/pull/903#discussion_r683126158

**Comment by tsegismont** [comment]
@gavinking this would be fixed in Vert.x 4.2. If it's a blocker, we could consider backporting #1024 to the `4.1` branch.

**Comment by gavinking** [comment]
I don't believe it's a blocker, more like a convenience. Right, @gbadner

**Comment by gbadner** [comment]
@gavinking, yes that is correct.
