### ISSUE TITLE
Support Returning Row Data on Delete Query

### ISSUE THREAD

**Issue by willisjtc** [eclipse-vertx/vertx-sql-client#1026]
#### Describe the feature

Postgres supports returning row data that is deleted. The vertx postgres client currently does not support this capability of postgres, though, column names/descriptors are being returned.

#### Use cases

Any tables that are related but not enforced by a foreign key constraint can better be deleted by this feature. For example, if there are tables for a school, class, and student then deleting the school would return the school data which would be used for deleting the class data, and the returned class data would be useful for deleting all enrollments of students in the class.

**Comment by willisjtc** [comment]
Looks like this issue also exists for Update queries, as well

**Comment by vietj** [comment]
does it require to use specific SQL ? 

which issue are you referring to ?

**Comment by willisjtc** [comment]
Here are some of the example queries:

```sql
delete from table where id = 1 returning *
delete from table where id = 1 returning column1

update table set column1 = 'c1' where id = 1 returning *
update table set column1 = 'c3' where id = 1 returning column1
```

**Comment by vietj** [comment]
it is already supported, here is a test case I wrote:


```java
  @Test
  public void testDeleteReturningBatch(TestContext ctx) {
    Async async = ctx.async();
    connector.accept(ctx.asyncAssertSuccess(client -> {
      deleteFromTestTable(ctx, client, () -> {
        List<Tuple> batch = Arrays.asList(
          Tuple.of(14, "SomeMessage1"),
          Tuple.of(15, "SomeMessage2"));
        client
          .preparedQuery("INSERT INTO Test (id, val) VALUES ($1, $2)")
          .executeBatch(batch)
          .compose(res -> client.query("DELETE FROM Test RETURNING id")
            .collecting(Collectors.toMap(row -> row.getInteger(0), row -> "whatever"))
            .execute()).onComplete(ctx.asyncAssertSuccess(res -> {
            ctx.assertEquals(2, res.size());
            ctx.assertEquals(new HashSet<>(Arrays.asList(14, 15)), res.value().keySet());
            async.complete();
          }));
      });
    }));
  }
```
