### ISSUE TITLE
Make possible combine mapTo and collecting

### ISSUE THREAD

**Issue by indiketa** [eclipse-vertx/vertx-sql-client#1035]
Executing a SqlTemplate only is possible to use `mapTo`  and `collecting` exclusively.
No way to obtain a `List<CustomObject>`directly.

**Comment by vietj** [comment]
can you show some example ?

**Comment by tsegismont** [comment]
It is possible to combine both:

```java
    SqlTemplate
      .forQuery(client, "SELECT * FROM users WHERE id=#{id}")
      .mapTo(USER_MAPPER)
      .collecting(toList())
```

Feel free to reopen if you can provide more info and a reproducer.
