### ISSUE TITLE
format of error messages on Postgres

### ISSUE THREAD

**Issue by gavinking** [eclipse-vertx/vertx-sql-client#1037]
The Postgres client produces error messages that look like 

    io.vertx.pgclient.PgException: { "message": "syntax error at or near \"foo\"", "severity": "ERROR", "code": "42601", "position": "1", "file": "scan.l", "line": "1180", "routine": "scanner_yyerror" }

I doubt that anything other than the message is actually meaningful, so I think the other gunk should be cleaned out.

**Comment by vietj** [comment]
you mean that the `PgException` `getMessage()` impl should return the error message and not such detailed message

**Comment by gavinking** [comment]
I guess.

**Comment by vietj** [comment]
yes that a bit too verbose for nothing and decrease usability

**Comment by DavideD** [comment]
I guess the `code` could also be handy. It makes it easier to look for the issue

**Comment by DavideD** [comment]
If it's a code identifying the error (I don't know)

**Comment by vietj** [comment]
like `actual message + "(" + code + ")"` ?

**Comment by gavinking** [comment]
Ah yes, right, I missed that because of all the extra irrelevant stuff. Yeah, if that's a Postgres error code, it's nice to have it.
