### ISSUE TITLE
java.lang.UnsupportedOperationException: Unable to decode metadata for DATETIMN

### ISSUE THREAD

**Issue by rasmushaglund** [eclipse-vertx/vertx-sql-client#1040]
Hello, I'm trying out the MSSQL client but encountered an error while trying to decode a nullable datetime field for MSSQL 2017 CU21.

https://github.com/eclipse-vertx/vertx-sql-client/blob/560041bb849dd6f80de9e50dfef8704e6b20c87b/vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/DataType.java#L395

I debugged the code and saw that there's no metadata handler for the type. I don't fully understand the system here, but when I read an unsigned byte from the payload for the metadata decoding, ByteBufUtils.readUnsignedByteLengthString(payload) gave the correct columnName.

Can I help somehow? If I were about to add support for DATETIMN, what parts of the code would I look into?

**Comment by vietj** [comment]
@tsegismont

**Comment by tsegismont** [comment]
Hi @rasmushaglund , thanks for offering your help.

You can start by implementing the methods in the `DataType` class. Then you need to update the [data types test cases](https://github.com/eclipse-vertx/vertx-sql-client/tree/master/vertx-mssql-client/src/test/java/io/vertx/mssqlclient/data).

If you haven't contributed to Vert.x before, I recommend reading https://github.com/vert-x3/wiki/wiki/Development-Process and https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines.

Looking forward to your contribution!

**Comment by rasmushaglund** [comment]
Thanks @tsegismont. 

I assume this is the type documentation? https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver15

**Comment by tsegismont** [comment]
Looks like it

>

**Comment by rasmushaglund** [comment]
I think I've managed to implemented the type, but I don't know if and how to implement encodeParam. Is there any tests involving encodeParam which I can take a look at? Maybe just try to encode and decode back again and compare the results?

https://github.com/rasmushaglund/vertx-sql-client/commit/31278ffbf3fea1282eb9d2d77615ad0d0b7b2b9a

**Comment by tsegismont** [comment]
There's the encodeParam implementation for TIMEN that you can inspire from:
https://github.com/eclipse-vertx/vertx-sql-client/blob/5b6c4cd4d627b1fea28340c2aef0046786e53d9e/vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/DataType.java#L451-L457

In the test sources, you should update the classes of the
MSSQLNullableDataTypeTestBase and MSSQLNotNullableDataTypeTestBase
hierarchies,

Le mar. 14 sept. 2021 à 17:45, Rasmus Haglund ***@***.***> a
écrit :

**Comment by rasmushaglund** [comment]
I've updated the related tests now, though the problem I have is that the encodeParam function for the data type is not called because the preferred class for LocalDateTime is DATETIME2N:
https://github.com/eclipse-vertx/vertx-sql-client/blob/5b6c4cd4d627b1fea28340c2aef0046786e53d9e/vertx-mssql-client/src/main/java/io/vertx/mssqlclient/impl/codec/DataType.java#L798

Do we even need a encodeParam function for DATETIMN? If the data sent to SQL Server is typed as DATETIME2N I guess it will handle the conversion to DATETIMN?

https://github.com/rasmushaglund/vertx-sql-client/commit/58f79d32453ae51dfd711ae66a09ec4463b51785

**Comment by tsegismont** [comment]
>or can we just encode those types as DATETIME2N and let SQL Server recast to the correct types

This is fine
