### ISSUE TITLE
SQL Client can't handle AWS RDS Multi-AZ failover

### ISSUE THREAD

**Issue by markusdlugi** [eclipse-vertx/vertx-sql-client#1052]
### Version

4.1.3

### Context

We are using an AWS Relational Database Service (RDS) PostgreSQL database for our application. AWS has the feature of Multi-AZ deployments, where you have a primary database and a standby database in another availability zone. The standby instance will take over once the primary instance fails, e.g. due to the outage of an AZ. In that case, the DNS entry in the AWS nameserver will be changed to point to the standby instance. For more details, see: https://docs.aws.amazon.com/en_en/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html

As pointed out in this documentation in the section `Setting the JVM TTL for DNS name lookups`, it is necessary that the application will try to resolve the DNS name again after some time for this approach to work. There's a property `networkaddress.cache.ttl` in Java which controls how often DNS entries are cached, and it is recommended to set this to a low value such as 60 seconds.

Currently however, when we test a failover, the application is not able to reconnect to the database even when this property is set. It seems like it still tries to contact the old instance even though that is not available and the standby instance has taken over.

Specifically, we identified the following code which is most likely causing this behavior:

https://github.com/eclipse-vertx/vertx-sql-client/blob/58981ae00557bd917fa86888e983d7b07fa1b0f7/vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/ConnectionFactoryBase.java#L59

Here, the DB's hostname is resolved by calling `options.getSocketAddress()`, which in turn creates the `SocketAddress`:

https://github.com/eclipse-vertx/vertx-sql-client/blob/58981ae00557bd917fa86888e983d7b07fa1b0f7/vertx-sql-client/src/main/java/io/vertx/sqlclient/SqlConnectOptions.java#L293

So that's the only place where the host name is resolved, and the resulting `SocketAddress` is kept forever in the ConnectionFactory, therefore no new DNS resolution is ever attempted.

Therefore, we suggest to change this behavior to always create a new `SocketAddress` object instead of storing it permanently in the ConnectionFactory. This way, the integrated Java mechanisms for DNS caching can be used to control how often DNS resolution is actually performed.

### Do you have a reproducer?

Unfortunately not, since it's hard to reproduce this locally without the Multi-AZ setup. You can test it yourself by:

### Steps to reproduce

1. Create an RDS instance on AWS with Multi-AZ enabled
2. Deploy any application, even a sample will be okay, which uses this database
3. Test the failover by rebooting the RDS instance and selecting the option "Reboot With Failover"
4. Observe that the application is not able to reconnect to the database. Only way to resolve this is to restart the application.

### Extra

Might seem related to #981, but this one is easier to solve since we can just rely on DNS to do the hard work for us.

**Comment by vietj** [comment]
from what I can see, if your host is a name (not an IPV4 or IPV6 address), then the created SocketAddress will contain this value. 

Resolution happens later by Netty's non blocking resolver when the class `ChannelProvider` connects using the bootstrap:

```java
ChannelFuture fut = bootstrap.connect(vertx.transport().convert(remoteAddress));
```

Have you tried configuring this resolver in the `AddressResolverOption` to set a small cache TTL ?

**Comment by vietj** [comment]
See https://vertx.io/docs/vertx-core/java/#_host_name_resolution

**Comment by vietj** [comment]
can you debug this and print the value of the the connection factory server
address to see if it contains an IP address or a to be resolved DNS address
?

**Comment by vietj** [comment]
we don't run such tests that have a complicated setup

**Comment by ashutoshk2206** [comment]
We are also facing similar issues. Is their any update on this?

**Comment by frankcoutinho** [comment]
Hi team,

I'm encountering the same issue with the PostgreSQL driver when using it with AWS RDS during a database failover.
The application fails to automatically reconnect to the new database instance.

This issue is particularly concerning for AWS users who **may not** have added specific health check mechanisms to handle failovers expecting the driver to reconnect automatically. It would be beneficial to re-open this issue, as it appears to be persistent. I **could not** reproduce this behavior locally but it's quite consistentent using AWS multi AZ setup.
