### ISSUE TITLE
`io.vertx.pgclient.PubSubTest` can block the CI build

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-sql-client#1056]
See https://github.com/eclipse-vertx/vertx-sql-client/runs/3947356558?check_suite_focus=true
And https://github.com/eclipse-vertx/vertx-sql-client/runs/3922465636?check_suite_focus=true

**Comment by vietj** [comment]
can it block locally ?

**Comment by tsegismont** [comment]
Outdated, this test is no longer failing
