### ISSUE TITLE
java.lang.NoClassDefFoundError: com/ongres/scram/common/stringprep/StringPreparation

### ISSUE THREAD

**Issue by hantsy** [eclipse-vertx/vertx-sql-client#1059]
In Github actions(Ubuntu VM), it throws an exception when running tests,  **but all tests are passed on my local machine(Windows 10)**.

It is a Hibernate Reactive(Reactive pg client+Postgres)/Spring project, https://github.com/hantsy/spring-puzzles/tree/master/hibernate-reactive

```bash
java.lang.NoClassDefFoundError: com/ongres/scram/common/stringprep/StringPreparation
	at io.vertx.pgclient.impl.codec.InitCommandCodec.handleAuthenticationSasl(InitCommandCodec.java:60) ~[vertx-pg-client-4.1.5.jar:4.1.5]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
```

The complete log can be found here, https://github.com/hantsy/spring-puzzles/runs/4005195925?check_suite_focus=true#step:6:1

Another project reported similar problems, https://github.com/hantsy/spring-puzzles/runs/4005195925?check_suite_focus=true

**Comment by hantsy** [comment]
@vietj  But I have not used it in my sample codes at all. And this issues only occurred on CI environment(Ubuntu/Zulu Java 17), all tests are working well on my local system(Win 10/ Java 17).

**Comment by hantsy** [comment]
Updated to Vertx 4.2.0 for all of my vertx-sandbox, the same result.

**Comment by vietj** [comment]
ok do you have a reproducer ?

**Comment by hantsy** [comment]
There are some vertx sample here, https://github.com/hantsy/vertx-sandbox but I have added this dep into projects and fix the exceptions on Github actions.

This exception only occurred on my Github actions CI building(Ubuntu, Java 17), never happened on my local system(Windows 10, Java 17).

**Comment by haakonn** [comment]
I just encountered this as well, on Ubuntu 20.04 with Java 17 and Vert.x 4.2.1. Interestingly it works when I connect to Postgres 13, but not 14. I'm using TestContainers with the `postgres` image.

The problem is indeed addressed by adding the SCRAM client dependency, but this feels arbitrary and I would prefer to not need to.

**Comment by hantsy** [comment]
@haakonn  Thanks for mentioning the versions, maybe it is same here, I always started PostgreSQL server in a docker for months, it is not updated to the newest PostgreSQL.

**Comment by lijiming** [comment]
I have encountered the  same issue when i enable Postresql@16 authentication. i fixed with adding the missed dependancies.

`        
        <dependency>
            <groupId>com.ongres.scram</groupId>
            <artifactId>common</artifactId>
            <version>2.1</version>
        </dependency>

        
        <dependency>
            <groupId>com.ongres.scram</groupId>
            <artifactId>client</artifactId>
            <version>2.1</version>
        </dependency>`
