### ISSUE TITLE
Oracle Client: expand test coverage

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-sql-client#1066]
Some TCK tests are not yet implemented in the Oracle Client:

- [x] DataTypeTest
- [x] MetricsTestBase
- [x] NullValueEncodeTestBase
- [x] PreparedQueryTestBase
- [x] TracingTestBase
- [x] TransactionTestBase

**Comment by blafond** [comment]
@tsegismont having an issue in Identity tests in Hibernate Reactive related to a prepared statement that returns the generated Identity value.

Executing the following:`insert into EntityWithIdentity (name, position) values (:2 , :3 ) RETURNING id INTO :1`

but I get `Missing IN or OUT parameter at index:: 3`

I get the same error with `insert into EntityWithIdentity (id, name, position) values (:1, :2 , :3 ) RETURNING id INTO :1`

Any suggestions?

**Comment by tsegismont** [comment]
@blafond I believe Oracle doesn't support `RETURNING` a result set. Instead, you should use the `GENERATED_KEYS` property.

There is an example of similar code in the MySQL client code: https://vertx.io/docs/vertx-mysql-client/java/#_mysql_last_insert_id

Can you file an issue so that we update the Reactive Oracle Client doc? Thank you

**Comment by DavideD** [comment]
@blafond, @tsegismont: https://github.com/eclipse-vertx/vertx-sql-client/issues/1074

**Comment by DavideD** [comment]
@tsegismont Do you know if it's possible to query column sof type `raw`?

We have this table:
```
create table UUIDEntity (id raw(255) not null, name varchar2(255 char), primary key (id))
```

An insert seems to work fine but when we try to select the value with:
```
select * from UUIDEntity u where u.id in (?,?)
```
we get the following error:
```
ORA-00932: inconsistent datatypes: expected - got BLOB
```

**Comment by tsegismont** [comment]
@DavideD the `Tuple` was created with 2 Vert.x `Buffer` instances, correct?

I believe in this case it is translated to `prepStmt.setBlob`. As a workaround, perhaps you could convert the value to blob?


```sql
select * from UUIDEntity u where TO_BLOB(u.id) in (?,?)
```

**Comment by DavideD** [comment]
> @DavideD the `Tuple` was created with 2 Vert.x `Buffer` instances, correct?

@tsegismont I've created a test case here: https://github.com/DavideD/vertx-sql-client/commit/b72733af9507a5f197cd1bfed6b11e95afd6310e

I've tried to use the `TO_BLOB` but I couldn't make it work.
Should I create a separate issue?

**Comment by DavideD** [comment]
Issue about Blob error: https://github.com/eclipse-vertx/vertx-sql-client/issues/1085

**Comment by DavideD** [comment]
@tsegismont I'm trying to write a similar test for dates but I can't make it work: https://github.com/DavideD/vertx-sql-client/commit/e528d6182bb9f01fc382d663b945a463261b804a

Am I doing something wrong or is this another issue?

**Comment by tsegismont** [comment]
@DavideD commented in the commit

**Comment by DavideD** [comment]
Thanks!
