### ISSUE TITLE
Update docs for Postgres client support of INET type

### ISSUE THREAD

**Issue by tobiasmuehl** [eclipse-vertx/vertx-sql-client#1070]
Since #992 was implemented, we have INET type support, but [readme](https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-pg-client/README.adoc) still needs to be updated.

Edit: Sorry for the label, this is **not a bug**

**Comment by vietj** [comment]
can you provide a small PR for this @tobiasmuehl ?
