### ISSUE TITLE
Missing method OracleConnectOptions.fromURI()

### ISSUE THREAD

**Issue by blafond** [eclipse-vertx/vertx-sql-client#1071]
All other `*ConnectionOptions` have this method.

see: [#797](https://github.com/eclipse-vertx/vertx-sql-client/issues/797)
and [PG version]: (https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-pg-client/src/main/java/io/vertx/pgclient/PgConnectOptions.java#L53)

Would it make sense to add a couple methods like this one to an interface?

**Comment by tsegismont** [comment]
Thanks for reporting @blafond
