### ISSUE TITLE
[Oracle]  Return a generated identity after an insert

### ISSUE THREAD

**Issue by DavideD** [eclipse-vertx/vertx-sql-client#1074]
In Oracle, when a column is defined as:
```
 create table EntityWithIdentity (id number(19,0) generated as identity, name varchar2(255 char), position number(10,0), primary key (id))
```

It's possible to get the value after an insert as:
```
insert into EntityWithIdentity (id, name, position) values (:1, :2 , :3 ) RETURNING id INTO :1
```

I don't think that client support this syntax at the moment.

**Comment by gavinking** [comment]
I believe that the issue is support for out parameters.

**Comment by gavinking** [comment]
(Though, in principle, the client could support it with something special-purpose like what happens with `LAST_INSERT_ID` on MySQL.)

**Comment by tsegismont** [comment]
@gavinking right, see https://github.com/eclipse-vertx/vertx-sql-client/issues/1066#issuecomment-975319592
