### ISSUE TITLE
[ORACLE] Support for RETURNING BULK COLLECT INTO clause

### ISSUE THREAD

**Issue by amitsinha0** [eclipse-vertx/vertx-sql-client#1084]
#### Issue

I dont think vertx sql client supports RETURNING BULK COLLECT INTO  clause or RETURNING  INTO clause. 

#### Describe the feature

Some time we require to know what data we have alterd. RETURNING clause helps to get this data. 

#### Use cases

In all DML query it can be used.

**Comment by tsegismont** [comment]
Please provide an example query and how you'd like to execute it

**Comment by amitsinha0** [comment]
Sample Query 

`DECLARE 
    TYPE updatedId IS TABLE OF Table1.col2%TYPE; 
    XupdatedId updatedId;
BEGIN 
    UPDATE TABLE1 
         SET col1 = 'OK' WHERE col2 IN ('abc','def')
   RETURNING col2 
        BULK COLLECT INTO XupdatedId; 
   FOR i IN 1..XupdatedId.LAST
   LOOP
        IF i > 1 THEN
            dbms_output.put_line (XupdatedId(i));
        END IF;   
   END LOOP;
END;`

Here we will receive a list of updatedId.

**Comment by tsegismont** [comment]
Do you have a working example with JDBC?
