### ISSUE TITLE
I need to get the underlying java.sql.Connection from Vert.x's io.vertx.sqlclient.SqlConnection (new vertx jdbc api)

### ISSUE THREAD

**Issue by vishnubaghel91** [eclipse-vertx/vertx-sql-client#1088]
**Description**

currently it is not possible to get underlying java.sql.Connection from Vert.x's io.vertx.sqlclient.SqlConnection (new vertx jdbc api)

Here is the solution for vertx legacy jdbc api solved by @tsegismont
https://stackoverflow.com/questions/49650083/i-need-to-get-the-underlying-java-sql-connection-from-vert-xs-sqlconnection/49666826#49666826

Please fix this issue in new api as well

**Link for Stackoverflow**
https://stackoverflow.com/questions/70211263/i-need-to-get-the-underlying-java-sql-connection-from-vert-xs-io-vertx-sqlclien

**Comment by vishnubaghel91** [comment]
@tsegismont Could you please confirm i can make change and create PR for this issue.

**Comment by tsegismont** [comment]
Please go ahead and send a PR
