### ISSUE TITLE
Reactive PG-Client: Exception if fetch size in createStream is smaller than fetched result set

### ISSUE THREAD

**Issue by ukr15** [eclipse-vertx/vertx-sql-client#1089]
### Questions

Reactive PostGres Client throws exception if fetch size in createStream is smaller than fetched result set

### Version

4.2.1

### Context

I encountered an exception which looks suspicious while ...
trying to access a postgres database using the stream interface

### Do you have a reproducer?

There is a reproducer 

### Steps to reproduce

1. sh boot.sh #start postgres database with 51 entries
2. cd vertx-test
3. mvn clean install 
4. java -jar target/vertx-test-2.2.2-fat.jar  # throws execption after 10 entries
5. # if fetch size is set to 100, no exceptions are thrown

### Extra

* Oracle JDK 17, MacOS 12.0.1
[vertx-docker.zip](https://github.com/eclipse-vertx/vertx-sql-client/files/7650870/vertx-docker.zip)

**Comment by vietj** [comment]
your code is actually incorrect, the test method should be instead:

```java
	public void test(Handler<AsyncResult<Void>> handler) {
		pool.withTransaction(conn-> conn.prepare(PG_QUERY).compose(ps -> {
			Promise<Integer> p = Promise.promise();
			RowStream<Row> stream = ps.createStream(50);
			AtomicInteger count = new AtomicInteger(0);
			stream.handler(row->System.out.println("count: "+count.incrementAndGet()));
			stream.endHandler(_res-> p.complete(count.get()));
			stream.exceptionHandler(t-> p.fail(t));
			return p.future();
		})).onSuccess(val -> {
			System.out.println("GOT " + val + " results");
		}).<Void>mapEmpty()
			.onComplete(handler);
	}
````

The transaction will last for the duration of the future that is returned by the function, so when you return a prepared statement, the code will get the prepared statement but the transaction will be closed.

Instead a promise should be created with whatever result you need and the stream should be created within that bock. The promise will remain uncompleted as long as the stream is not finished.
