### ISSUE TITLE
[Oracle] LocalTime returned with the wrong timezone 

### ISSUE THREAD

**Issue by DavideD** [eclipse-vertx/vertx-sql-client#1090]
If I insert a LocalTime, when I select it back is in the wrong timezone.

This is the test I've created: https://github.com/DavideD/vertx-sql-client/commit/dfbff6093df3057d5988289d0a6aff9336cb29ba

I'm not sure if it requires extra configuration, but it doesn't seem the case for the other databases.

Something similar happens with Offsettime

**Comment by tsegismont** [comment]
@DavideD can you try again with latest snapshot now that #1104 has been merged?

**Comment by tsegismont** [comment]
I merged the main branch into your test branch on my laptop, and the issue goes away (`testLocalTime` passes).

Closing as fixed in #1104

**Comment by DavideD** [comment]
Thanks @tsegismont. I've tested it and dates seems to work as expected
