### ISSUE TITLE
[ORACLE] Instant return a String value of oracle.sql.TIMESTAMPTZ@2e760c64

### ISSUE THREAD

**Issue by blafond** [eclipse-vertx/vertx-sql-client#1092]
### Version

 - 4.2.2-SNAPSHOT

### Context

Entity with a column of type Instant returns a result set row value of String when expecting TIMESTAMPZ

Details.. TBD ( @DavideD )

**Comment by DavideD** [comment]
To clarify, this error happens when selecting the `current_timestamp`:
```
 select id, textField, current_timestamp from Example where id = 1
```
