### ISSUE TITLE
Unused pooled connection eviction check

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-sql-client#1125]
https://github.com/eclipse-vertx/vertx-sql-client/blob/27f8a745e8a487137356c512fff45997298cfe16/vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/pool/SqlConnectionPool.java#L360-L368

The `io.vertx.sqlclient.impl.pool.SqlConnectionPool#check` method does not seem to be used

**Comment by vietj** [comment]
I can be safely removed.
