### ISSUE TITLE
On a live server, PgPool.getConnection.result() gives me null value, after a while.

### ISSUE THREAD

**Issue by ebadta81** [eclipse-vertx/vertx-sql-client#1143]
### Version

4.2.3

### Context

On a live server, PgPool.getConnection.result() gives me null value, after a while.

### Do you have a reproducer?

This is, how I create the PgPool:

```
suspend fun getPgConnection(vertx: Vertx, name: String, logger: Logger, connections: Int? = null) : PgPool
{
    val dbStore = configStoreOptionsOf(
        //format = "properties",
        type = "file",
        config = json {
            obj(
                "path" to "db.json",
                "raw-data" to true
            )
        })

    val options = configRetrieverOptionsOf(stores = listOf(dbStore))
    val retriever = ConfigRetriever.create(vertx, options)
    val config = retriever.config.await()
    val moduleElement = config.getJsonObject(name)

    val pgoptions = pgConnectOptionsOf(
        cachePreparedStatements = true,
        preparedStatementCacheSqlLimit = 3000,
        host = "localhost",
        port = 5432,
        user = moduleElement.getString("user"),
        password = moduleElement.getString("password"),
        database = "mydb")
    val poolOptions = poolOptionsOf(maxSize = connections ?: (Runtime.getRuntime().availableProcessors() * 2))
    val pool = PgPool.pool(vertx, pgoptions, poolOptions)
    pool.connection.onFailure {
        logger.error(it.message)
    }

    return pool
}

```

I call  getPgConnection with  connections = 4, and create multiple PgPool instances for different PG users.

This is my code, where the exception happens.

```
	PGPoolClient.getConnection { con ->
		// res is null sometimes
                 val res = con.result()
                 res.preparedQuery(...
```

It is working for a while, and after that, I only get NULL's from con.result().
Restarting the service resolves the problem (for a while).

There is no error message in the postgresql log.

vertx version:  4.2.3
psql version: postgresql13-server-13.5-1PGDG.rhel8.x86_64

### Extra

I log the stack, here it is:

Stack: [server.database.DatabaseVerticle$delinsRouter$1$1.invokeSuspend$lambda-5(DatabaseVerticle.kt:616), io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153), io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75), io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230), io.vertx.core.impl.future.Mapping.onFailure(Mapping.java:45), io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75), io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230), io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23), io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54), io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:43), io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23), io.vertx.sqlclient.impl.pool.SqlConnectionPool$1PoolRequest.lambda$null$0(SqlConnectionPool.java:202), io.vertx.core.net.impl.pool.SimpleConnectionPool$Cancel.run(SimpleConnectionPool.java:666), io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:50), io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:240), io.vertx.core.net.impl.pool.SimpleConnectionPool.cancel(SimpleConnectionPool.java:629), io.vertx.sqlclient.impl.pool.SqlConnectionPool$1PoolRequest.lambda$onEnqueue$1(SqlConnectionPool.java:199), io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:893), io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:860), io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50), io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274), io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22), io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53), io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22), io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:883), io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98), io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170), io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164), io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503), io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986), io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.base/java.lang.Thread.run(Thread.java:829)]

**Comment by vietj** [comment]
it happens because there was a connection error.

you should test first with `con.succeeded()` then get the result otherwise get the error cause.
