### ISSUE TITLE
Oracle uri parser requires a port in the Uri

### ISSUE THREAD

**Issue by DavideD** [eclipse-vertx/vertx-sql-client#1151]
I don't know if this qualify as a bug.

The `OracleConnectionUriParser` is the only one that fails if the port is missing in the uri.
All the other parser set the default port.

You can see the difference  between the regex for  [OracleConnectionUriParser](https://github.com/eclipse-vertx/vertx-sql-client/blob/ae3708f2774e343a0a058f4ff42043090a32d07d/vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleConnectionUriParser.java#L27) and [PgConnectionUriParser](https://github.com/eclipse-vertx/vertx-sql-client/blob/ae3708f2774e343a0a058f4ff42043090a32d07d/vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionUriParser.java#L43).

Example of url without port:
```
oracle:thin:@localhost:database
```

Causes `java.lang.IllegalArgumentException: Cannot parse invalid connection URI: oracle:thin:@localhost:orcl`

For comparison, Postgres set the right default port when the url is `postgresql://localhost/database` 

By the way, something similar happens for the credentials, oracle credentials are like `username/password@` but for all other databases it's `username:password@`.

This is not a big deal, but keeping everything consistent makes it easier to work with different databases.

**Comment by tsegismont** [comment]
The port should be optional, this will be addressed in a PR which I am preparing ATM.

The credentials format is consistent with JDBC url because unlike other reactive clients this one is based on the JDBC client. I will check if we can support both formats.

**Comment by DavideD** [comment]
Thanks a lot @tsegismont!

I don't think you should support both approaches but instead pick one.

All in all I think it would be nice if the connection url would look similar among all the databases but it's not that critical.
I was under the impression that the clients didn't want to reuse the  JDBC convention for the url connection with the Vert.x clients.

This woudl have the nice benefit of allowing the URL for the connection to be consistent between databases:
* Same way to specify credentials
* Same chars separator for URL query and parameters

This makes a lot of code reusable.

That said, including a JDBC style parser for when the url starts with `jdbc:` doesn't seem too hard to include as a future feature.

But I'm working on Hibernate Reactive and we connect to multiple databases so I might be biased.

**Comment by tsegismont** [comment]
Closed in a7edd75d
