### ISSUE TITLE
javascript code of vertx-pg-client 3.9.13 throwing ParserException

### ISSUE THREAD

**Issue by bkoripalli** [eclipse-vertx/vertx-sql-client#1181]
### Version

Which version(s) did you encounter this bug ?
3.9.13

### Context
Below piece of code throwing error.
var PgPool = require("vertx-pg-client-js/pg_pool");
var  connectOptions = {
    "port" : "5432",
    "host" : "localhost",
    "database" : "test",
    "password" : "secret",
    "user" : "postgres",
}

var poolOptions = {
    "maxSize":10,
    "shared": true
}
var client = PgPool.pool(vertx, connectOptions, poolOptions)
pool.getConnection(function (res1, res1_err) {
    if (res1_err != null) {
        console.log(res1_err.getMessage());
        return
    }
})

ERROR: vertx-sql-client-js/row_set.js#88:17<eval>:36:112 Expected an operand but found .
  var j_R = typeof j_arg_0 !== 'undefined' ? j_arg_0 : utils.unknown_jtype;SqlResult.call(this, j_val, RowSet<R>._jtype);
                                                                                                                ^ in file vertx-sql-client-js/row_set.js at line 36
javax.script.ScriptException: SyntaxError: <eval>#88:17<eval>:36:112 Expected an operand but found .
  var j_R = typeof j_arg_0 !== 'undefined' ? j_arg_0 : utils.unknown_jtype;SqlResult.call(this, j_val, RowSet<R>._jtype);
                                                                                                                ^ in <eval> at line number 111 at column number 6
        at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:477)
        at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:461)
        at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
        at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
        at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
        at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at io.vertx.lang.js.JSVerticleFactory$JSVerticle.start(JSVerticleFactory.java:109)
        at io.vertx.core.Verticle.start(Verticle.java:66)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$10(DeploymentManager.java:535)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: <eval>:111:6 SyntaxError: <eval>#88:17<eval>:36:112 Expected an operand but found .
  var j_R = typeof j_arg_0 !== 'undefined' ? j_arg_0 : utils.unknown_jtype;SqlResult.call(this, j_val, RowSet<R>._jtype);

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Extra

* JDK 11.0.14

**Comment by vietj** [comment]
this seems related to ES4X ?

**Comment by bkoripalli** [comment]
@vietj I think it is not related es4x, I tried using one of javascript sample.

 this is my pom looks like

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>io.vertx</groupId>
  <artifactId>maven-verticle-javascript</artifactId>
  <version>3.9.13</version>

  <properties>
    <main.verticle>MyJavaScriptVerticle.js</main.verticle>
  </properties>

  <dependencies>

    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-pg-client</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-lang-js</artifactId>
      <version>${project.version}</version>
    </dependency>

    
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-hazelcast</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <build>
    <resources>
      <resource>
        <directory>${project.basedir}/src/main/js</directory>
      </resource>
    </resources>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>2.3</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <manifestEntries>
                    <Main-Class>io.vertx.core.Launcher</Main-Class>
                    <Main-Verticle>${main.verticle}</Main-Verticle>
                  </manifestEntries>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
              </transformers>
              <artifactSet>
              </artifactSet>
              <outputFile>${project.build.directory}/${project.artifactId}-${project.version}-fat.jar</outputFile>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>1.4.0</version>
        <executions>
          <execution>
            <id>run</id>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>io.vertx.core.Launcher</mainClass>
              <arguments>
                <argument>run</argument>
                <argument>${main.verticle}</argument>
                <argument>-cp</argument>
                <argument>${project.build.outputDirectory}</argument>
              </arguments>
            </configuration>
          </execution>

          <execution>
            <id>run-app</id>
            <goals>
              <goal>exec</goal>
            </goals>
            <configuration>
              <executable>java</executable>
              <arguments>
                <argument>-jar</argument>
                <argument>target/${project.artifactId}-${project.version}-fat.jar</argument>
              </arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>staging</id>
      <repositories>
        <repository>
          <id>staging</id>
          <url>https://oss.sonatype.org/content/repositories/iovertx-3868/</url>
        </repository>
      </repositories>
    </profile>
  </profiles>

</project>
