### ISSUE TITLE
@Lob doesn't work with MSSQL

### ISSUE THREAD

**Issue by s-seidel** [eclipse-vertx/vertx-sql-client#1200]
### Version

4.3.1

### Context

When I try to insert a `byte[]` of more than 8000 bytes, I get the following exception:
```
 io.vertx.mssqlclient.MSSQLException: {number=8016, state=24, severity=16, message='The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 4 ("@P1"): Data type 0xA5 has an invalid data length or metadata length.', serverName='e7af36c1ac41', lineNumber=1}
```
The entity definition is:
```
public class Document extends PanacheEntity {
    @Lob
    public byte[] data;

    @Column(length = 32)
    public String sha256;

    public Long size;
}
```
Everything works fine up to 8000 bytes, but not with more than 8000. I tried various solutions like `@Column(length=1024*1024)` and lots of other things, but I cannot make it work.
Using Quarkus with Panache Reactive.

**Comment by DavideD** [comment]
Could you tell us which version of Quarkus you are using and what's the column type on the database, please?

**Comment by DavideD** [comment]
Nevermind, I can recreate the error

**Comment by s-seidel** [comment]
Great, thanks! I found that when using `String` as field type, I can store arbitrarily long Strings just fine. I had found [this article](https://knowledgebase.progress.com/articles/Article/000042962) with the exact same error message, which lead me to believe it could be something about the SQL data type mapping that causes it.

**Comment by DavideD** [comment]
This adapated quickstart shows the error: https://github.com/DavideD/quarkus-mssql-lobs

**Comment by DavideD** [comment]
Ah, my bad... I should have tested with the latest released version of Hibernate Reactive.
I guess we can close this issue then. I will work in the next Quarkus release
