### ISSUE TITLE
A wrong link in javadoc

### ISSUE THREAD

**Issue by azurvii** [eclipse-vertx/vertx-sql-client#1206]
https://github.com/eclipse-vertx/vertx-sql-client/blob/17719e5db4d305ebeb5f0feac40b11277f0bcd90/vertx-sql-client/src/main/java/io/vertx/sqlclient/Pool.java#L186

Should be `withConnection`, not `withTransaction`.

**Comment by vietj** [comment]
can you provide a PR ?
