### ISSUE TITLE
Oracle client - SSL connection support

### ISSUE THREAD

**Issue by NekiyXX** [eclipse-vertx/vertx-sql-client#1210]
Add support for SSL connection to Oracle DB with sslMode, certPaths and certValues options like it was done in PostgreSQL, MySQL and other clients.

**Comment by tsegismont** [comment]
@NekiyXX for the record, I was able to connect to Oracle Cloud using the "wallet" downloaded from their site https://gist.github.com/tsegismont/3f6f00ca3052ef11f941c93728a01f80

Can you provide more details about your environment? In particular, how would you connect to it using plain JDBC?

The usual encryption parameters from Vert.x Reactive Clients may not be useful here, given the Oracle client is a different kind (a wrapper around JDBC driver reactive extensions).

**Comment by tsegismont** [comment]
The EZConnect format allows to set the protocol to `tcps`. You could this:

```
String connectionUri = String.format(
  "oracle:thin:@tcps://%s:%s/%s",
  DB_SERVER_NAME, SSL_PORT, DB_SID);

// Connect options
OracleConnectOptions connectOptions = OracleConnectOptions.fromUri(connectionUri)
  .setUser(DB_USER)
  .setPassword(DB_PASSWORD)
  .addProperty("javax.net.ssl.trustStore", KEY_STORE_FILE_PATH)
  .addProperty("javax.net.ssl.trustStoreType", "JKS")
  .addProperty("javax.net.ssl.trustStorePassword", KEY_STORE_PASS);

// Pool Options
PoolOptions poolOptions = new PoolOptions().setMaxSize(5);

// Create the pool from the connection URI
OraclePool pool = OraclePool.pool(vertx, connectOptions, poolOptions);
```

**Comment by tsegismont** [comment]
We have this https://vertx.io/docs/vertx-oracle-client/java/#_connection_uri

What's your suggestion for improvement?

**Comment by NekiyXX** [comment]
In our application we can configure three databases MySQL, PostgreSQL and Oracle
So for MySQL client there is section: https://vertx.io/docs/vertx-mysql-client/java/#_using_ssltls
for PostgreSQL section: https://vertx.io/docs/vertx-pg-client/java/#_using_ssltls

After implementing these two I start to search how it should be in Oracle client.
Since the method of working with SSL in Oracle is different, I could not quickly find how to do it and asked a question here:
https://groups.google.com/g/vertx/c/Rxgh-BDpyAo
After this answer I created ticket. 
So I thing for Oracle also should be section "Using SSL/TLS" in documentation like MySQL and PostgreSQL clients.
Thank you very much for help.

**Comment by tsegismont** [comment]
Makes sense @NekiyXX , I will take care of it
