### ISSUE TITLE
con.preparedQuery(sql).execute(tuple).onComplete - onComplete never gets called

### ISSUE THREAD

**Issue by amb1ent** [eclipse-vertx/vertx-sql-client#1218]
### Version

Which version(s) did you encounter this bug ?

4.3.2, 4.3.1

### Context

For one query, with ~7k rows, onComplete is never being called.  For the same query, with different keys, returning 500 rows, onComplete is being called.  Testing the query manually shows it takes < 2 seconds to complete in my database browser.  Is there some buffer size limit or row size limit?  Shouldn't, if a limit is exceeded, onComplete be called with an error status?

### Do you have a reproducer?

I'm afraid nothing that I can share here.

### Extra

running on ubuntu linux 22.04 with jdk 18

**Comment by amb1ent** [comment]
Note, for the failing query, if I just add a "LIMIT 100" to the end of the query, it completes.

**Comment by amb1ent** [comment]
Note 2, this is postgresql version 14 server.

**Comment by vietj** [comment]
that sound weird, can you make an artificial reproducer ? i.e with some useless data

**Comment by amb1ent** [comment]
hum, it could be as simple as running out of memory - the join was joining each row with a column which has a 250kb jsonb since I don't need this column in the results i replaced it with an empty jsonb object and the query just ran OK.  For 7000 rows that gives me a huge memory footprint.

**Comment by vietj** [comment]
OOM will not prevent the client from ending the stream I think, it affects the entire JVM

**Comment by vietj** [comment]
if you have lot of data, you should consider paginating rows or handling rows on the fly and not keep data in heap

**Comment by amb1ent** [comment]
Thanks, I had that as a work-around until I looked again and saw the huge blob that was causing the problem.

**Comment by vietj** [comment]
please reopen if you have a reproducer that demonstrates an actual case in the client

**Comment by amb1ent** [comment]
I have made a reproducer with an extract of my data.  https://github.com/Err0-io/issue-1218-reproducer
This contains a docker file and scripts to start the database with data in docker on port 5555.  Afterwards there's a unit test that freezes for me.  Adding "LIMIT 100" to the sql shows it working.

In an ideal world the concept of a database library that returns all the rows at once means that I will need to use the JDBC driver when I am working on metrics (number crunching in java over huge SQL selects), an interface that let me process row by row and abort if I wish would always be my preference.

**Comment by pablosaavedra-rappi** [comment]
@amb1ent did you take a look at the streaming API for your use case? https://vertx.io/docs/vertx-pg-client/java/#_cursors_and_streaming

**Comment by tsegismont** [comment]
@pablosaavedra-rappi is right, either increase heap size or use cursors/streaming to avoid loading all rows at once
