### ISSUE TITLE
vertx-mysql-client with SslMode.PREFERRED does not work as expected

### ISSUE THREAD

**Issue by NekiyXX** [eclipse-vertx/vertx-sql-client#1219]
Version 4.3.2
It seems where is issue with ssl connection in PREFERRED mode. 

As described in javadoc for PREFERRED mode:
"establish an encrypted connection if the server supports encrypted connections, falling back to an unencrypted connection if an encrypted connection cannot be established"

**The client must try to connect via SSL, and if it cannot, then the Non SSL connection should be used**

I have local mysql db with enabled ssl mode with self-signed cert.
If I try to connect to this db in PREFERRED mode without adding any trustOptions in MySQLConnectOptions or after adding wrong cert I receive exception - 
`java.lang.RuntimeException: cannot initialize platforms cache, PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`
and vertx-mysql-client is not trying to connect with non-ssl

if sslMode = DISABLED it connected with non-ssl as expected
if I use correct cert in pemTrustOptions in "PREFERRED" mode it connected with ssl as expected.

Example: 
```
    ...
    val myConnectOptions = MySQLConnectOptions(merged(commonConf, mysqlConf))
    myConnectOptions.sslMode = SslMode.PREFERRED
    val pool = MySQLPool.pool(vertx, myConnectOptions, PoolOptions(poolConf))
    pool.connection
      .onFailure { err ->
        log.error("Failed to connect. Error is ${err.message}")
        }
      }.onSuccess {
        val ssl = it.isSSL
        log.info("SQL Storage initialized for: $type; SSL: $ssl")
      }
```

**Comment by vietj** [comment]
I think you misunderstood the javadoc : preferred means it will use SSL if the server supports SSL otherwise it will send clear text protocol.

**Comment by NekiyXX** [comment]
Hi @vietj,  but in postgreSQL vertx client PREFER sslMode worked as I expect - if server support ssl and non-ssl in this case client tried to connect wiht ssl and If it cannot(by eny reason) it connected via non-ssl without exception. So now it is different for mysql vertx client and postgressl client.
Also I use liquibase to connect to mysql with PREFERRED mode wwith mysql jdbc driver and it also work as I expected. So I think you are wrong what it is not a bug.

**Comment by vietj** [comment]
I do agree, but that's not the same way to support this. Perhaps we can have a `PREFER` implementation for MySQL as well cc @BillyYccc

**Comment by BillyYccc** [comment]
I think we should support this and I filed a PR for this in https://github.com/eclipse-vertx/vertx-sql-client/pull/1229
