### ISSUE TITLE
Log MSSQL INFO token content or let users handle it

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-sql-client#1223]
When executing commands, the server response may contain an INFO token which holds message/severity data.

Instead of simply ignoring it, we should log the data or let users decide how to handle it.

**Comment by vietj** [comment]
it seems similar to https://vertx.io/docs/vertx-pg-client/java/#_notice_messages

**Comment by tsegismont** [comment]
@vietj right
