### ISSUE TITLE
io.reactiverse.pgclient.Row::getXXX(integer pos) blocked when pos out of range

### ISSUE THREAD

**Issue by solayw** [eclipse-vertx/vertx-sql-client#123]
PgPool client = PgClient.pool(options);
        client.query("select 1,2",rs->{
            Row r=rs.result().iterator().next();
            Integer arr=r.getInteger(2); //blocked here
            
        });

**Comment by EmadAlblueshi** [comment]
@Adam74211

```java
PgPool client = PgClient.pool(options);
client.query("select 1,2", rs -> {
  if(rs.succeeded()) {
    Row r = rs.result().iterator().next();
    try {
      Integer value = r.getInteger(100);
    } catch (IndexOutOfBoundsException e) {
      e.printStackTrace();
    }
  } else {
    rs.cause().printStackTrace();
  }
});
```

Hi, An `IndexOutOfBoundsException` is thrown silently. The connection is not closed. This PR https://github.com/reactiverse/reactive-pg-client/pull/132 is simply `printStackTrace()` so at least you know what is going on because the exception is thrown from non existing position. 

Could you please clarify what did you mean of blocked ?

**Comment by vietj** [comment]
what's the actual issue here ?

**Comment by EmadAlblueshi** [comment]
The client hangs if the index is out bound

**Comment by vietj** [comment]
does it still apply ? this seems to be an issue from the code and not realted to the client itself

**Comment by EmadAlblueshi** [comment]
Well, we should test this and the issue is simply when that exception thrown the user have no idea what happened

**Comment by tsegismont** [comment]
The exception handler of a connection is invoked when a connectivity issue happens, not when any exception is thrown from callback code.

When a runtime exception is thrown in a callback, it is reported to the Vert.x exception handler.

As an alternative, you can work with the futurized API of the Vert.x SQL client, and then such exceptions will be reported to the final handler:

```java
      conn.query("SELECT id, message from immutable").execute().map(rs -> {
        throw new IndexOutOfBoundsException();
      }).onComplete(ar-> {
        // here ar.failed() returns true and ar.cause() is the IndexOutOfBoundsException thrown above
      });
```
