### ISSUE TITLE
Design flow in Pool.connectionProvider(): no way to share Pool.closeFuture with the caller so new ConnectionFactory instance is added to it.

### ISSUE THREAD

**Issue by amkartashov** [eclipse-vertx/vertx-sql-client#1230]
### Questions

I'm trying to implement RDS IAM Auth with hibernate-reactive which [uses vertx-sql-client pool](https://github.com/hibernate/hibernate-reactive/blob/5540b3cc0be768ed57141071b1c079117b67a5d1/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPool.java#L180). Basically, the single thing I need is to update password in connection options on new connection, because it changes every 15 minutes.

I'm using this approach: https://vertx.io/blog/dynamic-db-pool-config-with-sql-client/ - create new factory with MySQLDriver.INSTANCE.createConnectionFactory() for every new connection.

The problem I see is that this new factory differs from default factory created [during pool creation](https://github.com/eclipse-vertx/vertx-sql-client/blob/bef0b4b736e09e00d480d5891758f8223222bc1a/vertx-mysql-client/src/main/java/io/vertx/mysqlclient/spi/MySQLDriver.java#L58) - it's not added to pool CloseFuture. This means that this factory won't be closed on pool.close().

I could call factory.close() before creating new factory, but I believe this will close current connections created by old factory.

Mb this can be solved by adding getter method for Pool.closeFuture or by changing connectionProvider so it accepts ConnectionFactory instead.

### Version

4.3.2

### Extra

Initially I was expecting that it would be possible to call setPassword() method on ConnectionOptions somehow. But Pool does not keep ConnectionFactory and ConnectionOptions; ConnectionFactory keeps ConnectionOptions, but calls it's getPassword() only once in constructor...

What I want is to be able to reuse ConnectionFactory/ConnectionOptions created for the Pool, because it has specific settings defined in Driver implementation like MySQLDriver.newPool()/newPoolImpl()

**Comment by vietj** [comment]
The blog actually mentions it.

**Comment by amkartashov** [comment]
> yes you need to manage the factory and close, however the connections opened by this factory are actually closed when the pool is closed, so it should not leak resources.

New factory is not attached to the pool in any way. So if pool closes, factory is not closed and so are connections. In current implementation there is no way to get CloseFuture from the pool and attach it to the factory.

**Comment by amkartashov** [comment]
Ideal solution for me would be that `ConnectionFactory` does call `ConnectionOptions.getPassword()` every time it creates new connection. This approach from the blog is cumbersome and way too complex.

**Comment by vietj** [comment]
options are supposed to be immutable, one option could be to have a `Supplier<ConnectOptions>` instead I think that is called every time a connection is created

**Comment by vietj** [comment]
https://github.com/eclipse-vertx/vertx-sql-client/issues/1241
