### ISSUE TITLE
MySQL client should provide columnDescriptors with LONGVARCHAR JDBCType for TEXT types

### ISSUE THREAD

**Issue by DavideD** [eclipse-vertx/vertx-sql-client#1239]
[See this issue in Quarkus](https://github.com/quarkusio/quarkus/issues/22254#issuecomment-1259563555).

Is there any particular reason for this or it's a bug?

@fedinskiy:
```
I took a look into code for Postgress[1] and MySQL[2] and it looks like the text case is not handled properly in the latter.

[1] https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataType.java
[2] https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/datatype/DataType.java
```

**Comment by vietj** [comment]
this requires investigations @DavideD , @BillyYccc any idea ?

**Comment by gavinking** [comment]
> the mysql driver did return a `JDBCType.BLOB` for both MySQL BLOB and TEXT types.

But surely that's simply *wrong*! TEXT is is MySQL's CLOB type, it's not a BLOB.

**Comment by BillyYccc** [comment]
sorry for the late reponse..I just made a PR in https://github.com/eclipse-vertx/vertx-sql-client/pull/1339 to address this issue, I will try to backport it to 4.x later

**Comment by vietj** [comment]
will close when fix is backported to 4.x branch
