### ISSUE TITLE
Tuple is not working if access primitive array

### ISSUE THREAD

**Issue by zero88** [eclipse-vertx/vertx-sql-client#1247]
### Version

4.x.x

### Context

With this check, the result will be `false` if an object is a primitive array, then the accessor will throw ClassCastException
```java
val.getClass() == Object[].class
```

Affect to all `getArrayOfXXX` where XXX is type can be primitive type (Boolean/boolean, Integer/int...)

E.g: 
https://github.com/eclipse-vertx/vertx-sql-client/blob/75ee2e4ad73d0fcf736efd80f5ea4569b72f898a/vertx-sql-client/src/main/java/io/vertx/sqlclient/Tuple.java#L802-L808

**Comment by vietj** [comment]
I think instead we should not use primitive arrays

**Comment by vietj** [comment]
where does that happen ?
