### ISSUE TITLE
Type cache pollution: type io.vertx.pgclient.impl.codec.PgCodec

### ISSUE THREAD

**Issue by Sanne** [eclipse-vertx/vertx-sql-client#1253]
In the same scenarios tested as for #1251 , we have this other entry in the type pollution report:

```
5:	io.vertx.pgclient.impl.codec.PgCodec
Count:	4995275
Types:
	io.netty.channel.ChannelOutboundHandler
	io.netty.channel.ChannelInboundHandler
Traces:
	io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
		class: io.netty.channel.ChannelOutboundHandler
		count: 1489684
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		class: io.netty.channel.ChannelInboundHandler
		count: 1300795
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
		class: io.netty.channel.ChannelInboundHandler
		count: 1147801
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
		class: io.netty.channel.ChannelOutboundHandler
		count: 599837
	io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
		class: io.netty.channel.ChannelOutboundHandler
		count: 456909
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
		class: io.netty.channel.ChannelInboundHandler
		count: 199
	io.netty.channel.ChannelHandlerMask.mask0(ChannelHandlerMask.java:94)
		class: io.netty.channel.ChannelInboundHandler
		count: 31
	io.netty.channel.ChannelHandlerMask.mask0(ChannelHandlerMask.java:123)
		class: io.netty.channel.ChannelOutboundHandler
		count: 19
```

I've heard @vietj and @franz1981 have been looking at a similar one in other vert.x projects, so I'll defer this one to someone more knowledgeable.

**Comment by franz1981** [comment]
This is solved by upgrading to Netty 4.1.84.Final thanks to https://github.com/netty/netty/pull/12806

**Comment by Sanne** [comment]
great thanks :) I'll close this?

**Comment by franz1981** [comment]
Yep, we are aware of that, they should happen on bootstrap and cached forever, hence they will always have that magnitude

**Comment by franz1981** [comment]
I would open something for SslHandler that it's not fixed yet on Netty (and probably won't be) meaning that real users will get very bad performance out of it, scalability wise :( we should probably advertise for that

**Comment by tsegismont** [comment]
A few weeks ago, I ran @franz1981 's tool on our projects and found that `TupleInternal` was the only improvement we could make (`PgCodec` is a `CombinedChannelDuplexHandler` so, as he said and you found, the situation will be improved by the Netty upgrade).

**Comment by tsegismont** [comment]
Thank you @Sanne for these reports btw
