### ISSUE TITLE
Missing  com.ongres.scram : client

### ISSUE THREAD

**Issue by serajhqi** [eclipse-vertx/vertx-sql-client#1266]
### Question

I followed [Reactive PostgreSQL Client](https://vertx.io/docs/vertx-pg-client/java/) instruction.

### Version

4.37

### Context

I encountered the following error while I was trying to connect to the database:

```
Could not connect java.lang.NoClassDefFoundError: com/ongres/scram/common/stringprep/StringPreparation
```

### Steps to reproduce

1. Follow the [instruction](https://vertx.io/docs/vertx-pg-client/java/)

### Extra

I installed the dependency manually into my project to make it work.

```
<dependency>
    <groupId>com.ongres.scram</groupId>
    <artifactId>client</artifactId>
    <version>2.1</version>
</dependency>
```

**Comment by tsegismont** [comment]
Indeed, this is documented here: https://vertx.io/docs/vertx-pg-client/java/#_sasl_scram_sha_256_authentication_mechanism
