### ISSUE TITLE
NoStackTraceThrowable Exception is thrown when Postgres DB connectivity is lost

### ISSUE THREAD

**Issue by jaiprasad266** [eclipse-vertx/vertx-sql-client#1269]
### Questions

Quarkus App - Rest Operation to fetch data from Postgres DB

So when the db connection is lost while the service is running and the service receives a request , the app is throwing NoStackTraceThrowable exception. This is a generic exception and is preventing from custom handling of db connectivity issue. Say if u want add DB connect exception to circuit breaker

### Version

Which version(s) did you encounter this bug ?

Quarkus version : 2.9.0.Final
Client Lib : quarkus-reactive-pg-client

### Context

When db connection is lost temporarily and the app receives a REST request , the app throws NoStackTraceThrowable exception

### Extra

* Anything that can be relevant such as OS version, JVM version
* java 11 
* container image quarkus : registry.access.redhat.com/ubi-minimal:8.6

**Comment by tsegismont** [comment]
Thank you @jaiprasad266
