### ISSUE TITLE
Base exception class for all SQL Clients

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-sql-client#1274]
Currently, each client comes with its own exception class for database access problems.

Projects that are built upon the core SQL Client API, like Hibernate Reactive, don't have access to details.

A base exception class can be added for all SQL Clients, which would give (when known):

- error code
- sqlState (XOPEN or SQL:2003 conventions)

IMPORTANT: this does not mean clients will now only report exceptions extending the base class. They could still report raw `VertxException` or `NoStackTraceThrowable`, when the problem does not come from a DB interaction.

**Comment by dozsa** [comment]
I was just thinking of the same enhancement the other week when working with both the Postgres and Oracle clients. This will be helpful for projects that need to support multiple database types. So quite interested in this.

**Comment by gavinking** [comment]
Thanks for this.
