### ISSUE TITLE
Mysql Alias not in result set 

### ISSUE THREAD

**Issue by samu-developments** [eclipse-vertx/vertx-sql-client#1279]
### Version

`io.vertx:vertx-mysql-client:4.7.3`

### Context

Alias is not in result set, so not possible to do `row.getString("a.name")`. If `table_a` and `table_b` has same column `name`, it also seems unspecified what is returned in `row.getString("name")`. Only workaround I found is to do more specific select, eg. `SELECT a.name as a_name`.

My use case is that we join two tables and then extract data from the result, where we extract e.g. the `updated` column in each table.

### Do you have a reproducer?

```
SELECT *
FROM table_a AS a
JOIN table_b as b on b.id == a.id
```

where table_a and table_b has a "name" cloumn. Result set contains only one "name" column, when "a.name" and "b.name" is expected.

**Comment by tsegismont** [comment]
Actually, this is not a bug, the name of the column is what MySQL server returns. The same behavior shall be seen with JDBC.

If you need the `updated` column without prefixing all of them, you could do:

```mysql
SELECT *, a.updated updated_a, b.updated updated_b
FROM table_a AS a
JOIN table_b as b on b.id == a.id
```

Note that it's better to select only the columns needed, to minimize the amount of data sent over the network.
