### ISSUE TITLE
[Postgres] Instant is not being accepted as a parameter for a column of type TIMESTAMPTZ

### ISSUE THREAD

**Issue by fcoutinho-uolinc** [eclipse-vertx/vertx-sql-client#1283]
When you pass a `Instant` to the driver mapping to a `TIMESTAMPTZ` column, you get the following error:

> Parameter at position[7] with class = [java.time.Instant] and value = [1970-01-01T00:00:00Z] can not be coerced to the expected class = [java.time.LocalDateTime] for encoding.

> io.vertx.core.impl.NoStackTraceThrowable: Parameter at position[7] with class = [java.time.Instant] and value = [1970-01-01T00:00:00Z] can not be coerced to the expected class = [java.time.LocalDateTime] for encoding.

### Version

`vertx-pg-client:4.3.6`

**Comment by tsegismont** [comment]
Duplicates #1122

**Comment by shaonianA** [comment]
Hi @tsegismont, I think this issue stands apart from the previous discussions. The Instant class in Java, designed to be locale-independent, can be seen as functionally equivalent to OffsetDateTime. As such, it could be worthwhile to consider support for it. The thread referenced mostly focuses on locale matters, which aren't applicable to Instant. I believe this distinction merits a separate consideration.
