### ISSUE TITLE
Support dynamic password rotation in SQL Clients pool

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-sql-client#1289]
Security policies can require dynamic password rotation.

As examples of implementation, we have [Vault Dynamic DB Credentials](https://developer.hashicorp.com/vault/tutorials/db-credentials/database-secrets) and [RDS with AWS Secrets Manager](https://aws.amazon.com/blogs/security/rotate-amazon-rds-database-credentials-automatically-with-aws-secrets-manager/).

When a pool is created, it takes `SqlConnectOptions` which defines credentials for the the lifetime of the pool.

This prevents from creating new connections with updated credentials if password is rotated after the creation of the pool.

**Comment by vietj** [comment]
it is alraedy possible to implement this use case using https://vertx.io/blog/dynamic-db-pool-config-with-sql-client/

we should instead move the blog to the documentation.

**Comment by tsegismont** [comment]
Thanks for heads-up, I'll take care of it

**Comment by tsegismont** [comment]
Replace with #1291
