### ISSUE TITLE
Direct usage of PgConnection results in memory leak

### ISSUE THREAD

**Issue by robp94** [eclipse-vertx/vertx-sql-client#1302]
### Version

Which version(s) did you encounter this bug ?
quarkus 2.16.5 which uses vertx 4.3.7 and vertx-pg-client 2.30.1.

### Context

Using PgConnection directly, there seems to be a memory leak. PgConnectionFactory stays in memory after close.

### Do you have a reproducer?

https://github.com/robp94/vertx-pg-memory
Relevant code is in `org.acme.GreetingResource`.
See README for Instructions how to run. Use scripts to run some requests and make a memory dump.

Look for 
![image](https://user-images.githubusercontent.com/42009775/229520720-3c7a6821-8a1d-4361-a6f5-a70597cc916a.png)

### Steps to reproduce

1. Open connection
2. Use it
3. Close it
4. GC cannot clean up factory and some other objects. Connections on the other hand get cleaned up.
```
PgConnectOptions connectOptions = new PgConnectOptions().setPort(port).setHost(host).setDatabase(databaseName).setUser(username).setPassword(password);
PgConnection.connect(vertx, connectOptions);
```
Workaround:
```
ContextInternal context = ContextInternal.current();
context.removeCloseHook(((PgConnectionImpl) c.getDelegate()).factory());
Promise<Void> promise = Promise.promise();
((PgConnectionImpl) c.getDelegate()).factory().close(promise);
```

### Extra

See https://groups.google.com/g/vertx/c/ddQek1aGXmE

* Anything that can be relevant such as OS version, JVM version
* ubuntu 22.04, kubernetes
* JDK 17

**Comment by tsegismont** [comment]
Thank you for reporting this @robp94, we'll look into it asap

**Comment by tsegismont** [comment]
Hi @robp94 , would you be able to try this [patch](https://patch-diff.githubusercontent.com/raw/eclipse-vertx/vertx-sql-client/pull/1309.patch)?
