### ISSUE TITLE
PreparedQuery caching before model change produces errors on future correct calls.

### ISSUE THREAD

**Issue by FDoKE** [eclipse-vertx/vertx-sql-client#1321]
### Questions

If prepared statement is cached, and column type changes.
All future prepared statements with new column type will fail.

### Version

4.3.8

### Context

Looks like prepared statements should be evicted if passed parameters don't match on execute?

### Do you have a reproducer?

Follow steps

### Steps to reproduce

1. Create pool with 1 connection for simplicity
2. Create table TBL (id int)
3. Execute prepared statement:
SELECT * FROM tbl WHERE id = ?
id = 1, it succeed
4. drop/create same table with different column type
TBL (id varchar)
5. Execute prepared statement:
SELECT * FROM tbl WHERE id = ? (same query)
id = 'qweqwe'
Exception will be raised:
Parameter at position[%d] with class = [%s] and value = [%s] can not be coerced to the expected class = [%s] for encoding.

All future calls for this prepared statement will fail.

### Extra

Myabe its ok behaivor, are there ways to evict caches manually?

**Comment by vietj** [comment]
@FDoKE this is kind of expected, to avoid that you should disable prepared query caching

**Comment by tsegismont** [comment]
@vietj I believe we detect such errors for Pg and then evict automatically, don't we?

**Comment by FDoKE** [comment]
@tsegismont postgresql
@vietj yes - disabling will help, thats true, but maybe there should be a way to manually clear cache on demand (we know when model changes)? But for my perspective it looks suspicious that changing schema will break futher calls on cached prepared query and there is no way to avoid that.

**Comment by tsegismont** [comment]
We'll look into this @FDoKE . Julien was proposing to disable prepared query caching in the meantime (or to restart your nodes).

**Comment by vietj** [comment]
> @vietj I believe we detect such errors for Pg and then evict automatically, don't we?

yes only for PG, perhaps we can do the same for mysql ?
