### ISSUE TITLE
Row to Json conversion may prevent reading a timestamp as Instant

### ISSUE THREAD

**Issue by keksipurkki** [eclipse-vertx/vertx-sql-client#1323]
### Version

Vert.x 4.4.1 / PostgreSQL 15

### Context

When a timestamp with time zone column is set to an ISO date value such as 2023-01-01, Vert.x PostgreSQL client returns the value as '2020-01-01T00:00Z'.

This is problematic since e.g. Java's Instant::parse requires an ISO 8601 timestamp with seconds included. Consequently, doing row.toJson().getInstant('created') fails with a DateTimeParseException.

Expected behavior: Ensure the returned timestamp includes seconds, i.e. '2020-01-01T00:00:00Z' in the above example.

### Do you have a reproducer?

Here you go:
https://github.com/keksipurkki/vertx-db-timestamp-bug/tree/main

### Steps to reproduce

  1.  Clone the repository
  2. Build and run
  3. Observe that the demo query fails with a DateTimeParseException.

**Comment by keksipurkki** [comment]
Did some debugging and the issue arises in io.vertx.pgclient.impl.codec.DataTypeCodec on line 1781. The TIMESTAMPTZ_FORMAT controls the way in which Vert.x PgClient decodes the timestamp value to OffsetDateTime.

**Comment by pablosaavedra-rappi** [comment]
@keksipurkki seemed to be in the toJson method itself, LocalDateTime#toString omits seconds if not present.

**Comment by tsegismont** [comment]
Fixed by #1396 1396
