### ISSUE TITLE
Improve database client docs; mention Pool static methods

### ISSUE THREAD

**Issue by OddsJanttu** [eclipse-vertx/vertx-sql-client#1327]
The documentation (at least in the case PostgreSQL and JDBC clients) examples use specific `Pool` and `SqlClientOptions` implementations, with no mention of `Pool.pool()`, `SqlConnectOptions` and other less tightly coupled options.

The examples should nudge more in the direction of client implementation agnostic code.

**Comment by vietj** [comment]
Actually in 4.5 we promote pool builders instead of static pool methods
