### ISSUE TITLE
Autogenerated RowMapper class missing singleton INSTANCE in RxJava/Mutiny

### ISSUE THREAD

**Issue by kenkania** [eclipse-vertx/vertx-sql-client#1330]
In vertx-sql-client-templates, the mutiny version of RowMapped autogenerated classes is missing a static singleton INSTANCE (unlike the ParametersMapped ones).

RowMapperGen outputs `@GenIgnore` on the static singleton INSTANCE, which means that it isn't carried over to the mutiny autogenerated code (IIUC). ParametersMapperGen doesn't have this, so its INSTANCE is carried over to mutiny. It is slightly cumbersome to use the mutiny version of the interface generated by RowMapperGen because of this.

#### Example Non-Mutiny Outputs Today
RowMapperGen's output looks like:

```
@io.vertx.codegen.annotations.VertxGen
public interface MyClassRowMapper extends io.vertx.sqlclient.templates.RowMapper<MyClassResponse> {
  @io.vertx.codegen.annotations.GenIgnore
  MyClassRowMapper INSTANCE = new MyClassRowMapper() { };
  ...
}
```
whereas ParametersMapperGen's is:

```
@io.vertx.codegen.annotations.VertxGen
public interface MyClassParametersMapper extends io.vertx.sqlclient.templates.TupleMapper<MyClassResponse> {
  MyClassParametersMapper INSTANCE = new MyClassParametersMapper() {};
  ...
```

#### Contribution

I will put up a small PR for this if acceptable.

**Comment by tsegismont** [comment]
Fixed in #1333
