### ISSUE TITLE
Incorrect java documentation for SqlResult.rowCount()

### ISSUE THREAD

**Issue by akshaypatidar1999** [eclipse-vertx/vertx-sql-client#1370]
### Version

All

### Context

The `rowCount` method returns the `Rows matched` during the `UPDATE` operation but the documentation says that it returns the affected rows. These values can be different in some cases. Example

```sql
create table test(id int auto_increment, primary key(id));

insert into test(id) values(1);
```

Now if I run the query `update test set id=1 where id=1;`. In this case rows matched will be `1` but changes rows will be `0`. But the `rowCount` method returns 1.

https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/codec/CommandCodec.java#L140

https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-sql-client/src/main/java/io/vertx/sqlclient/SqlResult.java#L38

**Comment by tsegismont** [comment]
You can set the [`useAffectedRows`](https://vertx.io/docs/vertx-mysql-client/java/#_useaffectedrows) option to control the MySQL Client behavior.
