### ISSUE TITLE
Tracing: Support opentelemetry semantic conventions

### ISSUE THREAD

**Issue by cyhii** [eclipse-vertx/vertx-sql-client#1383]
#### Describe the feature

The tracing support seems like following `opentracing` semantic conventions. It's archived and being suggested to use `opentelemetry`. It may need some update.

#### Use cases

Just support opentelemetry semantic conventions, see [docs](https://opentelemetry.io/docs/specs/semconv/database/database-spans/)

**Comment by vietj** [comment]
@cyhii it is not clear what you are taking about, can you elaborate ?

if that is about the names using in vertx-core and vertx-sql-client we should keep these names and the open tracing implementation should translate them to the appropriate name for open tracing

**Comment by cyhii** [comment]
Get it. Thanks for your works!
