### ISSUE TITLE
Pg client throw exception when passing array of primitives

### ISSUE THREAD

**Issue by DavideD** [eclipse-vertx/vertx-sql-client#1390]
Given the following table:
```
create table Basic (id integer not null, booleanArray boolean array)
```
And the given query:
```
insert into Basic (booleanArray,id) values ($1,$2)
```

The client will throw an exception if the parameter for the column `booleanArray` is a `boolean[]` (primitive):
```
io.vertx.core.impl.NoStackTraceThrowable: Parameter at position[9] with class = [[Z] and value = [[Z@78af5164] can not be coerced to the expected class = [[Ljava.lang.Boolean;] for encoding.
```

It works fine if the parameter is of type `Boolean[]`.
This also happens for the other types:  `double`, `float`, `long`, `short`, ...

**Comment by tsegismont** [comment]
Thanks for reporting this
