### ISSUE TITLE
Sql Client always disables HostnameVerificationAlgorithm

### ISSUE THREAD

**Issue by s32eerdo** [eclipse-vertx/vertx-sql-client#1419]
### Version

4.5.4

### Context

I have a problem with this change: https://github.com/eclipse-vertx/vertx-sql-client/pull/1408/files#diff-b91b8b54ee0b359235e889c382c813fa0fcda35d321c630ebb5d3bda788cc21e

When we create a Pool for database connection even it has a configuration like `PgConnectOptions.hostnameVerificationAlgorithm = "HTTPS"`, this is overwritten by `netClient()` call when the connection is initialized by `Pool.connection`.
I think it should first check whether the `hostnameVerificationAlgorithm` is set or not. Then, it should set it to "".

**Comment by vietj** [comment]
for which database ? internally the algorithm is set depending on the database and mode of connection (mysql,pg)

**Comment by Traderjoe95** [comment]
I can confirm the bug for both PG and MySQL. I dug a bit deeper in the PG client, and it uses the `NetClient` almost directly. The `NetClient` is instantiated by `ConnectionFactoryBase.netClient()`, which sets the hostname verification algorithm hardcoded to `""` (line 61). The SSL connection upgrade of the PG client only delegates to `NetSocket`'s `upgradeToSsl` method. Because of that, I suppose, the empty hostname verification algorithm is used.

For MySQL, the flow looks a bit different, but I found a call to `NetSocket.upgradeToSsl` as well.

We have tests running with Testcontainers where we inject a certificate with a wrong hostname into the container. The connection with the `VERIFY_FULL` (PG) / `VERIFY_IDENTITY` (MySQL)  modes is correctly rejected on Vert.x 4.5.3 but there it connects without error on 4.5.4.

**Comment by vietj** [comment]
can you provide a reproducer without testcontainer ? e.g. you can use vertx hosts config to resolve a DNS name to localhost

**Comment by Traderjoe95** [comment]
I added a reproducer to the `TLSTest.java` for PG, based on the 4.5.4 release tag:

https://github.com/Traderjoe95/vertx-sql-client/blob/928d01bc6190edb9b9b7ffed90b42e524d8c3fc8/vertx-pg-client/src/test/java/io/vertx/pgclient/TLSTest.java#L95
https://github.com/Traderjoe95/vertx-sql-client/commit/928d01bc6190edb9b9b7ffed90b42e524d8c3fc8

The method on L95 tests that the connection fails with an invalid hostname (that test is failing). The other one on L115 tests that a correct hostname works fine. That one passes (as no hostname verification is done).

Please let me know if this is enough. I know that the test still uses Testcontainers, but if you still need a reproducer without testcontainers (or another one for MySQL), I should be able to create one for you. This was only the easiest way to go.

**Comment by vietj** [comment]
@Traderjoe95 thanks, it's just what I needed can you provide the same for MySQL ?

**Comment by Traderjoe95** [comment]
There you go:

https://github.com/Traderjoe95/vertx-sql-client/commit/01dee141034a558aff75cc814fa77d75dd7a000c

MySQL: Lines 266-311
https://github.com/Traderjoe95/vertx-sql-client/blob/01dee141034a558aff75cc814fa77d75dd7a000c/vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLTLSTest.java#L267

PG: Lines 94-134
https://github.com/Traderjoe95/vertx-sql-client/blob/01dee141034a558aff75cc814fa77d75dd7a000c/vertx-pg-client/src/test/java/io/vertx/pgclient/TLSTest.java#L95

**Comment by Traderjoe95** [comment]
Ah, just noticed a little gotcha: The test for successful connection on MySQL fails when hostname verification is enabled, because the CN from the certificate is no valid domain name. I think I will just create a PR fixing the issue and update the certificates there.

**Comment by Traderjoe95** [comment]
Just opened PR #1426, @vietj please have a look

**Comment by vietj** [comment]
@Traderjoe95 can you provide a PR for the master branch ?

**Comment by Traderjoe95** [comment]
@vietj done: #1427 

There seems to be a problem in the MSSQL module with a recently added change in `vertx-core` SNAPSHOT

**Comment by vietj** [comment]
I will have a look @Traderjoe95 and then you can rebase, it might be the change to trustAll ?

**Comment by vietj** [comment]
yes we did simplify this in master, since the SSL options carries it. You
should rebase your PR on latest master
