### ISSUE TITLE
MySQLConnectionImpl.resetConnection() does not clear PreparedStatementCache

### ISSUE THREAD

**Issue by KitanoTom** [eclipse-vertx/vertx-sql-client#1424]
### Version

4.5.4

### Issue

The ResetConnection in MySQL (`COM_RESET_CONNECTION`) releases the prepared statements, but `MySQLConnectionImpl.resetConnection()` does not clear the `PreparedStatementCache`. Therefore, executing the same query after resetConnection(), it will cause an error like the following.

```
io.vertx.mysqlclient.MySQLException: {errorMessage=Unknown prepared statement handler (1) given to mysql_stmt_precheck, errorCode=1243, sqlState=HY000}
```

**Comment by tsegismont** [comment]
Fixed by 878c4542
