### ISSUE TITLE
Mark scram-client in vertx-pg-client as required

### ISSUE THREAD

**Issue by jorsol** [eclipse-vertx/vertx-sql-client#1466]
#### Describe the feature

The `scram-client` dependency of the vertx-pg-client module is marked as optional, but since PostgreSQL 14+, the default value for `password_encryption` is `scram-sha-256`, so this dependency should not be marked as optional.

#### Use cases

To avoid recurring issues of failed authentication reports (due to the missing dependency), the dependency should be required. This improves the user experience when connecting to postgres and it does not have any downside.

#### Contribution

Who should implement this feature ? are you volunteering for implementing this feature or
do you know that is able and willing implement this feature ?

Yes, I could volunteer if approved, it should be just removing the optional tag and updating the documentation.

**Comment by vietj** [comment]
actually we are more leaning toward making it optional https://github.com/eclipse-vertx/vertx-sql-client/pull/1461

**Comment by vietj** [comment]
at least in master, so I do have mixed feelings about this

**Comment by jorsol** [comment]
Postgres can use SCRAM auth since version 10+ and is used by default in Postgres 14+, in the end, more and more users will require the dependency to be available rather than be optional, at least is a good step to show an error message about the missing dependency.

**Comment by vietj** [comment]
@jorsol yes your words reasonnate, perhaps I should change my mind and make it the default instead of being optional.

The scram dependency seems to be a proper java module (explicit) and in that case I don't see this being an issue
