### ISSUE TITLE
Wrong value inserted in table with jsonb column

### ISSUE THREAD

**Issue by DavideD** [eclipse-vertx/vertx-sql-client#1467]
For PostgreSQL and Vert.x SQL client 4.5.10

Given the following table:
```sql
create table BookWithJson (id integer not null, title varchar(255), author jsonb, primary key (id))
```

The code:
```java
String sql = "insert into BookWithJson (author,price,title,id) values (cast($1 as jsonb),$2,$3,$4)";
Tuple parameters = Tuple.of( "{\"name\":\"Peng\",\"surname\":\"Shepherd\"}", "The Book of M", 3 );
sqlConnection.preparedQuery( sql ).execute( parameters );
```

will insert the row (using `psql`):
```
 id |     title     |                        author                        
----+---------------+-------------------------------------------------------------------------
  5 | The Book of M | "{\"name\":\"Peng\",\"surname\":\"Shepherd\"}"
```

instead of:
```
 id |     title     |                        author                        
----+---------------+-------------------------------------------------------------------------
  5 | The Book of M | {"name":"Peng","surname":"Shepherd"}
```

I'm not even sure how it's possible, because it's inserting a string in a `jsonb` column.
I will try to create a test if necessary.

**Comment by tsegismont** [comment]
It's not a bug: a plain string is a valid JSON value, as per [rfc 7159](https://datatracker.ietf.org/doc/html/rfc7159#section-3).

What happens here is that a string value is stored in the jsonb column, regardless of its content.

If you want the content of the string to be converted to a JSON object, you must do it in the Java code with `new JsonObject(string)` or in the SQL query

**Comment by DavideD** [comment]
Thanks.
I was surprised because it didn't seem to work when I tried, but it was just a typo I made.

**Comment by DavideD** [comment]
@tsegismont  On second though, are we sure that this is not a bug? 

It's true that I'm passing a parameter as String, but the SQL query is calling a function that should convert it to a propert JSON object. How come this is not happening?

**Comment by tsegismont** [comment]
`cast` is not ignored, it correctly converts a string to `jsonb`. When the query is prepared, postgres doesn't know what kind of data it may expect, so when vert.x sends a string on the wire, it considers it as valid `jsonb` content.

If you want a conversion of the content of the string, give Pg a hint with `cast($1::text as jsonb)`
