### ISSUE TITLE
Why PgException No stack

### ISSUE THREAD

**Issue by zclcs** [eclipse-vertx/vertx-sql-client#1474]
### Questions

printStackTrace() only have message no stack

### Version
4.5.10

![image](https://github.com/user-attachments/assets/1b229a22-74be-489e-826d-9d36f2798a4e)

**Comment by zclcs** [comment]
![image](https://github.com/user-attachments/assets/ca1afb05-16f1-47f2-b381-f0ddf4c045cf)

**Comment by tsegismont** [comment]
Creating a stacktrace has a cost, and in this case, the cost is not justified: the problem is that the "users" table does not exist in the database. Indicating where the problem was detected in the Java application won't help solving that problem.
