### ISSUE TITLE
Indexing java documentation

### ISSUE THREAD

**Issue by Sxubas** [eclipse-vertx/vertx-sql-client#149]
I find the docs really useful, but I feel really frustated when searching anything specific. 

Earlier on I tried CTRL+F and 'autocommit' to learn about managing this in a connection but (as it is implemented differently) could not get any results. Later on, going section by section discovered how it was meant to be done.

Most docs I've read have ways of navigating through them (even Javadoc!), it would be awesome to reactive-pg-client to also have it. I recommend using the huge whitespace below the title, it fits really nice for an index:

![imagen](https://user-images.githubusercontent.com/19129356/44302544-814da400-a2f0-11e8-9c9a-c1ea6a4e67d1.png)

Just an small usability detail. Thanks in advance

**Comment by vietj** [comment]
@Sxubas I think right now we are using a template provided out of the box by GitHub to format using Jekyll, we should investigate wether it's possible to improve it.

**Comment by BillyYccc** [comment]
Closing this since the original project has been integrated into Vert.x stack and got a new style of documentation in https://vertx.io/docs/vertx-pg-client/java/.
