### ISSUE TITLE
 Support for scram-sha-256 password authentication type

### ISSUE THREAD

**Issue by ltkn** [eclipse-vertx/vertx-sql-client#150]
Hi,

Would you consider adding scram-sha-256 authentication type support?
This feature is present in official driver: https://github.com/pgjdbc/pgjdbc/pull/842

Below more information on my test/setup.

Logs I get using latest versions of client:

> 
> 2018-08-19 13:48:14.565 DEBUG 8471 --- [ntloop-thread-0] io.netty.handler.ssl.SslHandler          : [id: 0xa9d7e821, L:/127.0.0.1:45882 - R:/127.0.0.1:5432] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
> Failure: Authentication type 10 is not supported in the client
> 2018-08-19 13:48:14.599 DEBUG 8471 --- [ntloop-thread-0] io.netty.buffer.PoolThreadCache          : Freed 10 thread-local buffer(s) from thread: vert.x-eventloop-thread-0

`@Configuration public class JdbcConfig {

    @Bean
    PgPool pgPool(PgSettings settings) {

        // Pool options
        PgPoolOptions options = new PgPoolOptions()

                .setPort(settings.getPort())
                .setHost(settings.getHost())
                .setDatabase(settings.getDatabase())
                .setUser(settings.getUser())
                .setPassword(settings.getPassword())
                .setMaxSize(settings.getPoolsize())
                .setSsl(true)
                .setTrustAll(true);

        // Create the client pool
        return PgClient.pool(options);
    }`

/var/lib/postgres/data/pg_hba.conf  

> hostssl all dbadmin 127.0.0.1/32 scram-sha-256
> hostssl all dbadmin 192.168.0.0/16 scram-sha-256
> hostssl all service_user 127.0.0.1/32 scram-sha-256
> hostssl all service_user 192.168.0.0/16 scram-sha-256

/var/lib/postgres/data/postgresql.conf  

> ssl = on
> ssl_prefer_server_ciphers = on
> ssl_cert_file = 'postgres.crt'
> ssl_key_file = 'postgres.key'
> ssl_ca_file = 'root-ca.crt'
> password_encryption = scram-sha-256
> listen_addresses= 'localhost,192.168.0.0'

Thanks!

**Comment by vietj** [comment]
@ltkn yes it should be added I think, is that something you can contribute yourself ?

**Comment by BillyYccc** [comment]
fixed in https://github.com/eclipse-vertx/vertx-sql-client/pull/412.
