### ISSUE TITLE
QueueMetrics support

### ISSUE THREAD

**Issue by hfgbarrigas** [eclipse-vertx/vertx-sql-client#174]
Although I can set _MetricsName_ through PoolOptions, I can't find anything documented about metrics. Is there a way to retrieve metrics and, what metrics are available?

**Comment by vietj** [comment]
@hfgbarrigas I think for now the only metrics we have are TCP metrics of Vert.x Metrics, we could support `PoolMetrics` which give insight about pool queuing and usage

**Comment by vietj** [comment]
I renamed the issue so it mentions explicitly `QueueMetrics`.

**Comment by vietj** [comment]
@hfgbarrigas perhaps that is something you can contribute (it is not complicated to implement) ?

**Comment by hfgbarrigas** [comment]
Having those would be great, I'll see what I can do. Regarding tcp metrics, any idea how to get them?

**Comment by vietj** [comment]
you need to use vertx-dropwizard-metrics or vertx-micrometer-metrics project, the connections should appear among the TCP connection metrics

**Comment by vietj** [comment]
e.g https://vertx.io/docs/vertx-dropwizard-metrics/java/#_net_client_metrics

**Comment by hfgbarrigas** [comment]
thanks, I'll come back when I have something for those QueueMetrics

**Comment by ngmip** [comment]
@hfgbarrigas did you try adding the QueueMetrics ?
I'd be interested in such metrics too but it does not seem that much "not complicated to implement" to me :-/

**Comment by vietj** [comment]
currently actually we do support pool metrics

**Comment by vietj** [comment]
since 4.0

**Comment by vietj** [comment]
so I think we can close this issue
