### ISSUE TITLE
POJO support

### ISSUE THREAD

**Issue by aaloise** [eclipse-vertx/vertx-sql-client#233]
It would be nice to have POJO support as an option to facilitate all kinds of querys.

**Comment by vietj** [comment]
can you try using the Collector API of the client for this ? i.e you create your own collector that creates a `List<Pojo>`

**Comment by jklingsporn** [comment]
Or give [vertx-jooq](https://github.com/jklingsporn/vertx-jooq) a try.

**Comment by indiketa** [comment]
@vietj I've just implemented a generic object mapper using Collector API:
https://github.com/indiketa/vertx-sql-client

It's simplistic and is built on top of vertx-sql-client (no changes existent API)
- Column name based mapping (Row column name -> object setter)
- Data type binding based on destination object: `obj.setAmount(float X) ` retrieved as `row.getFloat("amount")`
- Basic optimizations: The mapping is computed on the first row and reused for subsequent rows, mapping done by column number.

If you consider, I can make a PR.

**Comment by vietj** [comment]
@indiketa thanks for the feedback, for object mapping we will have something in Vert.x 4 based on the new JSON codec and vertx data objects

**Comment by Globegitter** [comment]
@vietj Now that 4.0 is out is there any plan for integrated easy pojo support? That is that main reason why we internally still decide to go with other libraries over this one (even though I personally would prefer vertx-sql)

**Comment by vietj** [comment]
@Globegitter have you look at the Vert.x SQL templates ? it provides POJO support.

https://vertx.io/docs/vertx-sql-client-templates/java/#_mapping_with_jackson_databind
https://vertx.io/docs/vertx-sql-client-templates/java/#_mapping_with_vert_x_data_objects

This issue should be closed now

**Comment by vietj** [comment]
You can also now call `toJson()` on a `Row` and from there map the `JsonObject` to a POJO with Jackson.

**Comment by Globegitter** [comment]
@vietj I have not seen that, thanks for the links.
