### ISSUE TITLE
Incorrect bytea value when postgresql bytea_output is set to 'escape'

### ISSUE THREAD

**Issue by bludwik** [eclipse-vertx/vertx-sql-client#234]
Bytea values can be encoded in escape or hex format. Driver seems to accept only HEX format.
Below is test demonstrating issue:

    @Test
    fun byteaTest(vertx: Vertx, testContext: VertxTestContext) {

        val cp = dbConnect(vertx)
        runBlocking {
            val b = cp.queryAwait("""set bytea_output to 'hex'; select E'\\001\\007'::bytea as b""").next().first().getBuffer(0).bytes
            assertTrue(b.size == 2 , "Must be 2")
            assertTrue(b[0] == 1.toByte() &&  b[1] == 7.toByte(), "Must be equal values")

            // This was OK

            val c = cp.queryAwait("""set bytea_output to 'escape'; select E'\\001\\007'::bytea as b""").next().first().getBuffer(0).bytes

            println(c.size)
            assertTrue(c.size == 2 , "Must be 2")    // ERROR - I get 3....
            assertTrue(c[0] == 1.toByte() &&  c[1] == 7.toByte(), "Must be equal values")

            testContext.completeNow()
        }
    }

I use old database and cannot change format to HEX globally.
I cannot also find way to set "bytea_output to 'hex'" for every NEW connection created by pool.
It would by great to have option in PgConnectionPool to define sql string executed automatically after creation of new connection (not for connections being reused from pool)

**Comment by vietj** [comment]
- we could support escaped format I guess if we can test it ? could you provide a reproducer failing test we could have in our tests ?
- I think for the pool we could do that too

**Comment by bludwik** [comment]
The second part of my example shows 'escape' format:
`val c = cp.queryAwait("""set bytea_output to 'escape'; select E'\\001\\007'::bytea as b""").next().first().getBuffer(0).bytes`
It changes format of select to 'escape' and tries to read it. This causes errors.

In my opinion best way is to give option to execute custom SQL on connection creation or option to handle event of connection creation (afterCreateEvent)

**Comment by bludwik** [comment]
Of course to see error you must execute:

`
val c = cp.queryAwait("""set bytea_output to 'escape'; select E'\001\007'::bytea as b""")
	.next()
	.first()
	.getBuffer(0).bytes

assertTrue(c.size == 2 , "Must be 2") // ERROR - I get 3, but should be 2 bytes....
assertTrue(c[0] == 1.toByte() && c[1] == 7.toByte(), "Must be equal values") // And here also numbers are different - should be 1 and 7
`
My tests were on Postgresql 9.5

**Comment by vietj** [comment]
thanks
