### ISSUE TITLE
unable to suppress warning when selecting an ENUM column 

### ISSUE THREAD

**Issue by chris-brace** [eclipse-vertx/vertx-sql-client#240]
with the following ddl:

```sql
CREATE TYPE USER_TYPE AS ENUM ('MANAGER', 'SPOC');

CREATE TABLE IF NOT EXISTS user (
  user_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  type            USER_TYPE NOT NULL,
);
```

im doing the following query

```java
final Tuple arguments = Tuple.of(5);

//language=PostgreSQL
final String query = "SELECT * FROM user WHERE id=$1;";

pool.preparedQuery(query, arguments, res -> {
```

It works, however i get the following printed to stderr one or more (but not every) time the query is run.

```
Jan 31, 2019 3:15:34 PM io.reactiverse.pgclient.impl.codec.DataType
WARNING: Postgres type OID=69620 not handled - using unknown type instead
```

I've been through every issue related to enums and unknown types and i've looked at all the documentation but there doesn't seem to be a way to tell `reactive-pg-client` that i actually **do** want the values to be loaded as strings. (I'll pass these strings to `MyEnumType.valueOf(str)` later.) This is my desired behavior and since im deploying this application in an environment where others will administrate it i am loathe to have errors that are not errors printing to stderr.

I would have submitted a patch to add something to the `DataType.java` file but PSQL OIDs change for every added ENUM.

**EDIT**:
I have hidden the warning by adding this to my log4j2 configuration "loggers" element. But again, for a production configuration this is really not ideal.

```xml
        <Logger name="io.reactiverse.pgclient.impl.codec.DataType" level="error">
            <AppenderRef ref="Console"/>
        </Logger>
```

**Comment by kubino** [comment]
Having the same issue with `geography` type from Postgis, it is polluting the log every single time the query contains decoding of such an "natively uknown/unsupported" field type

**Comment by vietj** [comment]
I think we should simply move this warning to debug.
