### ISSUE TITLE
Provide a method for the connection pool to define an initial handler for every new created connection

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#242]
like `PgPool#connectionInitHandler` so that users can set an handler and for instance execute some sqls for every new created connection.
Motivation from https://github.com/reactiverse/reactive-pg-client/issues/234.

**Comment by vietj** [comment]
Hi,

in this case I would rather provide a factory for connection, i.e

static PgPool pool(PgConnectOptions options, Function<PgConnectOptions, Future<PgConnection> factory) { ... }

where factory is called is called to create a connection, so user can perform this.

**Comment by pilzm** [comment]
Hi there,
We have a scenario where we need to regenerate passwords periodically (tokens with expiration time). Am I right in assuming this will be possible with this proposed change?

**Comment by vietj** [comment]
@pilzm no it will not be possible, this PR aims to perform some work after a connection has been established. I think what you are looking for is rather creating a pool from a `Supplier`, e.g `PgPool.pool(() -> new ConnectOptions().setUsername("foo").setPassword("bar"))`

**Comment by pilzm** [comment]
@vietj sounds exactly like what I need :) Should I just create a new `enhancement` issue?

**Comment by vietj** [comment]
yes please

**Comment by tsegismont** [comment]
Closed in #986
