### ISSUE TITLE
Possibility of specifying schema when connecting to postgres

### ISSUE THREAD

**Issue by limadelrey** [eclipse-vertx/vertx-sql-client#243]
Hey everyone,

I'm using reactive-pg-client along with vertx. At this moment I'm trying to specify some options in order to use PgPool, but I've noticed that is "missing" some kind of way of specifying pool's schema. The options that I'm using are:

```
final PgPoolOptions options = new PgPoolOptions()
        .setHost(config.getString("HOST"))
        .setPort(Integer.parseInt(config.getString("PORT")))
        .setDatabase(config.getString("NAME"))
        .setUser(config.getString("USER"))
        .setPassword(config.getString("PASS"))
        .setMaxSize(Integer.parseInt(config.getString("POOL_MAX_SIZE")));
```

I've also tried to create a PgPoolOptions object given a connection URI, but it doesn't solve this problem. What I was expecting is something like JDBC's way of specifying schema "jdbc:postgresql://localhost:5432/mydatabase?**currentSchema=myschema**".

Am I missing out something?

Thanks in advance.

**Comment by vietj** [comment]
Hi,

indeed it is not supported and I think we could support generic properties to send to PG when connecting.

This seems to be sent with the DB startup message that is sent.

Julien

**Comment by vietj** [comment]
the property name for current schema is `search_path`, this should be sent in the startup message as far as I can see when connecting to PG.

**Comment by vietj** [comment]
here is the list of startup message that could be sent: https://www.postgresql.org/docs/9.1/runtime-config-client.html
