### ISSUE TITLE
INET fields are always decoded as null

### ISSUE THREAD

**Issue by nikarh** [eclipse-vertx/vertx-sql-client#257]
Hi,
I am trying to execute a select query in a transaction using a prepared statement and a `createStream` method. One of the columns in a query has an `INET` type. During the select for each row I am getting the following warning in my logger:
```
WARN  i.r.p.impl.codec.DataTypeCodec - Data type INET does not support binary decoding
```
When I am calling getValue with either a column index or an alias, for my `INET` column I am always getting null as a result. As far as I can tell, `INET` type is not handled in a `decodeBinary` method, and it falls back to a default branch which returns null.

**Comment by vietj** [comment]
I think it's because we don't support yet this custom Postgres types.

so this is more like a feature request I think :-)

**Comment by vietj** [comment]
are you interested in doing such contribution to the project ?

**Comment by nikarh** [comment]
Sure, I'll attempt to do it this weekend

**Comment by vietj** [comment]
great,

you will need to sign the Eclipse Contributor Agreement, as this project is going to be part of Eclipse Vert.x in the future.

Julien

**Comment by lordvlad** [comment]
is this still open? @nikarh have you found the time to fix it?

**Comment by nikarh** [comment]
> is this still open? @nikarh have you found the time to fix it?

Unfortunately I have switched to a (synchronous) JDBC Postgres client.
Considering that Postgres itself uses a process per connection model, a number of connections you usually open to a single Postgres database is limited. In the projects with asynchronous models I simply create a threadpool with maximum size equal to maximum connection size dedicated to running database queries.
In my experience performance difference between async postgres clients and jdbc is negligible

**Comment by vietj** [comment]
async postgres can do pipelining which provides a considerable performance
improvement under some conditions

**Comment by lordvlad** [comment]
Is there any way I can monkey-patch this behaviour without much processions, we need it kinda urgently :/

**Comment by vietj** [comment]
I'm having a quick look, what seems missing for now is the wire format of encoded INET values in PG

**Comment by vietj** [comment]
@lordvlad have a look at https://github.com/eclipse-vertx/vertx-sql-client/pull/993
