### ISSUE TITLE
Tuple does not support build from List?

### ISSUE THREAD

**Issue by abcfy2** [eclipse-vertx/vertx-sql-client#266]
In the old version(0.7.0), I can build a Tuple via:

```java
Tuple buildTuple(List params) {
    Tuple.of(params.toArray());
}
```

I have to refactor the code for compatibility:

```java
Tuple buildTuple(List params) {
    new ArrayTuple(params);
}
```

But now the latest version(0.11.3) does not support this way to get right params for SQL. Tupple just support these ways:

```java
// Create a tuple of one element.
static Tuple of(Object elt1)

// Create a tuple of two elements.
static Tuple of(Object elt1, Object elt2)

// Create a tuple of three elements.
static Tuple of(Object elt1, Object elt2, Object elt3)
...

//Create a tuple of six elements.
static Tuple of(Object elt1, Object elt2, Object elt3, Object elt4, Object elt5, Object elt6)

//Create a tuple of an arbitrary number of elements.
static Tuple of(Object elt1, Object... elts)
```

And I find the old version support Array param: 

https://github.com/reactiverse/reactive-pg-client/blob/92c092235a9b6f700a3cf5e720505432a8aa2771/src/main/java/io/reactiverse/pgclient/Tuple.java#L155

Why did you remove it ?

I this it's better to support build a Tupple from Array and List(). Such as:

```java
//Create a tuple of an arbitrary number of elements.
static Tuple of(Object... elts)

// Create a tuple of  an Collection
static Tuple of(Collection elts)
```

**Comment by huntj88** [comment]
Would something like this work? Its in Kotlin, but I made you two extension functions that should do this trick

```
@Suppress("IMPLICIT_CAST_TO_ANY")
fun <T> Array<T>.toTuple(): Tuple = when {
    this.size > 1 -> {
        // using the vararg tuple
        val restOfArgs = this.sliceArray(1 until this.size)
        Tuple.of(this[0], *restOfArgs)
    }
    this.size == 1 -> Tuple.of(this[0])
    else -> ArrayTuple.EMPTY
}

inline fun <reified T> List<T>.toTuple(): Tuple = this.toTypedArray().toTuple()
```

**Comment by huntj88** [comment]
same thing in java

```java
public class TupleUtil {
    public static <T> Tuple fromArray(T[] wow) {
        Tuple output;
        if(wow.length > 1) {
            Object[] restOfArgs = (Object[]) Array.newInstance(Object.class, wow.length - 1);
            System.arraycopy(wow, 1, restOfArgs, 0, wow.length - 1);
            output = Tuple.of(wow[0], restOfArgs);
        } else if(wow.length == 1) {
            output = Tuple.of(wow[0]);
        } else {
            output = ArrayTuple.EMPTY;
        }
        return output;
    }
    
    public static <T> Tuple fromList(List<T> wow) {
        return fromArray(wow.toArray());
    }
}
```

**Comment by miere** [comment]
I totally agree with @abcfy2. I've also created a similar method to `Tuple buildTuple(List params)`, which is utterly repetitive as I have to use it in multiple places. It forced me to issue a shared library with a single method within it.

**Comment by vietj** [comment]
I think we should add back the List build.

To be honest I don't remember why we removed it, perhaps it's a mistake when importing the project.

**Comment by miere** [comment]
As an addend to that, would it be ok to also include an array wrapper?

Maybe I should give you a bit of context. One of my services is using vertx to ingest data from the rest api and relay it into a Kinesis stream. I took special care to convert the data in a way it was easy consume and make a batch insert into my postgres db. I means I've transformed it into an `Object[]` and all I had to do in the other side was to read and persist.

I've noticed though that, as `ArrayTuple` extends `ArrayList`, it will make a second copy my `Object[]` which is a waste of resource - specially when you ingest hundreds of thousands of messages per second. I've ended up by writing a custom Tuple (`ArrayWrapperTuple`) which basically wraps my object array - in which I've borrowed a few pieces from the actual ArrayTuple.

That said, would it be ok to also include an array wrapper? Do you think it's useful for your project? If you are willing to, I can provide you a PR with it.

**Comment by vietj** [comment]
@miere  yes I think it's possible to have such wrappers to avoid un-necessary object creation, can you open another issue for this and make a PR ?

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vertx-sql-client/issues/395
