### ISSUE TITLE
Kotlin source is not being published in the sources.jar

### ISSUE THREAD

**Issue by renannprado** [eclipse-vertx/vertx-sql-client#269]
Kotlin source is not being published in the `sources.jar` and hence it becomes hard to check the documentation inside of the IDE while using kotlin due to missing kotlindoc or source.

**Comment by vietj** [comment]
good point

**Comment by vietj** [comment]
I think the assembly file should be modified to have the kotlin sources.

**Comment by BillyYccc** [comment]
@renannprado Hi, would you like to try the `3.8.0-SNAPSHOT` version? I think this has been resolved after we migrate `reactive-pg-client`to `vertx-sql-client`.

**Comment by vietj** [comment]
now the kotlin source code should be in the kotlin code base https://github.com/vert-x3/vertx-lang-kotlin/blob/3.8/vertx-lang-kotlin/pom.xml#L299

**Comment by renannprado** [comment]
@BillyYccc @vietj sorry for the delay, but yes it does work. Thanks!
