### ISSUE TITLE
Expose more details from PgException

### ISSUE THREAD

**Issue by mehcode** [eclipse-vertx/vertx-sql-client#274]
:wave: Hey @vietj, I submitted a PR that got merged recently ( #272 ). It appears to now be defunct and not included in the most recent master?

Those additional error details are critical for complex query error handling.

I see that `PgException` just has 3 strings now. Can we not just expose the internal error type?

**Comment by vietj** [comment]
@mehcode we are currently migrating this repository to be under the eclipse/vertx umbrella which is the explanation of this, when the repository will be migrated we will restore the previous master (which is still in this repo)
