### ISSUE TITLE
MySQL transaction support

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#280]
reference: https://dev.mysql.com/doc/refman/8.0/en/sql-syntax-transactions.html

**Comment by daihy8759** [comment]
hi，have any progress about this？

**Comment by BillyYccc** [comment]
It's in the plan but not supported yet, I did a try in https://github.com/BillyYccc/vertx-sql-client/tree/mysql-feature/transaction some time ago and I think we may think further and revisit this later. You may manage the transaction yourself with the `SqlConnection` at the moment.

**Comment by BillyYccc** [comment]
Contributions are absolutely welcome 😃
