### ISSUE TITLE
MySQL utility commands support

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#282]
protocol reference: https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_command_phase_utility.html

**Comment by BillyYccc** [comment]
support list:
- [x] COM_QUIT
- [ ] COM_INIT_DB
- [ ] COM_STATISTICS
- [ ] COM_DEBUG
- [ ] COM_PING
- [ ] COM_CHANGE_USER
- [ ] COM_RESET_CONNECTION
- [ ] COM_SET_OPTION

**Comment by vietj** [comment]
should't the list be updated with the new PR ?

**Comment by BillyYccc** [comment]
I will start up a dedicated documentation for MySQL and update this later.
