### ISSUE TITLE
correct JDBC url cannot be parsed

### ISSUE THREAD

**Issue by meredrica** [eclipse-vertx/vertx-sql-client#288]
Hello!

The [official doc](https://jdbc.postgresql.org/documentation/head/connect.html) for the postgresql jdbc driver states that connection uris must start with ``jdbc:postgres://``.

The [regex](
https://github.com/eclipse-vertx/vertx-sql-client/blob/ade44ecb11c8764c91e72d99ac74e52f3d8eaa93/src/main/java/io/vertx/pgclient/impl/PgConnectionUriParser.java#L37) that's in use doesn't match it however

**Comment by BillyYccc** [comment]
We don't use the syntax of JDBC connection url for the Postgres client

We implement this feature with the PostgreSQL official connection URI form 
`postgresql://[user[:password]@][netloc][:port][,...][/dbname][?param1=value1&...]`
 see https://www.postgresql.org/docs/11/libpq-connect.html#LIBPQ-CONNSTRING for more information.

**Comment by meredrica** [comment]
ok. that should go into the documentation ;)

**Comment by BillyYccc** [comment]
Actually it has been clearly stated in the documentation :-)

> More information about connection string formats can be found in the PostgreSQL Manuals.
