### ISSUE TITLE
Unable to use preparedQuery inside transactions

### ISSUE THREAD

**Issue by KyrumX** [eclipse-vertx/vertx-sql-client#312]
So I am running into the issue that I cannot seem to use preparedQuery inside an transaction, just as with #237 I am getting the exception of 'io.vertx.core.VertxException: Transaction already completed'.

The same issue seems to be referenced here:
> @vietj @foxgem I run into this problem too on 0.11.3
> Has there been a fix? Else, how should I run preparedQuery in a transaction?

_Originally posted by @quandragoon in https://github.com/eclipse-vertx/vertx-sql-client/issues/237#issuecomment-485937449_

I am running 0.11.3.

This one will not fail:

 ```
    dbClient.begin(res -> {

      if (res.succeeded()) {

        PgTransaction tx = res.result();


        tx.query("INSERT INTO test (id, email, password) VALUES ('60a2bf4d-ea0a-4355-9777-49e9e642c69a', 'random@gmail.com', 'random')", ar -> {});


        tx.commit(res2 -> {
          if (res2.succeeded()) {
            System.out.println("Transaction succeeded");
            context.response().setStatusCode(200).end();
          } else {
            System.out.println("Transaction failed " + res2.cause().getMessage());
            context.response().setStatusCode(500).end();
          }
        });

      } else {
        //
      }
    });
```

And this one will fail:

```
   dbClient.begin(res -> {

      if (res.succeeded()) {

        PgTransaction tx = res.result();

        tx.preparedQuery("INSERT INTO test (id, email, password) VALUES ($1, $2, $3)", Tuple.of(UUID.fromString("60a2bf4d-ea0a-4355-9777-49e9e642c69a"), "somemail@gmail.com", "random"), ar -> {
          System.out.println(ar.cause().toString());
        });

        tx.commit(res2 -> {
          if (res2.succeeded()) {
            System.out.println("Transaction succeeded");
            context.response().setStatusCode(200).end();
          } else {
            System.out.println("Transaction failed " + res2.cause().getMessage());
            context.response().setStatusCode(500).end();
          }
        });

      } else {
        //
      }
    });
```

It will still end up in the res.2 succeeded part, but the preparedStatement cause will state `io.vertx.core.VertxException: Transaction already completed` and thus nothing is actually commited.

I've tried using connections, directly on the pool, etc. It keeps failing.

**Comment by vietj** [comment]
I was able to reproduce it thanks

**Comment by vietj** [comment]
I will investigate

**Comment by vietj** [comment]
it seems normal to me, basically you should call tx.commit inside the prepared query result, when you commit just after, the first statement will send the commit statement before the prepared query is actually executed

**Comment by vietj** [comment]
I.e you should do:

```
      tx.preparedQuery("INSERT INTO Fortune (id, message) VALUES ($1, $2);", Tuple.of(14, "test message"), ar -> {
        System.out.println("got result " + ar.cause().getMessage());
        tx.commit(res -> {
          System.out.println("TX  " + res.succeeded());
        });
      });
```

**Comment by vietj** [comment]
I don't think it is the reactive sql client the culprit

**Comment by vietj** [comment]
I agree that the examples show a wrong usage

**Comment by vietj** [comment]
I will think about what is correct and not :-)

**Comment by vietj** [comment]
it seems it shold be correct to delay the transaction commit until all commands in progress have been executed, I will try to provide a patch for this

**Comment by vietj** [comment]
as work around you can commit the transaction when you get the prepared query result

**Comment by KyrumX** [comment]
Hi @vietj , thanks for looking into it! I'll use your work around for now!

**Comment by vietj** [comment]
I think actually the work around is the normal way to go and without it, it leads to more confusing code, I will instead change the documentation to show the correct way.

Perhaps later in the future we can revisit this.

**Comment by vietj** [comment]
set wontfix for now
