### ISSUE TITLE
preparedQuery method will exhaust MySQL statements

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#314]
A simple reproducer is 
```
  @Test
  public void testPreparedQuery(TestContext ctx) {
    MySQLConnection.connect(vertx, options, ctx.asyncAssertSuccess(conn -> {
      for (int i = 0; i < 20000; i++) {
        conn.preparedQuery("SELECT 'hello'", ctx.asyncAssertSuccess(res ->{
          ctx.assertEquals("hello", res.iterator().next().getValue(0));
        }));
      }
    }));
  }
```

error is 
`io.vertx.mysqlclient.MySQLException: Can't create more than max_prepared_stmt_count statements (current value: 16382)`

because executing `SqlConnection#preparedQuery`creates a prepared statement but does not close it after executing.

**Comment by BillyYccc** [comment]
A quick fix for this would mark a executingCommand with a closeAfterExectuing flag so that we can close the one-shot preparedQuery after executing, but we would not benefit much from the one-shot prepared query because we will have to execute like prepare->execute->close and that increases the round-trips.

Another way to fix can be move the `Prepared queries caching` feature to sqlclient, we can close the preparedStatement when it's evicted from the cache, in this way we may need more features for the cache as the cache in pgclient is actually a hashmap, we can also provide configurations for this.
In addition we can make the cache pluggable but that may be another issue we should think about.

**Comment by vietj** [comment]
is it possible to determine the max number of prepared queries in MYSQL ?

**Comment by BillyYccc** [comment]
yes, we can execute a query like `SET GLOBAL max_prepared_stmt_count = 50000;`, but I don't think this will always work in any use cases.

**Comment by vietj** [comment]
I mean retrieve the value, overall I think we should have a max size value that is ocnfigurable and when the max size is reached then close old statements

**Comment by vietj** [comment]
and we make this possible on `MySQLConnection` with a get/set of max statement cache

**Comment by vietj** [comment]
and we provide an initial value in options.

**Comment by BillyYccc** [comment]
I wonder whether we can also provide options for SQL placeholder interpolation like JDBC does by default, in this way users can eliminate this kind of error totally.

**Comment by BillyYccc** [comment]
Closing as the best practice for now is added in https://github.com/eclipse-vertx/vertx-sql-client/pull/540.
