### ISSUE TITLE
JSON types should not use code generation

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vertx-sql-client#320]
Currently the API uses an `@VertxGen` JSON type for PostgreSQL and this type cannot be unwrapped by the RX version with the `Tuple.of(...)` version because this one will not convert it.

**Comment by vietj** [comment]
for the sake of simplicity I am leaning toward removing the custom JSON type in `pgclient` and instead use `JsonObject` / `JsonArray` / `Number` / `Boolean` / `String` types.

The main issue is the ambiguous `null` value that can either mean null row or the null JSON value. This could be solved by always using the null JSON value.

**Comment by vietj** [comment]
@BillyYccc @ EmadAlblueshi any opinion on this ?

**Comment by BillyYccc** [comment]
`null` value is also ambiguous in `RowImpl`, a SQL `NULL` value or a mismatched typed value(which is called with accessor methods) both returns a null, maybe we should add some metadata to `Row` to make this more clear?

**Comment by vietj** [comment]
you mean something like an `isNull(String)` / `isNull(int)` with a null sentinel object ?

**Comment by BillyYccc** [comment]
yes, it tells the user whether it's SQL null value and returns a `boolean`, but the implementation details might vary.

**Comment by vietj** [comment]
ok, I think that's doable easily

**Comment by vietj** [comment]
I think one easy way to do, is to use `JsonNode` type in PG `RowImpl` and then unwrap this in `get(int)`.

The `isNull` can be implemented by simply checking `super.get(int) == null`.

**Comment by vietj** [comment]
at the end of the day after trying some variations around the idea, the simplest is to setup a `JSON_NULL` value constant that represents JSON null value

**Comment by vietj** [comment]
I will provide a PR for that.
