### ISSUE TITLE
MySQL preparedBatch support

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#334]
Since MySQL has no native protocol support for batching, we can simulate the process, in that way we send several COM_STMT_EXECUTE with the batching params from a prepared statement, then concat the `SqlResult` and return it to the user.

**Comment by BillyYccc** [comment]
I wonder whether we should support the `rewriteBatchedStatements` which is a property of MySQL JDBC driver, it will rewrite the prepared query to send one multi-query packet to save the round trips between the client and the server since MySQL does support pipelining. But one of the disadvantages is it's a bit opinionated with some magic.

**Comment by vietj** [comment]
@BillyYccc just go for now with the simplest way to do
