### ISSUE TITLE
PostgreSQL's hstore type implementation

### ISSUE THREAD

**Issue by renannprado** [eclipse-vertx/vertx-sql-client#340]
I was trying to hack around the lib to see if I could implement the [hstore](https://www.postgresql.org/docs/9.1/hstore.html) type, however it seems to be a little tricky as the `oid` of types created via extension is not the same across postgresql installations according to what I read here https://github.com/jackc/pgx/issues/227#issuecomment-272319971.

Based on that, I wonder if there's already a strategy that has been thought through by the contributors or is this something that has to be developed from the scratch? Is the refactor needed to support such types too big?

**Comment by vietj** [comment]
how does `pgx` get the field description name ?

**Comment by vietj** [comment]
have you looked at how it is done for other clients like JDBC ?

**Comment by renannprado** [comment]
@vietj just by looking at the code, it looks like they have at least two ways of mapping the types: one via `oid` and another via type `name`.

If you look [here](https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java#L138), you'll see that they add the `hstore` type name to a map called `pgNameToJavaClass`. So I suppose we would have do something similar.

**Comment by vietj** [comment]
I don't understand how the lookup is done given that only the IOD is passed in the protocol. How does it work when the driver needs to transform bytes to this format ? how is the lookup done ?

**Comment by renannprado** [comment]
It looks like they lookup on demand when it doesn't match with the ones already set by the lib.

It is querying the database to map the `oid` to the type name, apparently: https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java#L361

**Comment by vietj** [comment]
ok, this makes sense. I think we could have something like this where the user explicitly asks for it ?

**Comment by vietj** [comment]
I will create an issue for this feature

**Comment by vietj** [comment]
https://github.com/eclipse-vertx/vertx-sql-client/issues/343

**Comment by vietj** [comment]
I will close this issue in the mean time as it is specific to hstore
