### ISSUE TITLE
only support Mysql great 5.7？ 

### ISSUE THREAD

**Issue by daihy8759** [eclipse-vertx/vertx-sql-client#354]
Hi，I found mysql client only support > 5.7, but can't  found  any describe about this.

**Comment by BillyYccc** [comment]
I haven't checked for those, we should add matrix tests for MySQL like the Postgres client does. The protocol differs between different mysql versions so we may need extra effort to make all work. I wonder if we will want to support the versions below 5.6 because actually MySQL 5.5 has ended support in 2018, so maybe we can add MySQL 5.6 and 8.0(in Vert.x 4.0) support.

**Comment by daihy8759** [comment]
I agree with you, MySQL 5.6 not yet supported，I've done a test.

**Comment by daihy8759** [comment]
I think problem is this code  in `CommandCodec`
```
  OkPacket decodeOkPacketPayload(ByteBuf payload, Charset charset) {
    payload.skipBytes(1); // skip OK packet header
    long affectedRows = BufferUtils.readLengthEncodedInteger(payload);
    long lastInsertId = BufferUtils.readLengthEncodedInteger(payload);
    int serverStatusFlags = 0;
    int numberOfWarnings = 0;
    if ((encoder.clientCapabilitiesFlag & CapabilitiesFlag.CLIENT_PROTOCOL_41) != 0) {
      serverStatusFlags = payload.readUnsignedShortLE();
      numberOfWarnings = payload.readUnsignedShortLE();
    } else if ((encoder.clientCapabilitiesFlag & CapabilitiesFlag.CLIENT_TRANSACTIONS) != 0) {
      serverStatusFlags = payload.readUnsignedShortLE();
    }
```
https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_basic_ok_packet.html
it says 
As of MySQL 5.7.5, OK packes are also used to indicate EOF, and EOF packets are deprecated.
if CLIENT_PROTOCOL_41 is set, the packet contains a warning count.

**Comment by BillyYccc** [comment]
@daihy8759 Thanks for the hint, would you like to check the latest `3.8` branch for the compatibility with MySQL 5.6?

**Comment by daihy8759** [comment]
I create mysql5.6 in docker test passed,but test failed on my server version.

docker mysql version info:
===

`mysql  Ver 14.14 Distrib 5.6.44, for Linux (x86_64) using  EditLine wrapper`

server mysql version info:
===

`mysql  Ver 14.14 Distrib 5.6.37, for Linux (x86_64) using  EditLine wrapper`

**Comment by daihy8759** [comment]
It seems mysql version parse fail
```java
String[] versionNumbers = serverVersion.split("\\.");
int majorVersion = Integer.parseInt(versionNumbers[0]);
int minorVersion = Integer.parseInt(versionNumbers[1]);
int releaseNumber = Integer.parseInt(versionNumbers[2]); // we don't support dev version
if (majorVersion == 5 && (minorVersion < 7 || (minorVersion == 7 && releaseNumber < 5))) {
    // EOF_HEADER is enabled
} else {
    encoder.clientCapabilitiesFlag |= CLIENT_DEPRECATE_EOF;
}
```
I found mysql full version is 
![image](https://user-images.githubusercontent.com/6057326/61192804-bd001200-a6e9-11e9-8ea5-dfa798ac3e12.png)

**Comment by BillyYccc** [comment]
Can you show the error info or stacktraces? The embedded MySQL version is 5.6.36.

**Comment by daihy8759** [comment]
if your version string ends with -log this means that logging is enabled. releaseNumber may has letters

**Comment by BillyYccc** [comment]
I don't know much about the naming convensions for MySQL, it should be improved on the parsing. Thanks again:-)
