### ISSUE TITLE
Can't find classes under the `reactivex` package in 4.0.0-milestone1

### ISSUE THREAD

**Issue by aesteve** [eclipse-vertx/vertx-sql-client#382]
Hello,

I have a fine-working application with:

- 3.8.0
- vertx-pg-client
- rxjava2

Here's an extract of `build.gradle.kts`:

```kotlin
val vertxVersion = "3.8.0" // "4.0.0-milestone1"
// val vertxVersion = "4.0.0-milestone1"
dependencies {
    fun vertx(vararg artifacts: String) =
        artifacts.forEach {
            implementation("io.vertx:$it:$vertxVersion") {
                exclude(group = "org.slf4j")
            }
        }
    // ...
    vertx("vertx-web", "vertx-lang-kotlin", "vertx-rx-java2", "vertx-pg-client")
    implementation("io.github.jklingsporn:vertx-jooq-rx-reactive:$vertxJooqVersion") {
        exclude(group = "io.reactiverse")
    }
   // ...
}
```
I tried to upgrade my app to 4.0.0-milestone1, without touching anything, and found missing classes like `import io.vertx.reactivex.pgclient.PgPool`.

Basically, every class under the `reactivex` package for the modules `vertx-pg-client`, `vertx-sql-client` appear to be missing.

Is there some dependency I should add to get these classes working ? 

I tried to get a look at [the deprecation log](https://github.com/vert-x3/wiki/wiki/4.0.0-Deprecations-and-breaking-changes) but can't see any mention of `reactivex` changes, so I'm guessing this may be a codegen bug or something, hence this issue.

Hoping I can give 4.0.0 a try soon!

Thank you.

**Comment by vietj** [comment]
right I think we haven't integrated SQL client in vertx-rx and such we should fix it

**Comment by vietj** [comment]
see https://github.com/vert-x3/vertx-rx/commit/58ad322cecf60907b413659edb2e7b9bfcee96e8

**Comment by vietj** [comment]
resolved with wontfix as this will be done in vertx-rx instead

**Comment by vietj** [comment]
the issue can't be moved
