### ISSUE TITLE
Names in Row are lowercase

### ISSUE THREAD

**Issue by ylemoigne** [eclipse-vertx/vertx-sql-client#388]
Using postgres client, if a query use mixed case alias, the row won't find the field if not requested in lowercase.

If query `SELECT foo AS mixedCaseName FROM mytable` then `row.getString("mixedCaseName")` will return `null` ( `row.getString("mixedcasename")` will return the value)

If this behavior is intended, I think it should be documented as it differ from JDBC API and can be surprising.

**Comment by vietj** [comment]
this is the expected behavior, the SQL client would not modify what you send to the database, this is not specific to PG so perhaps indeed we should add a generic section in the documentation about this
