### ISSUE TITLE
Introduce generatedKey() on SqlResult

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#389]
For PostgreSQL we can use `RETURNING` clause for fetching the generated keys, but in MySQL we can get the generated key via the `last_insert_id` in the OK_Packet OTTB, so we may add an interface for this in the `sqlclient` module for better usage.

**Comment by pmlopes** [comment]
I'd rather have a `lastInsertedId()` that would only work for MySQL. Postgres can emulate that feature with the returning keywork but it will open a can of worms as you will need to parse the query to define the right place to add the returning statement. For trivial queries it's just appending but for complex ones like cte's you really need to parse and insert in the right place.

My opinion is not to write emulation features for other RDBMS.

**Comment by BillyYccc** [comment]
I agree we should avoid magic like injecting `RETURNING` clause into the SQL statement.

Since we use the same interface to represent the result as `SqlResult`, what I mean is adding a `lastInsertId()` method to the `SqlResult` interface.
* For MySQL we can return the id with the value from OK_Packet natively.
* For PostgreSQL we throw an `UnsupportedOperation` and give a hint to the users that they should write `RETURNING` SQL by themselves.

**Comment by vietj** [comment]
I am worried that each database will have its peculiarities

Perhaps we can add notion of properties on `SqlResult` , to do something like `result.property("lastInsertId")` ?

we could also do the same using generics magic to avoid casting and expose constants with something like:

```
@VertxGen
interface SqlResultProperty<T> {
}

```
@VertxGen
interface SqlResult {
  ...
  <T> T property(SqlResultProperty<T> property);
  ...
}

@VertxGen
interface MySQLClient extends SqlClient {
  // Constant
   SqlResultProperty<Integer> LAST_INSERTED_ID = new SqlResultPropertyImpl<>();
}
```



```

**Comment by BillyYccc** [comment]
@vietj It's quite a good idea! I have made a prototype for this in https://github.com/eclipse-vertx/vertx-sql-client/pull/392, can you take a look?

**Comment by BillyYccc** [comment]
Closing this fixed in #392
