### ISSUE TITLE
Broken website

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#399]
![image](https://user-images.githubusercontent.com/5463589/63509605-248e5600-c50f-11e9-8629-65ebb89014d9.png)

**Comment by vietj** [comment]
what is broken ?

**Comment by BillyYccc** [comment]
see my screenshot, including of common sections documentation does not work, you can check that in the website

**Comment by vietj** [comment]
ok, too bad we just did a release :-)

**Comment by vietj** [comment]
I'll have a look soon

**Comment by vietj** [comment]
we should do it differently I think in a way we don't patch all languages specifically for  this

**Comment by vietj** [comment]
for documentation you should look at https://github.com/vert-x3/vertx-stack/tree/master/stack-docs

**Comment by vietj** [comment]
I think we should copy the files in this project to each implementation

**Comment by BillyYccc** [comment]
I have a created a PR for `3.9` branch in https://github.com/vert-x3/vertx-stack/pull/103, I will open another PR for `master` branch when I finish integrating sql client to groovy module(it's currently missing).

**Comment by BillyYccc** [comment]
Here are they: 
https://github.com/vert-x3/vertx-lang-groovy/pull/95
https://github.com/vert-x3/vertx-stack/pull/104

**Comment by vietj** [comment]
I fixed it by correcting the files that are unpacked - see https://github.com/eclipse-vertx/vertx-sql-client/issues/571
