### ISSUE TITLE
Incorrect implementation of tuple factory method 

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#400]
https://github.com/eclipse-vertx/vertx-sql-client/blob/e8ef0be918add8a80784f75835a43f8ccbd174f5/vertx-sql-client/src/main/java/io/vertx/sqlclient/Tuple.java#L197-L206

**Comment by BillyYccc** [comment]
Tuple built from List method does not work

**Comment by shenzhou-6** [comment]
why six elements.... if elements size more than six?

**Comment by BillyYccc** [comment]
The intention of this method is to copy all elements in the List to a new
Tuple. Both the documentation and code need to be updated.

shenzhou-6 <notifications@github.com> 于 2019年8月24日周六 02:00写道：

**Comment by vietj** [comment]
ouch

**Comment by vietj** [comment]
yes this is a bug, in the mean time people can use the new Tuple.wrap(list) method
