### ISSUE TITLE
can't connect to MySQL 5.8

### ISSUE THREAD

**Issue by pmlopes** [eclipse-vertx/vertx-sql-client#401]
Just attempted to connect to MySQL 5.8 and can't get a connection. Server is ok and latest jdbc driver can connect without any issue.

Socket seems to open but connection handshake doesn't complete.

Use the connection example from the docs on 5.8 to verify.

**Comment by BillyYccc** [comment]
I think it may be related to not supporting the authentication method `caching_sha2_password` which is the default authentication method of MySQL 8, see https://github.com/eclipse-vertx/vertx-sql-client/issues/300.

**Comment by pmlopes** [comment]
Ok good to know. The server I want to connect to isn't on my domain so j can't change it's configuration. I'll watch the issue and retry when there are updates 👍

**Comment by BillyYccc** [comment]
@pmlopes MySQL 8 support is ongoing in https://github.com/eclipse-vertx/vertx-sql-client/pull/420 😃

**Comment by BillyYccc** [comment]
fixed in https://github.com/eclipse-vertx/vertx-sql-client/pull/420.
