### ISSUE TITLE
Some vertx-sql-client's unit tests failed to run or debug in VS Code

### ISSUE THREAD

**Issue by Heromyth** [eclipse-vertx/vertx-sql-client#404]
I submitted an issue, see https://github.com/microsoft/vscode-java-debug/issues/643.

The real reason is :
 The targetDir is not detected during the debug procession in VS Code. 
There is an Exception thrown in https://github.com/eclipse-vertx/vertx-sql-client/blob/3.8/vertx-pg-client/src/test/java/io/vertx/pgclient/junit/PgRule.java#83

**Comment by Heromyth** [comment]
Here is a simple fix: 
     String path = System.getProperty("user.dir");
     String a = System.getProperty("target.dir", path + "\\vertx-pg-client\\target");

**Comment by tsegismont** [comment]
We no longer use this rule (except for unixdomain socket testing on some platforms)
