### ISSUE TITLE
columnNames getter in Row.class

### ISSUE THREAD

**Issue by luckyshroom** [eclipse-vertx/vertx-sql-client#405]
Does it possible to get access to colunm names from row class (MySQLRowImpl) as List after query perfomed?
If it is can we have public method for it? Thnks
Or looking further it will be perfect to have ability to transform result (row) to JsonObject by specific method...
PS: Does MySQLClient have support for 8.0 version?

**Comment by BillyYccc** [comment]
> Does it possible to get access to colunm names from row class (MySQLRowImpl) as List after query perfomed?
> If it is can we have public method for it? Thnks

You can call `SqlResult#columnsNames` to get the column names.

> Or looking further it will be perfect to have ability to transform result (row) to JsonObject by specific method...

POJO mapping is planned in the Vert.x 4.x release. For now you can use the [Collector API](https://vertx.io/docs/vertx-mysql-client/java/#_collector_queries).

> PS: Does MySQLClient have support for 8.0 version?

Not yet, but we're working on it.
