### ISSUE TITLE
Missing Javadoc for vertx-sql-client

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#407]
Check https://vertx.io/docs/apidocs/ but find no Javadoc for original `vertx-sql-client` APIs but only Rxi-fied APIs.

**Comment by vietj** [comment]
that is weird

**Comment by vietj** [comment]
we need to check the vertx-stack project with the stack-docs module

**Comment by vietj** [comment]
it is because the -sources.jar are empty

**Comment by vietj** [comment]
well they are not empty but they are not unpacked

**Comment by vietj** [comment]
fixed in stack-docs project
