### ISSUE TITLE
Pool improvements

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vertx-sql-client#41]
- connection timeout
- idle timeout

**Comment by pratikpparikh** [comment]
@vietj can this be made part of 0.9.1 as this is very important to make sure that connection timeout is handled properly.

**Comment by Globegitter** [comment]
@vietj what is the status on this? I can see one can already set a `idleTimeout` through `PgConnectOptions`, is that then also respected by the pool? But as far as I can see a connection timeout itself is still missing. Can you also confirm that?

And I agree with @pratikpparikh having a connection timeout would be important to have.

**Comment by vietj** [comment]
we will have this when we reuse the current pool implement from vertx

**Comment by vietj** [comment]
I'm scheduling this for 4.0

**Comment by Globegitter** [comment]
@vietj that is great new, but if now I set:

```
PgPool.pool(
        pgConnectOptionsOf(
            host = "localhost",
            port = 5432,
            database = "postgres",
            user = "postgres",
            password = "postgres",
            connectTimeout = 1000,
            idleTimeout = 1000,
            idleTimeoutUnit = TimeUnit.MILLISECONDS
        ),
        poolOptionsOf()
    )
```

then is `connectTimeout` and `idleTimeout` ignored by the pool?

**Comment by vietj** [comment]
those are connection settings, not pool settings. Those should have effect though, i.e the connection should be closed after 1s of TCP inactivity whehter it's int he pool or not.

**Comment by vietj** [comment]
and for connect timeout there are chances it works correctly although one should check

**Comment by Globegitter** [comment]
Cool thanks for the quick responses, will give it a try and report back here.
