### ISSUE TITLE
JSON DataType for MySQL client

### ISSUE THREAD

**Issue by luckyshroom** [eclipse-vertx/vertx-sql-client#428]
Client throws NPE when trying to get data with column type JSON.

And also does it possible to return Instant value for DATETIME datatype?

**Comment by BillyYccc** [comment]
`JSON` data type is not supported for now in MySQL.

`DATETIME` is mapped to `java.time.LocalDateTime` and you can use `LocalDateTime#toInstant` to get it transformed.

**Comment by vietj** [comment]
closed per @BillyYccc
