### ISSUE TITLE
Char type is mapped to Buffer

### ISSUE THREAD

**Issue by onthegit** [eclipse-vertx/vertx-sql-client#429]
Hello authors,

Mysql reactive client, 4.0.0-milestone3

5.5.62-MariaDB - char column is resolved to Buffer instead of String as stated in documentation.

**Comment by BillyYccc** [comment]
Thanks for reporting, I will investigate it.

**Comment by BillyYccc** [comment]
I'm setting up a MariaDB 5.5 using https://hub.docker.com/r/cytopia/mariadb-5.5/ and this works well. If you can provide a reproducer I think it would be much easier to find out why that does not work for you.

**Comment by BillyYccc** [comment]
I think we have something changed and would you like to have another try using the latest snapshot version?
