### ISSUE TITLE
Version 3.8.2 causing timeouts

### ISSUE THREAD

**Issue by graemerocher** [eclipse-vertx/vertx-sql-client#433]
We have 2 PRs open (one for MySQL and one for Postgres) from dependabot that upgrade from 3.8.1 to 3.8.2 for Micronaut's integration with Vert.x SQL client.

Both are failing with the build timing out. The only change is point release upgrade:

https://github.com/micronaut-projects/micronaut-sql/pull/63
https://github.com/micronaut-projects/micronaut-sql/pull/61

Has something broken in this latest release?

**Comment by tsegismont** [comment]
https://github.com/vert-x3/wiki/wiki/3.8.2-Deprecations-and-breaking-changes

Nothing about SQL Client. Anything relevant in the build logs?

**Comment by graemerocher** [comment]
I have yet to debug the issue myself, thought I would report early to see if you were aware of anything. Currently the build logs just say that the build hangs and doesn't receive any more output for 10 minutes:

https://travis-ci.org/micronaut-projects/micronaut-sql/jobs/594963866#L759

I will do some more digging at some point and report back.

**Comment by BillyYccc** [comment]
I think it might be related to the changes in https://github.com/eclipse-vertx/vertx-sql-client/commit/ee9e9b028459c6399466d55cabaf2e94addb3a46, this actually brings API changes and I'm not sure if tests needs to be changes to adapt to this in Micronaut. HTH

**Comment by graemerocher** [comment]
Hmm if that is the case surely not a great idea introducing breaking API changes in a patch release?

**Comment by tsegismont** [comment]
This module is still in "Technical Preview", so such breaking changes might
happen.

**Comment by BillyYccc** [comment]
We could add this API change to the breaking changes list. Can you please edit that? @vietj

**Comment by graemerocher** [comment]
Ok, anyway will get back once I have dug into it some more.

**Comment by vietj** [comment]
@BillyYccc why would that change make the build hang ?

**Comment by BillyYccc** [comment]
I have investigated that's irrelavant, the cause is the dependencybot only upgrades the SQL client version without upgrading the stack.

**Comment by graemerocher** [comment]
Ah gotcha. Good point. Thanks for doing that. Closing...

**Comment by BillyYccc** [comment]
@vietj But I think we should still note the change in the breaking list, see my upgrading for the MSSQL client in https://github.com/BillyYccc/incubator-vertx-mssql-client/pull/23/commits/05f1a88f8de721e2e9e8edd3b58b686b3cc4afa7, it requires changes in the API anyhow.

**Comment by vietj** [comment]
thanks for investigating @BillyYccc

**Comment by vietj** [comment]
indeed it should be listed

**Comment by vietj** [comment]
I edited here : https://github.com/vert-x3/wiki/wiki/3.8.2-Deprecations-and-breaking-changes#vertx-sql-client
