### ISSUE TITLE
sql-client: CLIENT_FOUND_ROWS client flag is not set, wheras the flag ist set for JDBC as default

### ISSUE THREAD

**Issue by AndreasKl** [eclipse-vertx/vertx-sql-client#434]
Today I spent about an hour debug an issues, where an "update" statement despite being successful returned zero rows. I'm a postgres guy so my experience with MySQL is limited.

After looking into how this works in JDBC I found out that `https://dev.mysql.com/doc/refman/5.7/en/mysql-affected-rows.html` returns zero, if the update statement was successful but did not update the tuple.

The JDBC driver sets [`CLIENT_FOUND_ROWS`](https://github.com/mysql/mysql-connector-j/blob/36534fa273b4d7824a8668ca685465cf8eaeadd9/src/main/protocol-impl/java/com/mysql/cj/protocol/a/NativeAuthenticationProvider.java#L176) to `true` per default, which differs from the `vertx-mysql-client`:

```
useAffectedRows

Don't set the CLIENT_FOUND_ROWS flag when connecting to the server (not JDBC-compliant, will 
break most applications that rely on "found" rows vs. "affected rows" for DML statements), but does cause 
"correct" update counts from "INSERT ... ON DUPLICATE KEY UPDATE" statements to be returned by 
the server.

Default: false
```

I think that this flag should be the default to yield the same results as the `vertx-postgres-client`.

**Comment by BillyYccc** [comment]
Thanks for sharing your experience. `CLIENT_FOUND_ROWS` is one of the capability flags which can be set at the connection start, I think we could provide abilities for setting a part of those useful options of capability flags in a later version.

**Comment by AndreasKl** [comment]
Do you mind if I try to build a PR? I'm thinking of a set of new settings in `MySQLConnectOptions` so that a user has not to fiddle with flags.

**Comment by AndreasKl** [comment]
Ok, I think I figured out how this works:

https://github.com/eclipse-vertx/vertx-sql-client/compare/master...AndreasKl:gh434-user-can-configure-affected-rows

Should setting the CLIENT_FOUND_ROWS flag become the default? I would expect that, on the other hand it would break existing projects.

**Comment by vietj** [comment]
thanks for the contribution
