### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by Globegitter** [eclipse-vertx/vertx-sql-client#439]
I am doing batch inserts and they have been working fine in my application for quite some time but now they occasionally started failing with a `[...] cannot be coerced to [...]`. Where-as the list contain all values. I have inserts with 1000s (12132 to be precise) of values for that this error is turning out to be quite impossible to digest. Would it be possible to just log the values that can not be coerced instead? Or maybe provide a more specific error that has some metadata so one can debug the issue further?

I think that could really help in some cases.

**Comment by BillyYccc** [comment]
It could be improved I think, at least we can pick the subset of parameters which fails the client side validation instead of pushing all the parameters in the error message and make it friendlier. Do you have some advice for the metadata (such as the index of the parameters) to show in the error ?

**Comment by Globegitter** [comment]
One thing I have also noticed is that the error is being thrown in two separate cases. One when `values.size() != paramDataTypes.length` and one when there is actually a type error. So it would also be nice to have more specific errors or at least messages for the two cases. Turns out I am actually hitting this case and I am not entirely sure what it means - if values.size is larger does it mean I am providing to many query values compared to what the query actually expects?

But I agree if we just had the parameters that fail in the message that would already be enough. Otherwise the corresponding column names could also be useful.

**Comment by Globegitter** [comment]
Ok looking further into this, I do not quite understand what is going on. Now I have a query of following nature: `values.size() == 96084`,  `paramDataTypes.length == 30548` and I have checked, I am sending `96084` values along with the `preparedQueryAwait` and looking at the query itself it does seem to expect 96804 values with the latest being `$96084`.

But in any case, I will investigate further.

**Comment by Globegitter** [comment]
Very strange, I tried to investigate where `paramDataTypes` is coming from but could not figure it out (I am not so long in the java/kotlin world yet), but the main thing that is quite strange, if I let my application run over the same data set but keep the insert batches smaller it all works fine so that seems to me to suggest that preparedQuery is having issues with inserts that have more than a certain amount of values. The largest insert I have managed so far is 7069 rows  with 42414 values.

**Comment by BillyYccc** [comment]
The general idea of client side prepared statement validation is to check the number of placeholders in your prepared query sql is the equal to the number of parameters you're about to execute for an prepared statement and the param types are matched with the types defined in the server according the metadata returned in a prepared statement.

**Comment by Globegitter** [comment]
Ah, interesting, so there seems to be a limitation on the postgresql side where a prepared statement can not have more than 65535 parameters: https://stackoverflow.com/questions/6581573/what-are-the-max-number-of-allowable-parameters-per-database-provider-type

Might also be another useful improvement for the error message.

**Comment by Globegitter** [comment]
Maybe it is also worth looking at other error messages. I am just running into the following:

```
Exception in thread "main" io.vertx.pgclient.PgException: number of columns does not match number of values
```

and the stacktrace does not show any of my application code, so it would be useful to show more information to be able to know which query this relates to. The easiest added information would be the query itself, but maybe it could also just be part of the query. Like list the provided columns as well as the number of values provided or similar.

**Comment by BillyYccc** [comment]
fixed in https://github.com/eclipse-vertx/vertx-sql-client/pull/458.
