### ISSUE TITLE
Has plan to support the Mysql JSON type?

### ISSUE THREAD

**Issue by gaollg** [eclipse-vertx/vertx-sql-client#441]
> JSON data type is not supported for now in MySQL

from https://github.com/eclipse-vertx/vertx-sql-client/issues/428#issuecomment-535741331

Has plan to support the Mysql JSON type? Now the database contains a JSON type that returns 0 rows directly.

**Comment by BillyYccc** [comment]
I think it can be supported with reusing the postgres client codec logic quickly, I will have a try today.
