### ISSUE TITLE
utf8 string appears as question mark (?)

### ISSUE THREAD

**Issue by badrazizi** [eclipse-vertx/vertx-sql-client#444]
I am using version 3.8.2 and having some issues with utf8 string appears as question mark (?) in the database when inserting new record, but it's display old record correctly (inserted using phpmyadmin).

this how it's appeared.

Summery | Title | Time | ID | Image | Story | Link
-- | -- | -- | -- | -- | -- | --
??? ?????? ???? ???? ?? ????? ?????? ?????? ????... | ??? ??? ????: La Noria | 2019-11-02T05:03:08.884396 | 718 | /2019/10/La-Noria-310x165.jpg | ???? ????? ????? ?? ????? ??... | /?p=718

here how i init MySQLPool
```kotlin
fun init(vertx: Vertx): MySQLPool {
    val connectOptions = MySQLConnectOptions()
      .setPort(Config.mysqlPort)
      .setHost(Config.mysqlHost)
      .setDatabase(Config.mysqlDatabase)
      .setUser(Config.mysqlUsername)
      .setPassword(Config.mysqlPassword)
      .setCharset("utf8") // tried utf8mb4 also same result
      .setCollation("utf8_general_ci") // also tried utf8mb4_general_ci

    val poolOptions = PoolOptions().setMaxSize(Config.maxPoolSize)

    return MySQLPool.pool(vertx, connectOptions, poolOptions)
}
```

mysql variables

| Variable_name | Value|
| --- | --- |
| character_set_client | utf8 |
| character_set_connection | utf8 |
| character_set_database| utf8 |
| character_set_filesystem| binary|
| character_set_results| utf8 |
| character_set_server| utf8mb4|
| character_set_system| utf8 |

table news

|TABLE_COLLATION |TABLE_NAME |
| --- | --- |
| utf8_general_ci | news |

mysql create table

```mysql
 CREATE TABLE `news` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Title` text NOT NULL,
  `Image` text NOT NULL,
  `Link` mediumtext NOT NULL,
  `Summery` mediumtext NOT NULL,
  `Story` mediumtext NOT NULL,
  `Time` timestamp(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 
```

aslo changed the type from text to varchar with same result

from

Name | Type
-- | --
| Title | text |

to 

Name | Type
-- | --
| Title| varchar(2048) |

**Comment by BillyYccc** [comment]
Thanks for reporting, I will take a look

**Comment by BillyYccc** [comment]
@badrazizi Have you checked your collation/charset in your visualized database client?

**Comment by badrazizi** [comment]
> Have you checked your collation/charset in your visualized database client?

@BillyYccc sorry i really don't know, i use phpmyadmin that come with xampp.

Mysql configuration

```
[client]
default-character-set=utf8

[mysqld]
character-set-server = utf8
collation-server = utf8_general_ci

[mysql]
default-character-set=utf8
```

**Comment by BillyYccc** [comment]
Can you give some sample rows to reproduce? Are you using text query or preparedQuery? 
and can you have a try with JDBC MySQL to see if it works in the same way as this client so that we can confirm whether this is a problem

**Comment by badrazizi** [comment]
sample rows

Summery | Title | Time | ID | Image | Story | Link
-- | -- | -- | -- | -- | -- | --
اعلن مطوري فيجول نوفل World End Economica | الإعلان عن مشروع World End Economica | 2019-11-01 19:00:17.000000 | 650 | /2019/10/World_End_Economica.jpg | اعلن مطوري فيجول نوفل World End Economica | /?p=650

yes i use preparedQuery

```Kotlin
query = "INSERT INTO `news` (`Title`, `Image`, `Link`, `Summery`, `Story`) VALUES (?, ?, ?, ?, ?)"
params = ArrayTuple(5)
params.addString(obj.getString("title"))
params.addString(obj.getString("image"))
params.addString(obj.getString("link"))
params.addString(obj.getString("summery"))
params.addString(obj.getString("story"))
sqlEngine.preparedQuery(query, params) { saved ->
  if(!saved.succeeded()) {
    println("Failed to save ${obj.getString("title")}")
  } else {
    val lastInsertId = saved.result().property(MySQLClient.LAST_INSERTED_ID)
    println("Added news with id: $lastInsertId")
  }
}
```

sure i will try JDBC MySQL client

**Comment by badrazizi** [comment]
@BillyYccc yes using JDBC MySQL client worked without error and insert new record correctly

gradle

```
implementation "io.vertx:vertx-jdbc-client:3.8.2"
```

```Kotlin
query = "INSERT INTO `news` (`Title`, `Image`, `Link`, `Summery`, `Story`) VALUES (?, ?, ?, ?, ?)"
val params2 = JsonArray()
params2.add(obj.getString("title"))
params2.add(obj.getString("image"))
params2.add( obj.getString("link"))
params2.add(obj.getString("summery"))
params2.add(story)
sqlClient.queryWithParams(query, params2) { ar ->
  if(!ar.succeeded()) {
    Logging.log("Failed to save ${obj.getString("title")}", vertx)
  }
}
```

result

Summery | Title | Time | ID | Image | Story | Link
-- | -- | -- | -- | -- | -- | --
اعلن مطوري فيجول نوفل World End Economica | الإعلان عن مشروع World End Economica | 2019-11-01 19:00:17.000000 | 650 | /2019/10/World_End_Economica.jpg | اعلن مطوري فيجول نوفل World End Economica | /?p=650

**Comment by badrazizi** [comment]
@BillyYccc any progress, i have not heard from in almost 3 days.

**Comment by BillyYccc** [comment]
can you try with adding [`useServerPrepStmts=true`](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html) to the connection properties of the JDBC url so that the jdbc client uses server-side prepared queries and check that again? The MySQL JDBC client will use a client-side prepared statement by default which is different from reactive mysql client so the comparison does not make sense.

**Comment by badrazizi** [comment]
yes it does insert new record correctly with `useServerPrepStmts=true`

jdbc config

```Kotlin
private val jdbcClientConfig = JsonObject()
    .put("url", "jdbc:${Config.sqlEngine}://${Config.mysqlHost}:${Config.mysqlPort}/${Config.mysqlDatabase}?useUnicode=true&useServerPrepStmts=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC")
    .put("user", Config.mysqlUsername)
    .put("password", Config.mysqlPassword)
    .put("driver_class", "com.mysql.cj.jdbc.Driver")
    .put("max_pool_size", 30)
```

**Comment by BillyYccc** [comment]
I have given another try in https://github.com/BillyYccc/reactive-mysql-client-issue444 but still could not reproduce the problem. 
I debug the network packets for both JDBC and reactive MySQL client and what they send to server  is identical.

I notice you did not configure the `characterEncoding` property in JDBC, can you try with my reproducer and try again?

**Comment by badrazizi** [comment]
i have reproducer please test it [here](https://send.firefox.com/download/fa2a166b9771316b/#RNc38z9-AVOdMlwcgscqBQ)

**Comment by badrazizi** [comment]
@BillyYccc please test the reproducer i post above.

**Comment by BillyYccc** [comment]
I did more experiements but I could not reproduce the problem with using MySQLWorkbench and other clients.
I start MySQL using docker in my reproducer project and here is my server charset config
`SHOW VARIABLES LIKE '%character%'`

```
Variable_name | Value
-- | --
character_set_client | utf8mb4
character_set_connection | utf8mb4
character_set_database | utf8
character_set_filesystem | binary
character_set_results | utf8mb4
character_set_server | utf8
character_set_system | utf8
character_sets_dir | /usr/share/mysql/charsets/
```

can you try retrieving those rows inserted by `reactive-mysql-client` via JDBC or tools other than `phpmyadmin`(like MySQLWorkbench) like what I do in my [reproducer](https://github.com/BillyYccc/reactive-mysql-client-issue444/blob/384bd8cb41bd915b15fe2cc82ad7ce5a0765a02e/src/main/java/com/billyyccc/MySQLClientStarter.java#L33)  and compare the results?

**Comment by badrazizi** [comment]
MySQLWorkbench
`SHOW VARIABLES LIKE '%character%'`

character_set_client | utf8mb4
-- | --
character_set_connection | utf8mb4
character_set_database | utf8
character_set_filesystem | binary
character_set_results | utf8mb4
character_set_server | utf8
character_set_system | utf8
character_sets_dir | C:\xampp\mysql\share\charsets\

Result from MySQLWorkbench

![mysql](https://user-images.githubusercontent.com/6973616/68865215-7eb04900-0703-11ea-909c-1b5398eb3ab3.png)

**Comment by BillyYccc** [comment]
@badrazizi thanks for the clues I see where the problem locates now.

**Comment by BillyYccc** [comment]
can you by the way check what your default charset is by calling `java.nio.charset.Charset.defaultCharset().displayName()`

**Comment by badrazizi** [comment]
it print windows-1252

**Comment by badrazizi** [comment]
i just got working thanks to your comment by setting jvm default charset to utf8

```kotlin
System.setProperty("file.encoding", "UTF-8")
val charset = Charset::class.java.getDeclaredField("defaultCharset")
charset.isAccessible = true
charset.set(null,null)
```

but actually does not solve the issue since `MySQLPool#pool` does not respect `MySQLConnectOptions()#setCharset` configuration, also JDBC is working because i think is set to utf8 by default, or am i misunderstanding the code.

**Comment by BillyYccc** [comment]
Yes setting a default charset to UTF-8 seems to be a work around for now.

the `charset` and `collation` options are configured at the connection level but not really have and effects on charset for encoding, currently the encoding value is encoded in the default charset and I believe we need to improve this, I have posted an issue in https://github.com/eclipse-vertx/vertx-sql-client/issues/447.
