### ISSUE TITLE
Prepared queries caching question

### ISSUE THREAD

**Issue by ebadta81** [eclipse-vertx/vertx-sql-client#455]
Hello,

I found this in the Reactive PostgreSQL Client documentation as a feature.

Is it equals to, for example this one?

```kotlin
client.query("PREPARE example_func(int) AS SELECT 1 WHERE $1 = 1"){}
val tuple = Tuple.tuple()
tuple.addInteger(1)
client.preparedQuery("EXECUTE example_func($1)", tulpe){}
```

I tried this to achieve execution plan caching, but I always get the "Values [1] cannot be coerced to []" error message.

Is this feature supported, or is it already automatically used by the software?

**Comment by BillyYccc** [comment]
Hi I think you're mixing using named prepared statement with unamed ones.
You can either use named prepared statement like 
```
client.query("PREPARE example_func(int) AS SELECT 1 WHERE $1 = 1"){
    client.query("EXECUTE example_func(1)"){}
}
```
or try with
```
val tuple = Tuple.tuple()
tuple.addInteger(1)
client.preparedQuery("SELECT 1 WHERE $1 = 1", tuple){}
```

**Comment by ebadta81** [comment]
Billy, thank you for your answer.

Will vertx-sql-client cache query plan, if I just use a simple preparedQuery?:
 
```kotlin
 val tuple = Tuple.tuple()
tuple.addInteger(1)
client.preparedQuery("SELECT 1 WHERE $1 = 1", tuple){}
```

So what exactly "Prepared queries caching" means [in the documentation](https://vertx.io/docs/vertx-pg-client/kotlin/)?

**Comment by BillyYccc** [comment]
"Prepared queries caching" means when you configure the client with `cachePreparedStatements` on, the client will cache the prepared statement object and it can be used for executing with different parameters several times so that you do not need to prepare every time for the execution. you can also use  the `client#prepare` to prepare the statement and handle it yourself.

there're some issues with the documentation in Kotlin which misses some content for now and I suggest you reading the [Java one](https://vertx.io/docs/vertx-pg-client/java/), the usage is the same except for the language syntax.

**Comment by ebadta81** [comment]
So this caching is happening only in the vertx driver?
This is not postgres execution plan caching, if I understand it correctly. Am I right?

If complex prepared query called frequently, I assume it is worth using both.

What is your opinion?

**Comment by BillyYccc** [comment]
It depends, according to the [official documentation](https://www.postgresql.org/docs/12/protocol-flow.html) it says
> Query planning typically occurs when the Bind message is processed. If the prepared statement has no parameters, or is executed repeatedly, the server might save the created plan and re-use it during subsequent Bind messages for the same prepared statement. However, it will do so only if it finds that a generic plan can be created that is not much less efficient than a plan that depends on the specific parameter values supplied. This happens transparently so far as the protocol is concerned.

You can also just use named prepared statement mentioned above, execute for some times and then try with `EXPLAIN` and see if that works for you.

**Comment by ebadta81** [comment]
There is only one issue remain: I created the named prepared statement, but it is only available for that PG pool, so if the driver assigns the query to another pool, it is another PG session, and it doesn't have the created named prepared statement.

How can I create the named prepared statement in all the pg pools?
If the driver creates more pool later, at bigger load, I need those named prepared statements in all pools.

**Comment by BillyYccc** [comment]
In Postgres prepared statement only exists in the session but you can create several prepared statement in each session. You can measure the load and see if that's a performance bottleneck for you.

**Comment by ebadta81** [comment]
Yea, but how can I do that? 

My idea is, to create all named prepared query at the DatabaseVerticle init time, and after that I can use them. But I cannot control, to which PG pool/session to use and I don't know either how many sessions are.

I can call each prepared query multiple time at the initialization, but it is such a poor design.
