### ISSUE TITLE
How to create named prepared query for all pg pools/sessions?

### ISSUE THREAD

**Issue by ebadta81** [eclipse-vertx/vertx-sql-client#464]
Hi all,

My idea is, to create all named prepared query at the DatabaseVerticle init time, and after that I can use them. But I cannot control, which PG pool/session to use, and I don't know either how many sessions are there.

I can call each prepared query multiple time at the initialization, but it is such a poor design.

How can I create named prepared queries for all my PG sessions?

**Comment by vietj** [comment]
@ebadta81 why do you need to name them ? you can use directly the `SqlClient#preparedQuery` and give it the query you want. Underneath it will prepare the query for you and if you activate prepared statement caching in the options, it will be cached for max performance

**Comment by ebadta81** [comment]
@vietj Is it the same as [postgres PREPARE?](https://www.postgresql.org/docs/12/sql-prepare.html)

I need this for the use of a generic plan, that avoids planning overhead,

**Comment by vietj** [comment]
@ebadta81 preparedQuery does for you prepare / execute with caching when enabled
