### ISSUE TITLE
[Postgres]Provide access to resultset metadata

### ISSUE THREAD

**Issue by f0def** [eclipse-vertx/vertx-sql-client#470]
Please make enum `DataType` and `PgColumnDesc` public (package `io.vertx.pgclient.impl.codec`), previously they were like that

**Comment by BillyYccc** [comment]
hi what's your use case?

f0def <notifications@github.com> 于 2019年12月3日周二 21:45写道：

**Comment by f0def** [comment]
In version 0.11.4 I iterated over metadata's columns and check datatypes

**Comment by BillyYccc** [comment]
I think we could improve this by exposing richer column metadata in the `SqlResult` class rather than just make the internal classes public.

**Comment by f0def** [comment]
It would be great and right, now it seems only `columnNames` [is available](https://github.com/eclipse-vertx/vertx-sql-client/blob/3.8/vertx-sql-client/src/main/java/io/vertx/sqlclient/SqlResult.java#L43 in `SqlResult`), but this is not enough

**Comment by vietj** [comment]
@f0def now in master you can a `ColumnDescriptor` that gives you the name and also type, we can add more stuff to this for PG if that's needed.
