### ISSUE TITLE
io.vertx.pgclient.PgException: deadlock detected

### ISSUE THREAD

**Issue by Globegitter** [eclipse-vertx/vertx-sql-client#480]
We just saw this error in our production environment but no idea why this happened and if we could stop this from happening again in the future. I could also not find anything here in the codebase about this.

We are using ertx-pg-client v3.8.2

**Comment by BillyYccc** [comment]
Can you check details of the error by `PgException#getDetail()`?

**Comment by Globegitter** [comment]
We currently do not keep this in the logs but will add it and report if this occurs again.

**Comment by Globegitter** [comment]
@vietj @BillyYccc we now have the logs and saw it again, so maybe it can be opened again if there is something actionable now:

```
error=io.vertx.pgclient.PgException: deadlock detected)) with PgException code: 40P01, severity: ERROR and detail: Process 20070 waits for ShareLock on transaction 2918394; blocked by process 20191.
```

The query we have been seeing this for are frequent and quite large upsert queries if that would make any difference.

**Comment by Globegitter** [comment]
I found something here: https://stackoverflow.com/questions/46366324/postgres-deadlocks-on-concurrent-upserts so it seems that is nothing to do with vertx and can be left closed :)
