### ISSUE TITLE
Error connecting to PgBouncer pool

### ISSUE THREAD

**Issue by markhofmann** [eclipse-vertx/vertx-sql-client#528]
### Version

3.8.5

### Context

I'm running my services on DigitalOcean with PostgreSQL and use their built-in connection pool (PgBouncer) to connect.

When my application tries to connect to the pool, PgBouncer fails with the message:
"unsupported startup parameter: intervalStyle"

This happens because PgConnectOptions.java sets the intervalStyle, which is not supported by PgBouncer, as a default property:

```defaultProperties.put("intervalStyle", "postgres");```

But "postgres" is already the default value of PostgreSQL, so setting it again as a default value in the client is rather redundant. I don't see why this line should be there.

https://www.postgresql.org/docs/12/runtime-config-client.html#RUNTIME-CONFIG-CLIENT-FORMAT

The workaround is to remove the property directly after creating the PgConnectOptions object, but this is rather dirty since there is no accessor for it (at least in my version):

```connectOptions.getProperties().remove("intervalStyle")```

I noticed a discussion on that in a Pull Request, but not sure about the outcome:
https://github.com/eclipse-vertx/vertx-sql-client/pull/248

### Do you have a reproducer?

No

### Steps to reproduce

1.  Setup a connection pool on DigitalOcean
2. Try to connect to it

**Comment by BillyYccc** [comment]
OK I agree the redundant property could be pruned.
