### ISSUE TITLE
Vertx PG Client fails with Encryption scram-sha-256 

### ISSUE THREAD

**Issue by kameshsampath** [eclipse-vertx/vertx-sql-client#560]
### Version

vert.x pg-client v3.8.5

### Context

I had the issue when working with Reactive PG Client with Postgresql 11 https://github.com/kameshsampath/openshift-pgsql/tree/master/openshift-pgsql11-primary-centos7

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

### Steps to reproduce

1.  Start a Postgres Server using https://gist.github.com/kameshsampath/8efb19534a8b586948967966d0e6d823
2.  Write a simple JBDC insert and Select 
3.  The SQL operations will fail with a stack trace like https://gist.github.com/kameshsampath/7c8a0a64af114e77655f82c3b32ac4fa
4. If you add the  env variable `PG_PASSWORD_ENCRYPTION=md5` to the https://gist.github.com/kameshsampath/8efb19534a8b586948967966d0e6d823  and repeat Step 1..5 you will see the JDBC operations works as expected.

**Comment by BillyYccc** [comment]
The SASL SCRAM-SHA-256 authentication method has been supported in https://github.com/eclipse-vertx/vertx-sql-client/pull/412, however it missed the release of `3.8.5`. The feature in included in `3.9` and `4.0` branches, and I think the `3.9` release will come soon. You can have a try with `3.9.0-SNAPSHOT` now and wait for the `3.9` release.

**Comment by kameshsampath** [comment]
Thanks can wait for new release

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
