### ISSUE TITLE
Rx-ified API issues with Row/RowSet

### ISSUE THREAD

**Issue by jponge** [eclipse-vertx/vertx-sql-client#561]
I am porting code that used the RxJava2 bindings of the client, and especially the `io.vertx.reactivex.sqlclient.Row` and `io.vertx.reactivex.sqlclient.RowSet` types.

I am now getting class cast exceptions as in:

```
java.lang.ClassCastException: io.vertx.pgclient.impl.RowImpl cannot be cast to io.vertx.reactivex.sqlclient.Row
```

with code such as:

```java
  private void ranking(RoutingContext ctx) {
    pgPool
      .preparedQuery(SqlQueries.rankingLast24Hours())
      .rxExecute()
      .subscribe(
        rows -> sendRanking(ctx, rows),
        err -> handleError(ctx, err));
  }

  private void sendRanking(RoutingContext ctx, RowSet<Row> rows) {
    JsonArray data = new JsonArray();
    for (Row row : rows) {
      data.add(new JsonObject()
        .put("deviceId", row.getValue("device_id"))
        .put("stepsCount", row.getValue("steps")));
    }
    ctx.response()
      .putHeader("Content-Type", "application/json")
      .end(data.encode());
  }
```

I know this type of issue usually rings a bell to @vietj 😉

**Comment by jponge** [comment]
Note: the rx-ified APIs do expect Rx-ified `Tuple`, `Row`, etc

**Comment by vietj** [comment]
can you create an issue in vertx-rx project ?

**Comment by vietj** [comment]
it looks like a bug in the code generator, I will have a look soon, it seems blocker for 3.9

**Comment by vietj** [comment]
it is actually a limitation in nested generic types in the generator, I think we can provide a decent solution to this.

**Comment by vietj** [comment]
closing to invalid as it is an rx generator bug / missing feature
