### ISSUE TITLE
Batch method removed in version 3.9.0?

### ISSUE THREAD

**Issue by lygoing** [eclipse-vertx/vertx-sql-client#568]
![image](https://user-images.githubusercontent.com/5944432/78204069-2e2b6380-74cb-11ea-945f-ebf470cfe2ab.png)

**Comment by vietj** [comment]
you need to use client.preparedQuery(SQL).executeBatch(...) instead

please have a look at the breaking changes https://github.com/vert-x3/wiki/wiki/3.9.0-Deprecations-and-breaking-changes#fluent-query-api

**Comment by lygoing** [comment]
@vietj  Thank you very much. ☕️
