### ISSUE TITLE
Add SQL Server Client to the stack

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#569]
Motivation:
Integrate MSSQL client with Kotlin, JavaScript, Groovy, Ruby...

- [x] vertx-dependencies https://github.com/vert-x3/vertx-dependencies/commit/2b6a63fb50470fe41a4aadb04a92ce396e7ddd15
- [x] vertx-stack https://github.com/vert-x3/vertx-stack/commit/5c800fc767d98c77195dc6f130bff227b855da48
- [x] Kotlin https://github.com/vert-x3/vertx-lang-kotlin/commit/0af356249b2f63b9abf58ebf40103981d654e173
- [x] RxJava https://github.com/vert-x3/vertx-rx/commit/a6f1cde0453aea0fc08e448e68b1c367c33cd96f
- [x] Website https://github.com/vertx-web-site/vertx-web-site/pull/106
- [x] Starter https://github.com/vert-x3/vertx-starter/commit/77bd1f0e7495772e08af76daf11af80f74b9d5e9

**Comment by pmlopes** [comment]
Ping me if you need help here.

**Comment by BillyYccc** [comment]
Thanks! the SQL server client has been inactive for some time, I need to find out what is left over and get it spinned again first :-)

The codebase follows the way Vert.x codegen works so there should not be too much work left for this.
