### ISSUE TITLE
Prepared statement created by SqlConnection#prepare should not be cached

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#577]
#### Describe the feature

In the past all prepare statements are cached in the session once created, it's tricky that a user-created object `PreparedStatement` is closed by the cache automatically when the cache is enabled and the entry is evicted.

We should not cache those statements which are not one-shot prepared queries, as the lifecyles of the statments should be managed by the users themselves.

Related changes:
* add a flag in the SPI `PrepareStatementCommand` to indicate whether the prepare command request is from PreparedStatement#prepare or SqlClient#preparedQuery so we know whether the statement should be cached or not

* support named prepared statements for Postgres in `SqlConnection#prepare`, the named statements should also be closed when calling `PreparedStatement#close` by sending a `Close` command to the server.

**Comment by vietj** [comment]
Actually I believe it should not be so complicated:

I think it can be simply done by having two instance of the cache

- a cache for one shot prepared statement where key is the SQL string
- a cache for explicit prepared statements where the key is an UUID provided by the prepared statement

**Comment by vietj** [comment]
right, for explicit `PreparedStatement`, the `PreparedStatement` will cache the prepared statement itself
