### ISSUE TITLE
[MSSQL]Cursor support

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#606]
add support for using cursor/row streaming with sql server client

**Comment by Yaytay** [comment]
Is this on track for 4.3.0?
Can I help at all?

**Comment by tsegismont** [comment]
This is still a priority for 4.3. You can definitely help by testing when
the PR is sent. Thank you

**Comment by tsegismont** [comment]
@Yaytay just pushed the #1175 to implement this.

If you still want to help you can give it a try and report any issue you may find. Thank you
