### ISSUE TITLE
[MSSQL]datatype support

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#608]
currently we only support a small set of all the datatypes, we should expand the support and improve the current data type implmentation(such as `NUMERIC`).

**Comment by BillyYccc** [comment]
## Data type support checklist:

Note some data types have both fixed-length & vairable-length column, we need to support them all.

#### Numeric

- [ ] NUMERIC & DECIMAL (supported but do need some changes) (**HIGH PRIORITY**)
- [x] BIT
- [x] float & real
- [x] int, bigint, smallint, tinyint
- [ ] money & smallmoney

#### String & Binary

- [ ] binary & varbinary
- [x] char & varchar
- [ ] nchar & nvarchar (**HIGH PRIORITY**)
- [ ] ntext, text & image

#### date & time

- [x] date
- [ ] datetime
- [ ] datetime2 (**HIGH PRIORITY**)
- [ ] datetimeoffset (**HIGH PRIORITY**)
- [ ] smalldatetime
- [x] time

#### other

xml, GUID, spatial data types, etc...

**Comment by gavinking** [comment]
I agree that `numeric`/`decimal`, and `datetime2` are very high priority.

After that I would vote for `image`, `text`, and `varbinary`.

**Comment by tsegismont** [comment]
@BillyYccc about _NUMERIC & DECIMAL (supported but do need some changes)_: which changes are needed? I couldn't find any comment or todos in the code

**Comment by BillyYccc** [comment]
I remember the scales are not handled in a right way.

**Comment by tsegismont** [comment]
@BillyYccc would you mind filing a separate issue for this please?

**Comment by tsegismont** [comment]
OK I'll take care of this.

Le ven. 26 mars 2021 à 15:44, Billy Yuan ***@***.***> a
écrit :

**Comment by JonasTaulienSolutions** [comment]
Hello, just wanted to let you know, that we had to switch to the (legacy) jdbc-client because `varchar(max)` is currently not supported.

**Comment by tsegismont** [comment]
@JonasTaulienSolutions was `varchar(max)` the only one missing for your project?

**Comment by JonasTaulienSolutions** [comment]
Currently, its only `varchar(max)` that is missing for us. 
But in the next months we will probably need support for some more. If this happens I will write another message here :)

**Comment by Yaytay** [comment]
We have a lot of GUID columns in our data, would it take much to add support for them?
Thanks.

**Comment by tsegismont** [comment]
@Yaytay it's not very complex to implement. You can take #1048 as an example.

**Comment by Yaytay** [comment]
Hi,
Just submitted #1109 as support for GUID columns.

**Comment by git4rputuval** [comment]
Any progress on the NVARCHAR (MAX), BIT & VARBINARY?
I am under pressure from my management team to evaluate an alternative platform instead of quarkus if this issue is not resolved. Can you guys give me a timeline?

**Comment by tsegismont** [comment]
@git4rputuval `BIT` and `VARBINARY` are supported already.

`NVARCHAR(MAX)` may be supported in 4.2.4 otherwise it will be supported in 4.3.0.

**Comment by git4rputuval** [comment]
@tsegismont Thanks. Dates would have been helpful or at least a timeline like a month, or a quarter or a year.

**Comment by tsegismont** [comment]
@git4rputuval 4.2.4 should be released before the end of next week.

If something is critical for your project, there's the option of helping the community by contributing the pieces you're missing.

**Comment by git4rputuval** [comment]
@tsegismont Thanks. 

4.2.4: The dates are acceptable. 

Contributing the pieces: I believe, you meant, "digging through the code" to identify the issue & providing a solution or work around, right? If yes, will gladly support. If I have misunderstood, do correct me.

**Comment by tsegismont** [comment]
@git4rputuval yes, in this case I meant essentially sharing a pull-request for the feature you're missing.

Anyway, the PR #1120  is ready and should be included in 4.2.4
