### ISSUE TITLE
[MSSQL]Nullable data types are not handled correctly

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#627]
Currently the sql server client only supports `NOT NULL` constraint columns, if the column is nullable and will response with a variable-length data type which we don't support now.
See https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/859eb3d2-80d3-40f6-a637-414552c9c552.

We should add support for decoding [Variable-Length Data Types](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/ce3183a6-9d89-47e8-a02f-de5a1a1303de) such as (INTNTYPE, NVARCHARTYPE, etc...)

Additionally we need to add support for [NBCROW](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/c0da3cc9-4441-476b-aa99-5a518f22dc0a) which contains a null-bit map for nullable values.

**Comment by gavinking** [comment]
Excellent, thanks!
