### ISSUE TITLE
abstraction for MySQLClient.LAST_INSERTED_ID

### ISSUE THREAD

**Issue by gavinking** [eclipse-vertx/vertx-sql-client#639]
So MySQL is not the only database with support for autoincrement/identity columns. And even if it were, it's still a problem that in order to be able to support this feature of MySQL, I need a hard dependency to `MySQLClient.LAST_INSERTED_ID` which is defined in the MySQL client. That means, for example, that if I'm using Hibernate Reactive with Postgres in Quarkus, I'll have a dependency to the MySQL client.

Please add an API that lets us do `rows.property(MySQLClient.LAST_INSERTED_ID)` without needing to compile against the MySQL client.

**Comment by vietj** [comment]
with backport to 3
