### ISSUE TITLE
Reconsider SQL template placeholder as it does not work with string template

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#655]
Currently the SQL template supports SQL syntax like "SELECT * FROM users WHERE id=${id}" and replaces the SQL template holder(${}) with a real SQL placeholder such as ?,$1, etc...

This can work perfectly in Java, however languages like Kotlin and Javascript(ECMAScript 6) supports string template grammar which will interpolate variable into the SQL string, therefore the SQL template couldn't be used.

I propose to use #{} instead of ${} as the sql template placeholder, it enhances the semantic that the sql template statement execution is not a literal value interpolation as well. With this change we need also to check whether it works because Postgres uses # as the bitwise XOR operator.

**Comment by vietj** [comment]
in all cases, there are needs for escaping, things i;e one likely would need to use `\#` I guess.

**Comment by vietj** [comment]
maybe we should use some unicode char :-)
