### ISSUE TITLE
SqlResult.columnTypes()

### ISSUE THREAD

**Issue by gavinking** [eclipse-vertx/vertx-sql-client#657]
In Hibernate Reactive we need a way to obtain information about the type of a column in a `RowSet`.

Please [see my comment here](https://github.com/hibernate/hibernate-reactive/pull/180/files/b505f9530eddf59dfc173f24fa50689b0bb2da3a#r429576118).

**Comment by vietj** [comment]
can you describe what kind of type do you expect ?

e.g the java type mapping as defined by SQL client, the database type which might be specific to each database, i.e PG will tell you INT2, db2 something like SMALLINT, etc...

**Comment by gavinking** [comment]
Well that's a good question. TBH, the most convenient thing *for me* would be a `java.sql.JDBCType`, or one of the integer typecodes in `java.sql.Types`, since those are the type codes used internally in Hibernate.

But you probably don't want a dependency to `java.sql`.

But perhaps you could define an enum with ordinal values that by coincidence *just happen* to match up with codes in `java.sql.Types`?

**Comment by vietj** [comment]
isn't JDBCType in the JDK out of the box ?

we can provide such value if that's convenient

**Comment by gavinking** [comment]
> isn't JDBCType in the JDK out of the box ?

It *is*, but I'm not quite sure what module it's in (post JDK-9).

**Comment by vietj** [comment]
ok that make sense with post JDK9 

I think we can provide at least something that will return an an int value that correspond to this enum mapping

if that's available in JDK OOTB then we can use it as well

**Comment by gavinking** [comment]
That would be perfect, thanks.

**Comment by aguibert** [comment]
IMO we should just go with JDBCType and eat the dependency on java.sql. In practice the extra modules it pulls in is very small and sharing some types with the java.sql module will help interop in some cases.

Another case where I could see this being useful is sharing `java.sql.Blob/Clob`

**Comment by vietj** [comment]
it is not clear to me whether this comes out of the box with the JDK or not

**Comment by aguibert** [comment]
Yes, it is available on all JDK levels out of the box.

**Comment by vietj** [comment]
then it's very fine

**Comment by gavinking** [comment]
Hey, so this one kinda dropped off the radar, but I've verified that it is the cause of a limitation in Hibernate Reactive (compared to Hibernate ORM) for some pretty simple native queries. See:

<https://github.com/hibernate/hibernate-reactive/issues/336>

**Comment by vietj** [comment]
we haven't dropped it from our radar

**Comment by vietj** [comment]
I started a branch https://github.com/eclipse-vertx/vertx-sql-client/tree/column-descriptor

**Comment by vietj** [comment]
@aguibert can you take a look at supporting DB2 2? 
@BillyYccc can you take a look at the MySQL mapping I wrote ?

**Comment by vietj** [comment]
@aguibert @BillyYccc ping

**Comment by gavinking** [comment]
Great, thanks everyone!
