### ISSUE TITLE
preparedQueryAwait is missing from milestone5 and snapshot

### ISSUE THREAD

**Issue by jsoneaday** [eclipse-vertx/vertx-sql-client#673]
io.vertx.kotlin.sqlclient.preparedQueryAwait is missing although strangely getConnectionAwait is there

### Version

milestone5 and snapshot for Kotlin language

### Context

I'm simply trying to import preparedQueryAwait and the message I get is unresolved reference: preparedQueryAwait

### Do you have a reproducer?

https://github.com/jsoneaday/preparedQueryAwaitIssue

### Steps to reproduce

1. Just have your project as a kotlin gradle project for 4.0.0-milestone5 or snapshot and then in the MainVerticle try and import preparedQueryAwait just as I did in the sample. It will fail.

### Extra

Again I am using Kotlin gradle. I do not know if this happens for java or any other languages.

**Comment by vietj** [comment]
I think it is because we changed the API now it should be `preparedQuery(sql).executeAwait(tuple)`

**Comment by jsoneaday** [comment]
I see no preparedQuery in milestone5.
[cid:7d3fbad6-1440-4639-b0c6-85ba33789a64]
________________________________

**Comment by vietj** [comment]
prepareQuery with a d

**Comment by jsoneaday** [comment]
Ok its actually not in the same path either but I see that it comes off of the SqlConnection.


But it looks like VertxDataFetcher got moved and its signature has changed too. Any sample on how to call it now?

io.vertx.ext.web.handler.graphql.schema.VertxDataFetcher

________________________________

**Comment by vietj** [comment]
that is a different topic :-) cc @tsegismont
