### ISSUE TITLE
Add database connection pool monitoring function (recommended)

### ISSUE THREAD

**Issue by GZYangKui** [eclipse-vertx/vertx-sql-client#676]
Hello, we will need to monitor the status of database connection pool during the development of software. At present, vertx SQL client does not seem to provide relevant interfaces. I don't know if we can consider adding this function.

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by vietj** [comment]
we are planning adding support for it that will allow to know about pool queuing and connection lifecycle.

**Comment by GZYangKui** [comment]
Thank you for your hard work！！！
