### ISSUE TITLE
ArrayTuple resizing multiply the capacity by 4 instead of doubling and adding 1

### ISSUE THREAD

**Issue by u4989190** [eclipse-vertx/vertx-sql-client#680]
### Version
3.9.x

### Context
when initializing an ArrayTuple using the length constructor with 0 length,  it would throw the indexoutofbound exception.

### Do you have a reproducer?

the bug is easy to reproduce.

```
Tuple params = new ArrayTuple(0);
params.addInteger(1).addInteger(2);
```

### Steps to reproduce

1.  just run the code above with vertx 3.9+. it is working well with 3.8.x

### Extra

it seems on the line 60 in the file io\vertx\sqlclient\impl\ArrayTuple.java , 
the + operator is evaluated prior to the << operator due to higher precedence. when 0 argument is passed, it is still 0 after shift, and then the problem occurs.

```
  public Tuple addValue(Object value) {
    if (size >= values.length) {
      Object[] copy = new Object[values.length << 1 + 1];
      System.arraycopy(values, 0, copy, 0, values.length);
      values = copy;
    }
    values[size++] = value;
    return this;
  }
```

also, when I tried to find the source code of 3.8.x, I noticed that the branch 3.8 was also changed by the merge. but the maven repo of 3.8.x remains the old implementation(ArrayTuple extending ArrayList). not sure if it is correct though.  anyway, here is the [commit](https://github.com/eclipse-vertx/vertx-sql-client/commit/9915e148d4588da0e8053751f9b820bbaf5e2080)

**Comment by cjsworld** [comment]
It should be `(values.length << 1) + 1`, instead of `values.length << 1 + 1`, which means `values.length * 4`
But why double capacity then plus 1 ? Why not just extends ArrayList ?

**Comment by vietj** [comment]
I don't remember why that was done

**Comment by vietj** [comment]
did you encounter this issue in an actual case ? ArrayTuple is an implementation and should not be instantiated directly. Not saying there is not bug, but I'm curious to hear how this issue happened in practice (unless you do a query on a table with 0 columns ?)

**Comment by cjsworld** [comment]
in our query sql building DSL, we create an ArrayTurple to hold string value. using ArrayTurple(0) instead of Turple.turple() which create a 10 capacity array, because param size is not sure, could be zero.
in ArrayList, zero capacity array is cached in static, could reduce GC if nothing is added.

**Comment by vietj** [comment]
I think there is a good reason we don't extend ArrayList but I don't remember precisely.

**Comment by vietj** [comment]
I've added the empty array caching in 3.9 and master @cjsworld thanks for reporting

**Comment by u4989190** [comment]
> 
> 
> did you encounter this issue in an actual case ? ArrayTuple is an implementation and should not be instantiated directly. Not saying there is not bug, but I'm curious to hear how this issue happened in practice (unless you do a query on a table with 0 columns ?)

yes, it actually is a real case, but happening embarrassingly.
Here is the code snippet we write in practice.

```
String SQL = " SELECT * FROM xxx_tbl ";
int flag = params.getInteger("flag", 0); 
Tuple queryParams = new ArrayTuple(1);
if(flag > 0) {
	SQL += " WHERE flag = ?";
	queryParams.addInteger(flag);
}
		
Promise<JsonObject> promise = Promise.promise();
conn.preparedQuery(SQL).execute(queryParams, res ->  {
	if(res.succeeded()) {
		promise.complete();
	}else{
		promise.fail("");
	}
});
```
somehow this time, one of our team members, who has little knowledege of programming, changes new `ArrayTuple(1)` to new `ArrayTuple(0)`.
I actually asked him why he was doing this, he said he thought it makes no difference since ArrayTuple could grow its capacity itself. sounds terrible, I know.

anyway, that`s how it is found.

**Comment by vietj** [comment]
thanks for reporting it should be fine now
