### ISSUE TITLE
Codegen does not work when Mapping with Vert.x data objects

### ISSUE THREAD

**Issue by yuhaibohotmail** [eclipse-vertx/vertx-sql-client#681]
### Questions
[https://vertx-web-site.github.io/docs/vertx-sql-client-templates/java/#_mapping_with_vert_x_data_objects](url)
Step by step according to the above document description，Codegen does not work when Mapping with Vert.x data objects

### Version
4.0.0-milestone5

### Do you have a reproducer?
[sqltemplate.zip](https://github.com/eclipse-vertx/vertx-sql-client/files/4757739/sqltemplate.zip)

### Steps to reproduce

1.  when  I compile the project  on windows, I got the error message：
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project sqltemplate: Fatal error compiling: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:
/techprj/sqltemplate/target/classes/PathForCodeGenProcessor.class -> [Help 1]`

2. then  I compile the project  on centos, I got the error message：
  `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project sqltemplate: Compilation failure
[ERROR] /root/sqltemplate/src/main/java/org/whedu/sqltemplate/UserDataObject.java:[8,1] Could not generate model for org.whedu.sqltemplate.UserDataObject: Declaration annotated with @VertxGen must be under a package annotatedwith @ModuleGen. Check that the package 'org.whedu.sqltemplate.UserDataObject' or a parent package contains a 'package-info.java' using the @ModuleGen annotation` 

3. I  add   a 'package-info.java' ， compiled successfully but no code generation.

### Extra

* Anything that can be relevant such as OS version, JVM version
Windows 10
CentOS 7

**Comment by yuhaibohotmail** [comment]
The error message is resolved with 4.0.0-SNAPSHOT , but no code was generated.  @vietj

**Comment by vietj** [comment]
can you try using another generator (like generating json converter) to see
if it works?

**Comment by yuhaibohotmail** [comment]
It works using generating json converter , and  ProxyGen

**Comment by vietj** [comment]
can you provide a reproducer project we can try ?

**Comment by yuhaibohotmail** [comment]
[sqltemplate.zip](https://github.com/eclipse-vertx/vertx-sql-client/files/4765222/sqltemplate.zip)
this is a  reproducer

**Comment by yuhaibohotmail** [comment]
@vietj  This issue still exists in the 4.0.0.beta1

**Comment by vietj** [comment]
with the same reproducer ?

**Comment by yuhaibohotmail** [comment]
yes！
It looks like the MapperGenLoader didn't load.

**Comment by yuhaibohotmail** [comment]
@vietj ,Could you spare some time to solve this problem?
Thanks!

**Comment by vietj** [comment]
could you post the issue you have on windows ?

**Comment by vietj** [comment]
@yuhaibohotmail actually the vertx-sql-client-templates project was missing a file and it could not be found by the generator (in your project no file were generated), this commit https://github.com/eclipse-vertx/vertx-sql-client/commit/a2f76957c4a9f83d39c744145afa98a8989f54b8 add the missing file and now it should generate the files

**Comment by vietj** [comment]
do you mind trying a snapshot that contains this change ?

**Comment by yuhaibohotmail** [comment]
I'm willing to try it.

**Comment by yuhaibohotmail** [comment]
The issue is solved！
Thanks！

**Comment by hjianhao** [comment]
> this is a bug on windows, if you use 4.0.0-SNAPSHOT it should be resolved

I am using 4.5.5, still have this issuse.
