### ISSUE TITLE
`XXXAwait` version of vertx-sql-client

### ISSUE THREAD

**Issue by blindpirate** [eclipse-vertx/vertx-sql-client#692]
### Context

[github.com/vietj/reactive-pg-client](https://github.com/vietj/reactive-pg-client)'s doc says that it was superseded by this project, but there's a key feature missing in this project: the `XXXAwait` version (coroutine) of all APIs. I can use `public suspend fun io.reactiverse.pgclient.PgClient.queryAwait(sql: kotlin.String)` version of `io.reactiverse.pgclient.PgClient`, but can't for this project. 

Can we add them?

**Comment by vietj** [comment]
you need to use the `io.vertx:vertx-lang-kotlin-coroutines` artifact

**Comment by blindpirate** [comment]
@vietj Thanks, but I did check `io.vertx:vertx-lang-kotlin-coroutines`, there's no such methods for `vertx-sql-client`, am I wrong anywhere? Can you please elaborate on it?

**Comment by BillyYccc** [comment]
There're breaking changes of the **vertx-sql-client** APIs since `3.9` version, the `await` suffix methods are only generated for those methods with asynchrnous calls.
So now you shall use `val rowSet = client.query("SELECT * FROM users").executeAwait()`

**Comment by blindpirate** [comment]
Got it. @BillyYccc Thank you very much!
