### ISSUE TITLE
DB2 stack integration

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-sql-client#696]
- [x] integration in vertx-stack project
- [x] integrate in vertx-rx, vertx-lang-groovy, vertx-lang-kotlin
- [x] add to vertx-starter stack definition file
- [x] add to current website
- [x] add to next website

**Comment by tsegismont** [comment]
@vietj is there anything missing?

**Comment by tsegismont** [comment]
See https://github.com/vert-x3/vertx-stack#adding-a-new-module-to-the-stack

**Comment by tsegismont** [comment]
@aguibert can you take care of it? Ideally this should be backported to 3.9 branches, if time permits.

**Comment by aguibert** [comment]
sure, I can look into this. I'm not familiar with `vertx-stack`, but it looks like it's basically just a BOM for Vertx modules?

**Comment by tsegismont** [comment]
`vertx-stack` is the repo where we integrate all modules. It contains the `vertx-stack-depchain` modules but also CLI, Docker, ...etc.

All the required steps are listed in https://github.com/vert-x3/vertx-stack#adding-a-new-module-to-the-stack

**Comment by aguibert** [comment]
@tsegismont I've opened all of the required PRs now. Can you please go through the PRs linked on this issue and review+merge them when you have time?

**Comment by tsegismont** [comment]
@aguibert thank you. Done.
