### ISSUE TITLE
Double rollback and transaction exception propagation

### ISSUE THREAD

**Issue by 01101101** [eclipse-vertx/vertx-sql-client#711]
### Version

`4.0.0-milestone5`

### Context

It seems that when a query fails in a transaction, a rollback query is queued. But then, when the future completes (with a failure), the transaction is rollbacked again, generating an error (line 108 of `io.vertx.sqlclient.impl.TransactionImpl` for the first rollback, line 169 in `io.vertx.sqlclient.Pool` for the second rollback).

Maybe this is the right behavior but I find it a bit unexpected.

Also, it would be nice if exceptions occurring inside a transaction bubble up. But I've not read enough code to fully understand the logic behind transactions, so it may not be trivial/doable.

### Do you have a reproducer?

Here is a reproducer https://github.com/01101101/vertx-sql-client-transaction

### Steps to reproduce

1. Create a Postgres database named `test`
2. Run the reproducer

**Comment by vietj** [comment]
thanks for the reproducer we will investigate
