### ISSUE TITLE
Invalid SQL never completes query promise

### ISSUE THREAD

**Issue by wowselim** [eclipse-vertx/vertx-sql-client#714]
### Version

`4.0.0-milestone5`

### Context

I was playing around with the new MySQL client and noticed that invalid SQL isn't properly handled by it. Promises are never completed when there is an invalid query or invalid tuple that doesn't match a prepared query. No exceptions are thrown. Promise is never completed. Thread doesn't seem to be blocked (at least there's no warning in the logs).

Valid queries work fine.

### Do you have a reproducer?

[Gist](https://gist.github.com/wowselim/f0fd187bdb1cb5bfff1daa70daf824d5)

### Steps to reproduce

Use some invalid query such as "abc"

### Extra

It doesn't seem to work with the normal vertx callback-style either.

**Comment by BillyYccc** [comment]
You will need to catch the exception in your verticle otherwise it will be propagated in the verticle deployment.

**Comment by wowselim** [comment]
@BillyYccc I think there's a misunderstanding. The code **does not throw an exception**.

**Comment by wowselim** [comment]
```kotlin
    client.query("abc") { ar ->
      if(ar.succeeded()) {
        println("success!")
      } else {
        ar.cause().printStackTrace()
      }
    }
```

does not print anything

**Comment by BillyYccc** [comment]
could you share a full runnable reproducer such as a maven project so we can why it does not work for you?
