### ISSUE TITLE
rxWithTransaction The return is expected to be a future

### ISSUE THREAD

**Issue by anuranjit** [eclipse-vertx/vertx-sql-client#716]
### Questions

I am trying to use `rxWithTransaction` with Reactive Vertx .  But the return type expected in the lambda function is a Future. 
From Vertx

```
 public <T> Single<T> rxWithTransaction(Function<io.vertx.reactivex.sqlclient.SqlClient, io.vertx.reactivex.core.Future<T>> function) { 
       return AsyncResultSingle.toSingle($handler -> {
              withTransaction(function, $handler);
      });
}
 ```

My usage Code
```
pool.rxWithTransaction(sqlClient -> {
          return Single.just(1);
   });
```
### Version

4.0.0-milestone5

### Context

While using the simplified transaction API.

### Do you have a reproducer?

```
pool.rxWithTransaction(sqlClient -> {
          return Single.just(1);
   });
```

### Extra

OS - Mac Os Catalina
Java version - 11.0.5

**Comment by vietj** [comment]
you can try now with latest master, this has been fixed and rxWithTransaction will accept a `Function<SqlClient, Single<T>>`

**Comment by vietj** [comment]
see https://github.com/vert-x3/vertx-rx/issues/231

**Comment by anuranjit** [comment]
@vietj Will check thanks
