### ISSUE TITLE
Does Reactive-pg-client support MySQL in Vertx?

### ISSUE THREAD

**Issue by XiaohuChen** [eclipse-vertx/vertx-sql-client#72]
Hello, I find it is not convenient to use vertx-mysql-postgresql-client in vertx，and it don't support batch operation. I find Reactive-pg-client and it Ranked #1 in the TechEmpower Benchmark Round 15 Single query benchmark.
 I just want to know, Does Reactive-pg-client support MySQL in Vertx? Or is there any plan to suport MySQL in Vertx?

**Comment by vietj** [comment]
we would like to support it

**Comment by vietj** [comment]
also contributions are welcome

**Comment by BillyYccc** [comment]
It's now supported in https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-mysql-client, closing this issue.
