### ISSUE TITLE
NoSuchMethodError on DB2 and JDK 1.8 with 3.9.3-SNAPSHOT

### ISSUE THREAD

**Issue by gavinking** [eclipse-vertx/vertx-sql-client#736]
See https://github.com/hibernate/hibernate-reactive/pull/319.

I have confirmed that this error does not occur on JDK 11.

**Comment by gavinking** [comment]
What makes this incredibly strange is that this method totally exists in JDK 1.8.

**Comment by aguibert** [comment]
Here is the stack trace of the root issue mentioned in the hibernate reactive issue:

```
  Caused by:
        java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
            at io.vertx.db2client.impl.drda.DRDAConnectRequest.getProductData(DRDAConnectRequest.java:121)
            at io.vertx.db2client.impl.drda.DRDAConnectRequest.buildPRDDTA(DRDAConnectRequest.java:363)
            at io.vertx.db2client.impl.drda.DRDAConnectRequest.buildACCRDB(DRDAConnectRequest.java:68)
```

I have seen this bug a few times locally, and usually it is when I have compiled the Vertx modules with Java 11 but try to run them with Java 8. I wonder if the 3.9.3 modules are accidentally getting compiled at java 11 bytecode level?

**Comment by gavinking** [comment]
>  I wonder if the 3.9.3 modules are accidentally getting compiled at java 11 bytecode level?

Ahah! That is indeed possible. Let me see.

**Comment by gavinking** [comment]
OK, thanks @aguibert, I've rebuilt the 3.9.3 snapshot locally on JDK 1.8, and the error goes away.

The issue is that the snapshot in the sonatype repo was built on JDK 11.

What JDK are *releases* built on?

**Comment by aguibert** [comment]
The releases must be built on 8, but the JDK used to build shouldn't matter since we (should) always set `javac.source/target` to `1.8`. I recall opening a PR to be a bit more explicit about this, but we didn't merge it because @vietj pointed out that it was already set in the parent pom:

```xml
<maven.compilter.target>1.8</maven.compiler.target>
<maven.compiler.source>1.8</maven.compiler.source>
```
This should be the same for all SQL client modules. Is it just the DB2 module giving you this issue, not any of the others?

**Comment by gavinking** [comment]
>  I recall opening a PR to be a bit more explicit about this, but we didn't merge it because @vietj pointed out that it was already set in the parent pom:

Well it seems to me that I've show that this isn't working with the snapshot build.

> Is it just the DB2 module giving you this issue

Right, it only occurs on DB2.

**Comment by aguibert** [comment]
Ok, I think I found some other projects that ran into the same issue here:

https://github.com/eclipse/jetty.project/issues/3244

So to fix this, we should add a Maven profile that activates on JDK 9+ that uses the new `--release 8` compiler option

**Comment by aguibert** [comment]
Fixed this issue in vertx-parent so it will apply to all vertx projects (not just SQL client). Julien will cut a new parent pom release soon

**Comment by gavinking** [comment]
Thanks!

**Comment by vietj** [comment]
master and 3.9 branch have been updated with the pom parent that now should properly build expected jars with JDK >= 9

**Comment by vietj** [comment]
thanks @aguibert for figuring out this issue
