### ISSUE TITLE
After 24 hours pg-client keep connections open

### ISSUE THREAD

**Issue by Valtureyn** [eclipse-vertx/vertx-sql-client#753]
Hello i have a issue with idle connection on my project.

Start of connection (cl is the object use in other class) :
`PoolOptions poolOptions = new PoolOptions().setMaxSize(100);
cl = PgPool.pool(vertx, connectOptions, poolOptions);`

Sample of query :
`public void handleGetDemande(RoutingContext routingContext){
    HttpServerResponse response = routingContext.response();

    JsonArray result = new JsonArray();

    PostgresDatabase.cl.getConnection(reply ->{
      if(reply.succeeded()){
        SqlConnection sql = reply.result();

        sql.query("SELECT demande FROM demandes WHERE demande->>'status' <> 'OK' AND demande->>'status' <> 'aucune données'")
          .execute(res -> {
            if(res.succeeded()){
              RowSet<Row> r = res.result();
              for(Row ro: r){
                JsonObject jo = (JsonObject) ro.getValue("demande");
                result.add(jo);
              }
              response.putHeader("content-type", "application/json").end(result.encode());
            }

            sql.close();
          });
      }
    });`

All my query follow this template.

After 24 hours vertx can't connect to postgres and on the postgres:
![image](https://user-images.githubusercontent.com/26739134/91994208-a1fdc080-ed36-11ea-9c9a-3cc46201f601.png)

I use the 3.9.2 vertx version

If someone can explain the issue ....

After an reboot: i have no issues ...

![image](https://user-images.githubusercontent.com/26739134/91995605-4f250880-ed38-11ea-934b-c7843054a6cb.png)

**Comment by vietj** [comment]
can you try setting an idle timeout on the `PgConnectOptions` ?
