### ISSUE TITLE
methods like getLocalTime(col) return null when col is of wrong type

### ISSUE THREAD

**Issue by gavinking** [eclipse-vertx/vertx-sql-client#766]
In `Tuple.getLocalTime()` and `Tuple.getLocalDateTime()`, `null` is returned when the value is the wrong type.

This is Bad. An exception should be thrown instead.

And it's not even consistent, *sometimes* `Row.getLocalTime()` with throw an `UnsupportedOperationException` (and sometimes even an NPE), at least on MySQL.

So this really needs to be cleaned up.

**Comment by gavinking** [comment]
You should also look at `MySQLRowImpl.getOffsetTime()`, which throws an NPE when `getValue(name)` returns `null`.

It's trying to throw an `UnsupportedOperationException`, but I would say that's wrong also.

All these operations should throw the same kind of error, indicating that the column gas the wrong type.

**Comment by vietj** [comment]
in theory we could use something like Optional but both of us would hate it :-)

**Comment by vietj** [comment]
so the main issue is that null is an ambiguous return value right ?

**Comment by gavinking** [comment]
> in theory we could use something like Optional but both of us would hate it :-)

I say let's not do something we both hate :-)

> so the main issue is that null is an ambiguous return value right ?

Well that's certainly part of it. But it's also that if I have a column named `id` of type `VARCHAR` and I use `getLocalTime()` to read it, then that's almost certainly a bug in my code, and I would prefer an error.

**Comment by vietj** [comment]
what would be the appropriate error to throw ?

**Comment by vietj** [comment]
would `java.util.NoSuchElementException` be a good fit or is there a better exception to reuse ?

**Comment by gavinking** [comment]
Well it's not a `NoSuchElementException`, since there *is* an element with that column name. It's just the element has a different type. I mean, it's essentially a `ClassCastException`, if anything. But perhaps you might want to invent your own exception type instead?

**Comment by vietj** [comment]
indeed that's right, I'm keen on reusing existing exception when possible

**Comment by gavinking** [comment]
Thanks!
