### ISSUE TITLE
SqlConnectionOptions.fromUri()

### ISSUE THREAD

**Issue by gavinking** [eclipse-vertx/vertx-sql-client#767]
Currently we have the useful method `Pool.pool()` which automatically selects the driver based on the concrete class of the given `SqlConnectOptions`.

But I would like a method `SqlConnectionOptions.fromUri()`, which automatically constructs the right type of `SqlConnectOptions` based on the scheme of the given URI.

(It would delegate to `PgConnectOptions.fromUri()`, etc.)

**Comment by gavinking** [comment]
@vietj @aguibert any reactions to this suggestion? Thanks

**Comment by aguibert** [comment]
I like the idea, but in order for that to work the generic `SqlConnectOptions` to delegate to an implementation we would need a service loader mechanism first, similar to what is proposed in this PR: https://github.com/eclipse-vertx/vertx-sql-client/pull/644

**Comment by gavinking** [comment]
OK, I see.

**Comment by vietj** [comment]
what kind of URI are we talking there ?

`PgConnectOptions.fromUri()` supports the URI format specified here https://www.postgresql.org/docs/9.3/libpq-connect.html

**Comment by gavinking** [comment]
@vietj Right, the same URI format. I'm saying I would like a single method that automatically distinguishes the driver type based on the format of that URL.

**Comment by vietj** [comment]
do other databases have similar URI ?

**Comment by gavinking** [comment]
> do other databases have similar URI ?

Yup, at least the ones you support, and Vert.x already has methods for handling them. :-)

**Comment by gavinking** [comment]
(See `MySQLConnectionUriParser`, `DB2ConnectionUriParser`, `PgConnectionUriParser`.)

**Comment by pmlopes** [comment]
I don't know about databases but the official registry (IANA)

https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

does have entries for redis and mongodb for example. The new redis client refers to it and the url format of the connection string follows the iana spec.

**Comment by vietj** [comment]
I don't mind an SPI, however there is already an SPI and I would like to avoid the proliferation of SPI for a feature that seem to be the same, i.e we should reuse the same SPI or have a way to reduce one SPI usage to the other.

**Comment by vietj** [comment]
Something similar like `SqlConnectOptions Driver#fromUri(String uri)` that returns either null or the option could reuse the existing SPI.

**Comment by tsegismont** [comment]
@vietj hasn't this been solved by #1101 ?

**Comment by vietj** [comment]
indeed good catch
