### ISSUE TITLE
Need a SpringBoot starter

### ISSUE THREAD

**Issue by CoderYellow** [eclipse-vertx/vertx-sql-client#769]
Something like _ReactiveJdbcTemplate_ equivalent to  [JdbcTemplate](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html)

**Comment by longdt** [comment]
If you want familiar spring style, I would like to recommend: https://github.com/longdt/vertx-orm-mysql to you. You could give it a try.
disclaim: I'm author of that project

**Comment by BillyYccc** [comment]
have you tried SQL Client Templates? https://vertx-web-site.github.io/docs/vertx-sql-client-templates/java/
