### ISSUE TITLE
fetch size can not be set to a value less than 0, problematic for mysql streaming result sets

### ISSUE THREAD

**Issue by vertxusr123** [eclipse-vertx/vertx-sql-client#781]
### Version

3.8.5 

### Context

The AbstractJDBCAction in the applyStatementOptions method has this clause :
 if (options.getFetchSize() > 0) {
        statement.setFetchSize(options.getFetchSize());
      }

This is problematic for mysql for results sets which are too large to read into memory, my sql jdbc supports streaming result sets when the statement is foward_only, read_only, and fetch size is Integer.MIN_VALUE.

This becomes an issue in the scenario below where  calling connection.rxQueryStreamWithParams on a very large result set, you get an out of memory exception:

SQLConnection connection = sqlClient.rxGetConnection().blockingGet();
SQLOptions options = new SQLOptions();
options.setFetchDirection(FetchDirection.FORWARD);
options.setFetchSize( Integer.MIN_VALUE);
options.setReadOnly(true);
connection.setOptions(options);
SQLRowStream rs = connection.rxQueryStreamWithParams(sql,params).blockingGet()

Expectation was that the fetch sized would have been passed through to the statement but the check for greater than zero prevents this. 

The mysql doc's around the streaming result set can be found here:
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-implementation-notes.html

**Comment by BillyYccc** [comment]
can you open this issue in https://github.com/vert-x3/vertx-jdbc-client?

**Comment by vertxusr123** [comment]
> can you open this issue in https://github.com/vert-x3/vertx-jdbc-client?

Thanks, logged to vert-x3 jdbc-client,:
https://github.com/vert-x3/vertx-jdbc-client/issues/194
