### ISSUE TITLE
4.0.0.Beta3: getConnectionAwait is deprecated but no replacement available

### ISSUE THREAD

**Issue by blindpirate** [eclipse-vertx/vertx-sql-client#785]
### Version

4.0.0.Beta3

### Context

Javadoc says "use getConnection().await()", but there's no `getConnection()` in `SQLClient`.

```
@Deprecated(message = "Instead use getConnection returning a future and chain with await()", replaceWith = ReplaceWith("getConnection().await()"))
suspend fun SQLClient.getConnectionAwait(): SQLConnection {
  return awaitResult {
    this.getConnection(it)
  }
}
```

https://github.com/vert-x3/vertx-jdbc-client/blob/master/src/main/java/io/vertx/ext/sql/SQLClient.java#L42

Is this intentional?

**Comment by vietj** [comment]
yes it is, instead you should write

```kotlin
val conn = client.getConnection().await();
```

**Comment by vietj** [comment]
ah ok, so this is the old client so there is not `getConnection()` that returns a `Future`, can you reopen this issue in the vertx-jdbc-client project ?

**Comment by blindpirate** [comment]
Sure, thanks.

**Comment by vietj** [comment]
the API you are using is the Vert.x 3 API, the Vert.x 4 implementation of Vert.x JDBC Client implements also the new API and we recommend to migrate your app to use it.
