### ISSUE TITLE
ConcurrentModificationException in MySQLPoolImpl / VerxMetricImpl creation

### ISSUE THREAD

**Issue by ylemoigne** [eclipse-vertx/vertx-sql-client#786]
### Version

4.0.0-SNAPSHOT

### Context

The exception :
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1226)
	at io.vertx.micrometer.impl.VertxMetricsImpl.createClientMetrics(VertxMetricsImpl.java:150)
	at io.vertx.mysqlclient.impl.MySQLPoolImpl.create(MySQLPoolImpl.java:33)
	at io.vertx.mysqlclient.MySQLPool.pool(MySQLPool.java:82)

Appear randomly but quite often (1 launch on 3 or 4 maybe).
The pool is created outside vertx event loop thread (on a thread coming from kotlin Dispatchers.Default)
On the same vertx instance, it is possible that another pool with the same configuration is created by another thread also coming from kotlin Dispatchers.Default.

### Do you have a reproducer?

No.

### Extra

I did not have this issue with vertx 3.9.3, so I suspect this is a bug but I'm perfectly ok if the answer is that the pool creations must be single threaded (from event loop or not).

**Comment by vietj** [comment]
sounds like a bug in micrometer, can you reopen the issue there ?

**Comment by vietj** [comment]
`VertxMetrics` implementation should be concurrent

**Comment by vietj** [comment]
if you can provide a reproducer for micrometer it would be great (I think you can concurrently call `createClientMetrics` with several threads)
