### ISSUE TITLE
Allow connectionOptions to change during runtime

### ISSUE THREAD

**Issue by pilzm** [eclipse-vertx/vertx-sql-client#787]
Created as a product of the [discussion](https://github.com/eclipse-vertx/vertx-sql-client/issues/242#issuecomment-709342005) in #242 

### Feature

When creating a `PgPool` using the `PgPool#pool` factory method, provide a way to use a `Supplier<PgConnectOptions>` instead of plain `PgConnectOptions`. This will allow changes to the connect options to apply to new connections created by the pool.

### Use cases

* Change credentials periodically (e.g. token with expiration)
* Change hosts at runtime

### Contribution

If you lack the time and want me to create a PR for this, let me know :)

**Comment by robotmrv** [comment]
are there any updates regarding this feature

**Comment by vietj** [comment]
we are working on a new pool and it will be part of it.

**Comment by vietj** [comment]
The main issue is that having a `Supplier<SqlConnectOptions>` is that creating a connection might be expensive due to loading the certificate when SSL is enabled

**Comment by vietj** [comment]
I think it remains reasonnable if we assume that only some options will change and we can use base same options for networking details, connection properties, etc... Only the server address, username, password and database would vary.

**Comment by robotmrv** [comment]
@vietj are there any plans on release date for this feature

**Comment by vietj** [comment]
you can expect this in 4.1.1 by end of next week
