### ISSUE TITLE
MySQL JSON column can't be retrieved as String

### ISSUE THREAD

**Issue by mcanalesmayo** [eclipse-vertx/vertx-sql-client#788]
### Version

Behavior is happening in 3.9.x. We think it's probably also happening in 4.x from what we've seen in the source code in that version.

### Context

First of all, let me clarify that we are not sure whether this should be considered an issue, as the documentation doesn't explain too much about to what extent MySQL JSON types are supported. FYI, this might be linked to #426 

The issue we are facing is that we can insert a JSON type field as a String, but we can't get it with `Tuple.getString`, even though the documentation states that JSON datatypes can be represented by String (https://vertx.io/docs/vertx-mysql-client/java/#_handling_json). In version 3.9.1, we always get `null` value when using `Tuple.getString` (we can get the column as `JsonObject` by using `resultSet.getObject` tho). In version 3.9.4, we get `java.lang.ClassCastException: class io.vertx.core.json.JsonObject cannot be cast to class java.lang.String`. Using `Tuple.getObject` works fine and retrieves the object.

This is because JSON columns might be decoded into objects that are not `String` (like `JsonObject` or `JsonArray`), depending on the value:
https://github.com/eclipse-vertx/vertx-sql-client/blob/df20a720ec8d3b50e8b4ca47869d0e1c8cf31a8a/vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/datatype/DataTypeCodec.java#L712-L739
However, in version 3.9.1 the `getString` implementation returns `null` if the decoded object is not a `String`:
https://github.com/eclipse-vertx/vertx-sql-client/blob/0faeacce37339cd7f3a565ff7d4c4d956d4536f7/vertx-sql-client/src/main/java/io/vertx/sqlclient/Tuple.java#L318-L324
In 3.9.4, `getString` returns the following, which causes the previously mentioned `ClassCastException`:
https://github.com/eclipse-vertx/vertx-sql-client/blob/df20a720ec8d3b50e8b4ca47869d0e1c8cf31a8a/vertx-sql-client/src/main/java/io/vertx/sqlclient/Tuple.java#L351-L353

We would expect `Tuple.getString` to return the "stringified" JSON instead.

### Do you have a reproducer?

You can reproduce by using Hibernate (we are using 5.4.18.Final), a POJO and use a JPA converter (`AttributeConverter<YourFieldDataType, String>`) on a field that is mapped to a JSON column in the MySQL DB (annotate it with `@Convert`). In 3.9.1 you should see that the method `convertToEntityAttribute` already receives a `null` value as input parameter. In 3.9.4 you should see a `ClassCastException` raised when reading the field from the DB.

### Steps to reproduce

1. Insert a new entry in the DB with a JSON object or array in the JSON field, so that the value of the JSON field is starting with `{` and ending with `}` or `[` and `]`.
2. Trigger a read operation in the DB for that entry.

### Extra

N/A

**Comment by BillyYccc** [comment]
We will add `getJson` accessor method for `Row` and `Tuple` so you can simply use `String.valueOf(tuple.getJson(x))` in later versions to get a stringified JSON element.
