### ISSUE TITLE
Mysql: incorrect mapping collationId -> Java Charset for JSON column

### ISSUE THREAD

**Issue by longdt** [eclipse-vertx/vertx-sql-client#790]
### Questions
From MySql document:
```MySQL handles strings used in JSON context using the utf8mb4 character set and utf8mb4_bin collation```
So `DataTypeCodec.textDecodeJson()` should return utf8 String but `MySQLCollation.getJavaCharsetByCollationId(collationId)` (collactionId = `63` in case JSON column) return Charset ISO-8859-1 which cause incorrect String

### Version

3.9.4

### Steps to reproduce

1. Create table with Json Column
2. Insert Row with Json contain special character like: `{"name":"xin chào vertx mysql"}`
3. Get row and see value of "name"

Mysql version: 5.7

**Comment by vietj** [comment]
@BillyYccc any news of this ?
