### ISSUE TITLE
Time date conversion exception

### ISSUE THREAD

**Issue by GZYangKui** [eclipse-vertx/vertx-sql-client#794]
Hello, the current version of PG is 12. When the specified time value is,However, the official document of PG supports these specific specified values and document addresses:[pg_document](https://www.postgresql.org/docs/12/datatype-datetime.html#DATATYPE-DATETIME-SPECIAL-TABLE),Vertx-pg-client throws an error message as follows:[error_info](https://github.com/databasefx/dbfx/issues/2)

**Comment by vietj** [comment]
can you provide a reproducer project ?

**Comment by GZYangKui** [comment]
Hello, I wrote a test to reproduce this problem. This is the test address:https://github.com/databasefx/dbfx/blob/master/kit/src/test/kotlin/cn/navigational/dbfx/kit/test/impl/PostgresqlClientTest.kt

**Comment by vietj** [comment]
can you provide a standalone project that reproduces it ? that would help

**Comment by GZYangKui** [comment]
OK, I've set up a separate project. This is the project address:[vertx-sql-client-test](https://github.com/databasefx/vertx-sql-client-test)

**Comment by vietj** [comment]
thanks

**Comment by GZYangKui** [comment]
Another problem is that the current client cannot resolve the oid data type

**Comment by vietj** [comment]
closed by https://github.com/eclipse-vertx/vertx-sql-client/issues/800
