### ISSUE TITLE
MSSQL Missing method MSSQLConnectOptions#fromUri

### ISSUE THREAD

**Issue by DavideD** [eclipse-vertx/vertx-sql-client#797]
All the others `*ConnectinoOptions`  have it.

Example: https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-pg-client/src/main/java/io/vertx/pgclient/PgConnectOptions.java#L53

**Comment by vietj** [comment]
is there a specific format for MSSQL uri format ?

**Comment by DavideD** [comment]
I think this issue is related to https://github.com/eclipse-vertx/vertx-sql-client/issues/767

**Comment by BillyYccc** [comment]
what do we do with the prefix designator `jdbc:` since it's a JDBC specfic, should we just provide a parser for `sqlserver://[serverName[\instanceName][:portNumber]][;property=value[;property=value]]`?

**Comment by BillyYccc** [comment]
I would like to introduce a new connection format in a more idiomatic way like what `MySQL` and `Postgres` does, the format is like `sqlserver://[user[:[password]]@]host[:port][/schema][?attribute1=value1&attribute2=value2...`

**Comment by vietj** [comment]
I agree with you that it should be discussed @BillyYccc , perhaps we should have an RFC wiki page with SQL client URLs formats that gather them all to have an higher level view of all of this

**Comment by BillyYccc** [comment]
I have create a RFC wiki page in https://github.com/vert-x3/wiki/wiki/RFC:-SQL-Client-Connecion-URL-format

**Comment by EmadAlblueshi** [comment]
I think we should consider providing multiple hosts in the connection string for cluster database servers such as postgres-xc cluster
