### ISSUE TITLE
Deprecate Tuple/Array XXXArray methods in favor of ArrayOfXXX

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vertx-sql-client#821]
Methods interacting with array values are named in a way such that it collides with `JsonArray`, e.g `getJsonArray` ambiguously named an array of `Json` and a `JsonArray` value. We can use a different naming pattern using `ArrayOf` and have instead `getArrayOfJson` and `getArrayOfJsonArray`.

For String:

- `Tuple#getStringArray(int)` ➡️ `Tuple#getArrayOfString(int)`
- `Tuple#addStringArray(String[])` ➡️ `Tuple#addArrayOfString(String[])`
- `Row#getStringArray(String)` ➡️ `Row.getArrayOfString(String)`

We introduce these new methods and deprecate the old ones. Deprecated methods are removed in Vert.x 4.

**Comment by gavinking** [comment]
Well OK but `getArrayOfString()` is bad grammar!

**Comment by vietj** [comment]
because of plural ?

**Comment by gavinking** [comment]
> because of plural ?

yup.

**Comment by vietj** [comment]
so we should rename it to ArrayOfStrings etc... ?

I found a few example of methods where it was used (and they are therefore
incorrect)

**Comment by gavinking** [comment]
> so we should rename it to `ArrayOfStrings` etc... ?

Well, I'm not sure. All I know is that I would never say "array of string" in speech and I would certainly never write it.

I would say "string array" or "array of strings".

**Comment by vietj** [comment]
we'll correct to use plurals soon then, thanks for reporting this

**Comment by vietj** [comment]
https://github.com/eclipse-vertx/vertx-sql-client/commit/07ef44d1d2a31ce53299ea47b3758dc2e9640571
