### ISSUE TITLE
MySQL load empty data infile cause the session being in an illegal state

### ISSUE THREAD

**Issue by longdt** [eclipse-vertx/vertx-sql-client#827]
### Questions

Load empty data infile cause can't create Transaction correctly. new TransactionImpl schedule command "BEGIN" but result in fail with exception.

### Version

3.9.4

### Do you have a reproducer?

https://github.com/longdt/vertx-mysql-txn-bug
Please checkout this repo then run TransactionTest

### Steps to reproduce

1. use pool.query("LOAD DATA LOCAL INFILE ")  with empty file
2. on result handler. Try get Transaction from pool (`pool.begin()`) 
3. use Transaction to query data 
4. on result handler. Exception: io.vertx.core.VertxException: Transaction already completed occur

### Extra

* Anything that can be relevant such as OS version, JVM version
OS: Ubuntu 20.04
java: 11
mysql server: 5.7

Sorry for my poor english

**Comment by BillyYccc** [comment]
Thanks for reporting and the reproducer, I found it's not related to transactions but the loading empty file will cause the session being in an illegal state.
