### ISSUE TITLE
Client should report failure to the inflight commands when connection get closed by server

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#837]
Currently when the client schedules a command and waits for the server reponse, if the underlying connection gets closed the session will only report failures to the pending commands but the inflight requests get stuck and receive no response, we should report the connection closing event and fail the command instead.

**Comment by BillyYccc** [comment]
This issues is blocking testing against https://github.com/eclipse-vertx/vertx-sql-client/issues/805 as well.

**Comment by BillyYccc** [comment]
@aguibert can you help taking care of the DB2 part for this issue? I tried to write a test using `dbms_lock.sleep` and `FORCE APPLICATION` but failed.

**Comment by vietj** [comment]
@aguibert ping

**Comment by aguibert** [comment]
hi @BillyYccc and @vietj, I can have a look at this over the next few weeks. I'll use the linked PRs as examples of how this should behave

**Comment by vietj** [comment]
Closing this issue as the only remaining implementation with a bug is DB2 and there is a specific issue for this.
