### ISSUE TITLE
[vertx 4.0.0] Connection.close callback may not be called

### ISSUE THREAD

**Issue by ylemoigne** [eclipse-vertx/vertx-sql-client#847]
### Version

Vertx 4.0.0

### Context

Some code working in vertx 3.9.x begin to hang.
After investigation it was comming from `connection.close().await()` (using kotlin-coroutine)
Replacing the kotlin extension `await()` by `onSuccess { ... }.onFailure{ ... }.onComplete{ ... }` showed that none is called.

### Do you have a reproducer?

No, but I think I have an explaination.

The method `close()` is called on a `ConnectionConnectionImpl`. This method create a new `Promise` then call `close(Promise ...)`
If the context is not vertx current context, it dispatch a new `close()` call in the context. But this call has no link to the promise created by the initial `close()` call.

```
@Override
  public Future<Void> close() {
    Promise<Void> promise = promise(); // new promise here
    close(promise);
    return promise.future();
  }

private void close(Promise<Void> promise) {
    if (context == Vertx.currentContext()) {
      if (tx != null) {
        tx.rollback(ar -> conn.close(this, promise));
        tx = null;
      } else {
        conn.close(this, promise);
      }
    } else {
      context.runOnContext(v -> close()); // so `promise` argument of method is never used, a close() will generate a new one
    }
  }
```

**Comment by vietj** [comment]
can you provide a reproducer ?

**Comment by ylemoigne** [comment]
No reproducer as I said in initial post.

As a workaround, I have copied the class `io.vertx.sqlclient.impl.SqlConnectionImpl` in my sourceSet, and in `private void close(Promise<Void> promise)` method I changed :

```
      context.runOnContext(v -> close());
```

to

```
      context.runOnContext(v -> close(promise));
```

No issue found so far from this patch.

**Comment by ylemoigne** [comment]
Thanks. (And congratz for the Vertx 4 release. The migration was a breeze and I love the new website. 🥇 )
