### ISSUE TITLE
sqlclient ConnectionPool looks like it's not thread-safe

### ISSUE THREAD

**Issue by snazy** [eclipse-vertx/vertx-sql-client#849]
It seems that the class `io.vertx.sqlclient.impl.ConnectionPool` (resp `io.vertx.sqlclient.impl.pool.ConnectionPool`) is used in a multi-threaded way but the implementation uses collection-classes like `j.u.HashSet` and `j.u.ArrayDeque` and non-thread-safe modifications to its internal fields like `size`/`checkInProgress`/`closed`.

I was looking into how Quarkus w/ hibernate-reactive is using the pool. Quarkus creates an instance of `org.hibernate.reactive.pool.impl.ExternalSqlClientPool` that keeps a reference to `io.vertx.sqlclient.Pool`, so the interface that `io.vertx.sqlclient.impl.PoolBase` implements, which in turn holds an instance of `ConnectionPool`.

None of the call sites of for example `io.vertx.sqlclient.impl.ConnectionPool#acquire` that I could find are synchronized, so I assume that `ConnectionPool` is expected to be thread safe, but looking at its actual implementation it is not.

**Comment by vietj** [comment]
@snazy the current pool is single threaded and should always access the internal pool state with the same thread.

In Vert.x 4, we have

```java
  public void acquire(Handler<AsyncResult<Connection>> waiter) {
    if (context != null) {
      context.emit(waiter, this::doAcquire);
    } else {
      doAcquire(waiter);
    }
  }
```

in practice context is not null and the context emit operation will ensure that the doAcquire method is called on this thread.

in vertx 3 it should be similar otherwise it is a bug.

**Comment by vietj** [comment]
can you provide a reproducer project for this ?

**Comment by snazy** [comment]
Hm. No reproducer there though.

Just wondering whether the expectation that the pool's always accessed from the same thread is what users of the pool can actually guarantee - like hibernate-reactive in Quarkus - where users have no control on which thread their code's running.

**Comment by vietj** [comment]
any call to the pool should detect whether it's on the right thread and if
it's not schedule a task on this to access it.

perhaps this is not what happens in quarkus and in this case this is a bug
in vertx sql client pool

which is why I'm asking a reproducer.

**Comment by snazy** [comment]
Ah, yea - thanks for the heads-up. I've completely missed the code that does the rescheduling.
Sorry for the noise!

**Comment by Sanne** [comment]
> Hm. No reproducer there though.
> 
> Just wondering whether the expectation that the pool's always accessed from the same thread is what users of the pool can actually guarantee - like hibernate-reactive in Quarkus - where users have no control on which thread their code's running.

I just spoke to @vietj about this, and I understand now that the initialization of the pool I implemented for Quarkus is wrong.

Followed up:
 - https://github.com/quarkusio/quarkus/issues/13868

**Comment by robotmrv** [comment]
Hi @vietj  

I have feeling that there is some misunderstanding regarding vertx Pool - quarkus integration usage with multiple threads.     
So just want to check it from your side.

There is a strange (from my POV) solution in quarkus regarding `Pool` management. Using `ThreadLocal` to make invocation on `Pool` single threaded.  
I was trying to find out why it was introduced but did not receive any detailed answer except that  

>@robotmrv it's quite simple: the pool in vert.x v.3 (which is what we're using here currently) is not designed to work with multiple thread, but is designed to be used by a single thread. So, each thread should have its own.
>
>This will likely change when we switch to vert.x v4

(https://github.com/quarkusio/quarkus/pull/10221#issuecomment-778071151)

As far as I understand from this issue it is valid to invoke vertx 3 `Pool` methods from any `Thread` as there is always logic that schedules state change to the single `context` Thread or synchronizes access to the mutable state (like in `io.vertx.sqlclient.impl.TransactionImpl#schedule()`).  
So there is no (or at least should not be Thread safety issues) with invoking public methods of `Pool`, `Connection` or `Transaction` interfaces from non Vertex Thread`s.  

@vietj 
Please correct me if I am wrong.


regarding this part  
>This will likely change when we switch to vert.x v4

As far as I understand the multithreading problem which will be solved in vert.x v4 version is https://github.com/eclipse-vertx/vertx-sql-client/issues/349  
i.e. `Pool` will use all accessible event loop threads but not only one like in vert.x 3.  

Are you aware of any other multi/single threaded issues/restrictions?

**Comment by vietj** [comment]
@Sanne I think it's better I clarify the behaviors in the various.

On top of my mind here are the expected behaviors:

- a pool is assigned an event-loop (in v3 and current v4), you can use this pool outside of its event-loop safely, if you do
  - in v3 the callback is on the pool event-loop
  - in current v4 the callback is on the correct event-loop (assuming it was done from an event-loop) and the caller and the connection use message passing between threads to perform database interactions
- the new pool we are working on can use several event-loop (so it can distribute IO on them) and will perform a best effort to use the same event-loop than the caller. The strategy to have multiple event-loop is not yet 100% defined, i.e
  - for the moment the pool has no event-loop, when a request is made the pool then
    - try to reuse an existing connection with the same event-loop
    - otherwise create a new connection with the caller event-loop
    - otherwise reuse an existing connection with another event-loop (which is like in the current v4 behavior)
  - we might also provide an implementation that uses a set of predefined event-loop and the pool would round robin on them independently of the caller
