### ISSUE TITLE
PreparedQuery does not take parameter types into account

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-sql-client#851]
This bug reports follows-up on https://github.com/quarkusio/quarkus/issues/11501

The user initially reported they were not able to insert into jsonb column with Pg Client whereas the same query with Postgres JDBC works.

I proposed a better query to the user that works with both Postgres JDBC and the Pg Client as a workaround.

As for the issue, I did a little research and it seems the Pg client does not always send parameter types when preparing a query.

Consider the following table:

```sql
CREATE TABLE object_data (data JSONB)
```

And the following query:

```
INSERT INTO object_data (data)  VALUES (to_json($1)) RETURNING (data)
```

If you execute:

```java
PreparedQuery<RowSet<Row>> insertQuery = pgConnection.preparedQuery("INSERT INTO object_data (data)  VALUES (to_json($1)) RETURNING (data)");
insertQuery.execute(Tuple.of("toto"), ctx.asyncAssertSuccess(rs -> {
  Row row = rs.iterator().next();
  Object value = row.getJson(0);
  System.out.println("value = " + value);
}));
```

You will see:

```
io.vertx.pgclient.PgException: { "message": "could not determine polymorphic type because input has type unknown", "severity": "ERROR", "code": "42804", "file": "parse_coerce.c", "line": "1866", "routine": "enforce_generic_type_consistency" }
```

But if you change this:

https://github.com/eclipse-vertx/vertx-sql-client/blob/a08a7d7d97bdfa9b209afd76d866f4915d448712/vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SocketConnectionBase.java#L194

to

```java
PrepareStatementCommand prepareCmd = prepareCommand(queryCmd, cache, true);
```

Then you get the expected result:

```
value = toto
```

My understanding is that we do not want to send the parameters because we wouldn't be able to cache the prepared statement, correct?

I believe Posgres JDBC checks if the types are the same before reusing a cached statement and, if they are not the same, prepares the statement again with new types.

**Comment by vietj** [comment]
We do not provide the parameters because some queries might use a different parameter that would result in a cast exception in PG (e.g using a function that take any parameter as input, if you bind it with integer, then it will fail for a string).

Normally the client will detect that situation and try a rebind with the parameters when it happens and there is a check for this in `PgSocketConnection`:

```java
  @Override
  public boolean isIndeterminatePreparedStatementError(Throwable t) {
    if (t instanceof PgException) {
      PgException e = (PgException) t;
      return "42P18".equals(e.getCode());
    }
    return false;
  }
````

The error reported in the log is _ 42804_ and we should also check this specific code.

**Comment by vietj** [comment]
Here is the original fix https://github.com/eclipse-vertx/vertx-sql-client/issues/700

**Comment by vietj** [comment]
Here is the issue that happens if you bind parameters https://github.com/eclipse-vertx/vertx-sql-client/issues/700 such queries should not be cached however we cannot detect it.

Hence we have a strategy to first prepare without parameters and when it fails we rebind with parameters.

**Comment by tsegismont** [comment]
pgjdbc stores the parameters used when preparing an re-prepares if the cached query is used with a different type:

https://github.com/pgjdbc/pgjdbc/blob/529e5dc3a8f071ad4946daf3bde1422c21a99524/pgjdbc/src/main/java/org/postgresql/core/v3/SimpleQuery.java#L181-L195

This is not great performance-wise, but that's a choice we could make.

I don't mean we should make it though. Perhaps we could document that in a new doc section that describes differences with pgjdbc?

**Comment by vietj** [comment]
I think we can first support the other code reported by PG and in the
future do what you are suggesting if that remains a blocker issue.

**Comment by tsegismont** [comment]
>I think we can first support the other code reported by PG

Not sure what you mean

**Comment by vietj** [comment]
I mean that the fix we did works when PG reports the error with the code _42P18_ and the error you reported from Quarkus uses the code _42804_. So we should handle and test with error code _42804_.

**Comment by vietj** [comment]
i.e when we get a _42804_ we should prepare the statement with types.

**Comment by tsegismont** [comment]
Yes, thanks for claryfing.

**Comment by tsegismont** [comment]
@vietj added this to 3.9.6 milestone
