### ISSUE TITLE
definer user for view missing shows up as access denied exception

### ISSUE THREAD

**Issue by radai-rosenblatt** [eclipse-vertx/vertx-sql-client#867]
### Version

3.9.2

### Context
i have a Table (lets call it T) and a view V defined on it.
the view V was created by user U, that was at the time running from IP1. mysql defaults for views are "SQL SECURITY DEFINER" and "DEFINER = CURR_USER", which means definer=U@IP1 was "captured".
later on U@IP1 was removed from allowed access, and vertx was run from IP2 (using U@IP2).
when issuing a select statement on the view, vertx  (likely) got error ERROR 1449 ("the user specified as definer does not exist, see https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html#error_er_no_such_user).

this shows up in application code as io.vertx.mysqlclient.MySQLException: Access denied for user ‘U’@‘IP2’ (using password: YES), which is wrong - this is not an access denied of the current user. this isnt an access denied at all.

trying the statement form the mysql command line client returns the correct error:
ERROR 1449 (HY000): The user specified as a definer ('U'@'IP1') does not exist

### Do you have a reproducer?
no. 
### Steps to reproduce

1. create any mysql table
2. create a view on said table
3. set definer on view created above to a not-allowed user@ip combination
4. run select * from view created in 2 above

**Comment by vietj** [comment]
@BillyYccc any idea ?
