### ISSUE TITLE
[vertx-pg-client] Cannot pass string values to prepared queries timestamps using ::timestamptz on the server side

### ISSUE THREAD

**Issue by yuce** [eclipse-vertx/vertx-sql-client#869]
### Version

vertx-pg-client 4.0.0.
Postgres 12

### Context

I'm trying to pass string values for a timestamp column and do the conversion on the Postgres side using `::timestampz` cast.

I've explained the problem at Google groups: https://groups.google.com/u/1/g/vertx/c/vO2Y8DznNEA but copying the relative conversation here just in case.

The Postgres table looks like this:

```sql
CREATE TABLE table1 (
    item_id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ
);
```

(The examples below are in Kotlin, I can rewrite them in Java if it's more convenient)

Using `?::timestamptz` to let PG convert the string works OK with JDBC:

```kotlin
val query =
    """"
    INSERT INTO table1 (created_at)
    VALUES (?::timestamptz)
    """"
DriverManager.getConnection(url).use { conn ->
    conn.prepareStatement(query).use { stmt ->
        stmt.setObject(1, "2017-12-03T10:15:30Z")
        stmt.execute()
    }
}
```

I can't seem to do the same with the Vert.x PG client. I've tried:

```kotlin
val query =
    """"
    INSERT INTO table1 (created_at)
    VALUES ($1::timestamptz)
    """"
client.getConnection().compose { conn ->
    conn
        .prepare(query)
        .execute(Tuple.of("2017-12-03T10:15:30Z"))
        .onComplete {
            if (it.succeeded()) println("Query ran OK")
            else println("Query failed: ${it.cause()}")
        }
}
```
I get the following error with the code above:

```
io.vertx.core.impl.NoStackTraceThrowable: Parameter at position[0] with class = [java.lang.String] and value = [2017-12-03T10:15:30Z] can not be coerced to the expected class = [java.time.OffsetDateTime] for encoding.
```
Note that using `TO_DATE` instead of casting with `::timestamptz` works fine.

### Do you have a reproducer?

Yes, https://github.com/yuce/vertx-pg-client-timestamptz

### Steps to reproduce

(Requires Docker to be present)

1. `git clone https://github.com/yuce/vertx-pg-client-timestamptz`
2. `cd vertx-pg-client-timestamptz`
3. `make build`
4. `make run-docker&`
5. `java -jar ./build/libs/vertx-pg-client-timestamptz-1.0-SNAPSHOT-all.jar`

Thanks and is there anything else I can help with diagnose the issue?

**Comment by vietj** [comment]
this cast expects the date to be provided as an `OffsetDateTime` and not a `String`

I think either you should convert the string to date when creating the tuple or change the query to perform the conversion, something like : `INSERT INTO table1 (created_at) VALUES (TO_TIMESTAMP($1, 'YYYY-MM-DD HH:MI:SS'))`

**Comment by vietj** [comment]
The JDBC driver likely performs the cast for you when using setObject.

The vertx-jdbc-client is a wrapper of the JDBC client, so I'm assuming it
works for the same reason.

**Comment by yuce** [comment]
I've just checked the Postgres driver's `setObject` and it seems to send the string verbatim.

The following is valid Postgres SQL:
```sql
select '2021-01-04T12:55:23Z'::timestamptz;
```
Postgres seems to be happy receiving a string, so I think the string should not be converted to OffsetDateTime (for the query above).

`cast($1 AS timestamptz)` also doesn't work (not sure why `TO_DATE` works) so I think vertx-pg-client's behaviour is incorrect here.

As far as I see, vertx-pg-client loads the table schema, discovers that the column is of timestamp type and tries to cast the passed param to `OffsetDateTime` when preparing the query. The exception is thrown here: https://github.com/eclipse-vertx/vertx-sql-client/blob/60fdcd786fbbd7565d5c4e93a9bf905f07b8045f/vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgParamDesc.java#L61 I'll continue checking whether there's a workaround but do you remember an easy way off the top of your head to bypass casting on the preparation stage?

**Comment by yuce** [comment]
I've experimented with this a bit more and here's what I found.

The following works with Postgres:

```sql
insert into table1 (created_at)
values ('2021-01-04T12:55:23Z');
```

So, Postgres automatically converts it to `TIMESTAMPTZ`. But it doesn't work by default with JDBC (using official Postgres driver) with `stmt.setObject("2021-01-04T12:55:23Z")`:
```
insert into table1 (created_at)
values (?);
```

The exception is:
```
org.postgresql.util.PSQLException: ERROR: column "created_at" is of type timestamp with time zone but expression is of type character varying
```

So, Postgres driver checks just the type of the object passed to `setObject` (which is a string) and sends it with type `VARCHAR`. Postgres doesn't like that and returns an error. The fix is in this case is disabling auto-setting the string type by passing `stringtype=unspecified` property to the JDBC Postgres driver. Something like:
```kotlin
val props =
    Properties().apply {
        setProperty("stringtype", "unspecified")
    }

DriverManager.getConnection(url, props).use { conn: Connection ->
    conn.prepareStatement(query).use { stmt ->
        stmt.setObject(1, "2021-01-04T12:55:23Z"])
        stmt.execute()
    }
}

```

Then it works beautifully.

So, in case JDBC compatibility is a desired trait for vertx-pg-client, it would be supercool if it tried to deduce target field types using the type of passed parameters, not the table schema. (And of course having the ability to set the string type to unspecified would be great).

**Comment by vietj** [comment]
The thing is that such conversion opens the door for all kind of possible (magic) conversions and that is something I would rather like to avoid for various reasons.

In 4.0 we tried to avoid such thing unless it happens for the same type (i.e converting a number format to another format).

**Comment by yuce** [comment]
Thanks to you and all the contributors. Vert.x became my favorite toolkit (if not the favorite tech) in 2020. It has just the right amount of magic so I can get things done in 98% of the cases (the exception is the issue in this ticket and vertx-mqtt auto-sends acknowlegement messages). So, I hope I don't sound too argumentative, it's not my intention.

IMHO JDBC does the less-magic thing here, when the user passes a String it sends a VARCHAR, when the user passes a java.sql.Timestamp then it sends a TIMESTAMP, etc.

Anyway, I think I've found a workaround. `PreparedStatementCommand.java` has the following method:
```
public PrepareStatementCommand(String sql, boolean managed, List<Class<?>> parameterTypes)
```

I guess it allows overriding parameter types for the prepared statement? The only problem is `SqlConnectionBase` doesn't have an overloaded `prepare` method that makes use of it. I'll add it to see whether that fixes the problem.

Thanks again for your time.

**Comment by yuce** [comment]
Adding `Future<PreparedStatement> prepare(String sql, List<Class<?>> parameterTypes)` to `SqlConnection` interface fails with `error: Could not generate model for parameterTypes: Illegal type ? of kind WILDCARD`. Maybe that's why that method is not already in the interface...

**Comment by vietj** [comment]
@yuce that would be something we could add indeed. The limitation you have is due to the code generator  for now you should use Class instead.

**Comment by yuce** [comment]
Like `public Future<PreparedStatement> prepareX(String sql, List<Class> parameterTypes)` ? That also fails similarly:
```
error: Could not generate model for io.vertx.sqlclient.SqlConnection#prepareX(java.lang.String,java.util.List<java.lang.Class>): type java.util.List<java.lang.Class> is not legal for use for a parameter in code generation
```

**Comment by vietj** [comment]
ok, as you can otherwise annotated the method with `@GenIgnore` and use wildcards I think

**Comment by yuce** [comment]
Thanks, that works! I've created a preview PR at https://github.com/scaleplandev/vertx-sql-client/pull/1/files . Probably `preparedQuery(String sql, List<Class<?>>)` method should already be added to `SqlClient` but that seem to require deeper changes.

The changes are trivial but I can create a PR if this is this something that can make its way into the official repo,

**Comment by vietj** [comment]
thanks for the PR. I think we will first try to get wildcard working in the generator before merging and reviewing.

**Comment by vietj** [comment]
Also I think there might be some concerns with prepared statement caching, so this is is something we should think of too. Because the same query could be execute with different classes or not class (as it is the default). So it needs to be carefully thought out.

**Comment by yuce** [comment]
I see. That makes sense.

**Comment by Hetal-Goswami-Einfochips** [comment]
Is it fixed in any latest version of vertx ?

**Comment by tsegismont** [comment]
> Is it fixed in any latest version of vertx ?

No, the decision is https://github.com/eclipse-vertx/vertx-sql-client/issues/869#issuecomment-755264780

**Comment by yonyong** [comment]
> I've experimented with this a bit more and here's what I found.
> 
> The following works with Postgres:
> 
> ```sql
> insert into table1 (created_at)
> values ('2021-01-04T12:55:23Z');
> ```
> 
> So, Postgres automatically converts it to `TIMESTAMPTZ`. But it doesn't work by default with JDBC (using official Postgres driver) with `stmt.setObject("2021-01-04T12:55:23Z")`:
> 
> ```
> insert into table1 (created_at)
> values (?);
> ```
> 
> The exception is:
> 
> ```
> org.postgresql.util.PSQLException: ERROR: column "created_at" is of type timestamp with time zone but expression is of type character varying
> ```
> 
> So, Postgres driver checks just the type of the object passed to `setObject` (which is a string) and sends it with type `VARCHAR`. Postgres doesn't like that and returns an error. The fix is in this case is disabling auto-setting the string type by passing `stringtype=unspecified` property to the JDBC Postgres driver. Something like:
> 
> ```kotlin
> val props =
>     Properties().apply {
>         setProperty("stringtype", "unspecified")
>     }
> 
> DriverManager.getConnection(url, props).use { conn: Connection ->
>     conn.prepareStatement(query).use { stmt ->
>         stmt.setObject(1, "2021-01-04T12:55:23Z"])
>         stmt.execute()
>     }
> }
> ```
> 
> Then it works beautifully.
> 
> So, in case JDBC compatibility is a desired trait for vertx-pg-client, it would be supercool if it tried to deduce target field types using the type of passed parameters, not the table schema. (And of course having the ability to set the string type to unspecified would be great).
Thank you for your ideas, which saved me a lot of detours. I also encountered this issue when using the Vertx pg linet library.
My solution is to use class loading priority mechanism to overwrite the source code of pg client. I found that the reason for this error was due to type strong conversion, so I modified the error reported by strong conversion to encoding level adaptive conversion. For details, please refer to this repository [yonyong/vertx-pg-client-patch](https://github.com/yonyong/vertx-pg-client-patch)

**Comment by yonyong** [comment]
I mainly made two modifications:
1. If the prepare method causes an error when parsing field types, try VARCHAR type conversion
2. When Netty writes a character stream, it no longer uses strong type conversion, but instead takes into account the conversion of string types
