### ISSUE TITLE
Vertx executeBatch not returning all rows

### ISSUE THREAD

**Issue by ivadoncheva** [eclipse-vertx/vertx-sql-client#902]
### Questions

Hello, I want to use pg-client executeBatch() method however the result that I am getting is not what I expect. I see that in the database several rows have been inserted but the result RowSet<Row> contains only the first inserted row. Could you please elaborate on this?

### Version

version: pg-client: 3.9.5

### Do you have a reproducer?
`List<Tuple> batch = new ArrayList<>();
batch.add(Tuple.of("julien", "Julien Viet"));
batch.add(Tuple.of("emad", "Emad Alblueshi"));

// Execute the prepared batch
client
  .preparedQuery("INSERT INTO USERS (id, name) VALUES ($1, $2) RETURNING id")
  .executeBatch(batch, res -> {
  if (res.succeeded()) {

    // Process rows
    RowSet<Row> rows = res.result();
    System.out.println("Got " + rows.rowCount() + " rows ");

    for (Row row : rows) {
	System.out.println("User id: " + row.getInteger("id"));
     }
  } else {
    System.out.println("Batch failed " + res.cause());
  }
});`

Output is always the first inserted row:
Got 1 rows
User id: julien

**Comment by vietj** [comment]
what the client provides shall really be what the database returns, did you check the smae with JDBC ?

**Comment by vietj** [comment]
so here is what happens and it makes sense to me (and I will clarify it in the doc):

each insert will be a RowSet of its own, you can access the next row set using the`next()` method, e.g

```java
        client
          .preparedQuery("INSERT INTO Test (id, val) VALUES ($1, $2) RETURNING id")
          .executeBatch(batch, ctx.asyncAssertSuccess(r1 -> {
            ctx.assertEquals(14, r1.iterator().next().getInteger("id"));
            RowSet<Row> r2 = r1.next();
            ctx.assertEquals(15, r2.iterator().next().getInteger("id"));
            async.complete();
          }));
```

**Comment by vietj** [comment]
https://github.com/eclipse-vertx/vertx-sql-client/issues/903

**Comment by ivadoncheva** [comment]
> so here is what happens and it makes sense to me (and I will clarify it in the doc):
> 
> each insert will be a RowSet of its own, you can access the next row set using the`next()` method, e.g
> 
> ```java
>         client
>           .preparedQuery("INSERT INTO Test (id, val) VALUES ($1, $2) RETURNING id")
>           .executeBatch(batch, ctx.asyncAssertSuccess(r1 -> {
>             ctx.assertEquals(14, r1.iterator().next().getInteger("id"));
>             RowSet<Row> r2 = r1.next();
>             ctx.assertEquals(15, r2.iterator().next().getInteger("id"));
>             async.complete();
>           }));
> ```

Hi @vietj, thank you for your quick response. It would be really nice to document this as currently the documentation is rather confusing.

 
```
.executeBatch(batch, res -> {
  if (res.succeeded()) {
    // Process rows
    RowSet<Row> rows = res.result();
```

I tried the example that you have documented:
```
 for (RowSet<Row> rows = ar.result();rows.next() != null;rows = rows.next()) {
            Integer colorId = rows.iterator().next().getInteger("color_id");
            System.out.println("generated key: " + colorId);
          }
```

However, it seems that it doesn't get the least inserted element. Do you have any idea? I am still trying to understand why this happens.

**Comment by zero88** [comment]
@ivadoncheva 
Use this one
```
if (ar.succeeded()) {
    RowSet<Row> rows = ar.result();
    int[] count = new int[] {0};
    while (rows != null) {
        count[0]++;
        rows.iterator().forEachRemaining(row -> {
            System.out.println(row.toJson());
        });
        rows = rows.next();
    }
    ctx.verify(() -> Assertions.assertTrue(count[0] > 0));
} else {
    ctx.failNow(ar.cause());
}
```

**Comment by ivadoncheva** [comment]
Thanks, @zero88. This works!
