### ISSUE TITLE
postgresql support, sessions are not ended at connection close (pool in use here)

### ISSUE THREAD

**Issue by amb1ent** [eclipse-vertx/vertx-sql-client#908]
### Version

Which version(s) did you encounter this bug ?

4.0.2

### Context

I am busy porting plenty of web-services from worker-pool postgresql jdbc client to this client.  I have finished my first one.

I use pg_advisory_lock as well as transactions, the locks were not freed at session end.

For the interim, I have added the following code my side to 'close' the connection (returning it to the pool)

```
public static void closeEndingSession(SqlConnection con) {
        con.query("ROLLBACK").execute().onComplete(ar1 -> {
            if (!ar1.succeeded()) {
                final Throwable t = ar1.cause();
                boolean log = true;
                if (t instanceof PgException) {
                    final PgException pgException = (PgException) t;
                    if ("25P01".equals(pgException.getCode())) { // no tx in progress error
                        log = false;
                    }
                }
                if (log) {
                    logger.warn(ar1.cause());
                }
            }
            con.query("DISCARD ALL").execute().onComplete(ar2 -> {
                if (!ar2.succeeded()) {
                    logger.warn(ar2.cause());
                }
                con.close(ar3 -> {
                    if (! ar3.succeeded()) {
                        logger.warn(ar3.cause());
                    }
                });
            });
        });
    }
```

The 'DISCARD ALL' statement is necessary at the end of the session to clean up resources associated with the session freeing the locks.

If you can keep track of transaction state in the library the 'ROLLBACK' statement is not necessary.  Note, at this point in my code I do not have a valid Transaction object, or a java exception may have been thrown without committing or rolling back the transaction.

Note that this statement will also drop any query plans for cached prepared statements.

https://www.postgresql.org/docs/12/sql-discard.html

### Do you have a reproducer?

No, sorry, the code is closed-source.  It should be easy enough to reproduce with some code.

### Steps to reproduce

1. open two connections from a pool
2. execute "SELECT pg_advisory_lock(1);" on connection 1, then close the connection on complete.
3. execute "SELECT pg_advisory_lock(1);" on connection 2, after connection 1 close is complete, this will block because connection 1's resources were not freed.

At least, that's what I saw on my side until I patched the close statement.

### Extra

ubuntu 20.10, java 15, pg 12

**Comment by BillyYccc** [comment]
The pool does not reset the state or execute any SQL for connections in the pool after executing, maybe we could provide an async hook for users to config at pool level like `Function<SqlConnection, Future<Void>>` to add.

**Comment by amb1ent** [comment]
Sounds like a flexible suggestion; I would like to know in the hook whether or not a transaction has started but not committed or been rolled back so I only issue rollback when needed.

**Comment by vietj** [comment]
Can you use the transaction API ? 

if you do then the connection could be aware of the transaction status and rollback the transaction before returning the connection to the pool.

**Comment by vietj** [comment]
given that PostgreSQL notifies the transaction status, it might be possible to do that automatically

**Comment by vietj** [comment]
if you are using the transaction api, the tx should be rollback when the connection is returned to the pool. I checked that.

we can make PG connection aware of this without a transaction using the transaction status but this requires more work and some internal refactoring, so that will not make it in 4.0.3.

**Comment by amb1ent** [comment]
I'm using the tx api & explicitly committing and rolling back where i can; It's good to know that the transactions will be rolled back; this is more about exception handling.  I don't have the guarantees of ```try { ... con.commit(); } catch { ... con.rollback(); } finally { con.close(); }``` that I had with JDBC.

Are you able to add the hook somehow to the pool so that after the tx is rolled-back on return I can add some logic e.g. issue DISCARD ALL or indeed just pg_advisory_unlock_all().  I have a to-do once I've ported all my webservices to the async connector to rewrite them all to use prepared statements, at which point I won't want to use DISCARD ALL as it drops the query plans.

From my perspective I have a solution so there's no urgency for the next release.

**Comment by vietj** [comment]
the Transaction object has a `completion` future that is called when a transaction is commited or rolled back.

**Comment by vietj** [comment]
we are currently working on the pool rewrite for 4.1 and we will take this in account as we also want to have pre function to be called when a connection is taken out of the pool

**Comment by vietj** [comment]
@amb1ent there have been some changes in master with the new pool, can you have a look again and provide an update ?

**Comment by vietj** [comment]
with Postgres we can know the transaction status and rollback an on going unfinished transaction when it is put back in the pool I think

**Comment by amb1ent** [comment]
@vietj can you publish a 4.1.0-snapshot to a maven repository?  It's almost beyond me building the entire vertx system, I am rather rusty with the tools - I'd need pointers to do that, send by email if you still have my address?

**Comment by vietj** [comment]
snapshots are published already at
https://s01.oss.sonatype.org/content/repositories/snapshots/io/vertx/

**Comment by amb1ent** [comment]
I got a failure using this with unmodified code on my side and the 4.1.0-SNAPSHOT via s01 repo:

```
java.lang.ClassCastException: class io.vertx.core.impl.DuplicatedContext cannot be cast to class io.vertx.core.impl.EventLoopContext (io.vertx.core.impl.DuplicatedContext and io.vertx.core.impl.EventLoopContext are in unnamed module of loader 'app')
	at io.vertx.sqlclient.impl.pool.SqlConnectionPool.acquire(SqlConnectionPool.java:192)
	at io.vertx.sqlclient.impl.PoolBase.acquire(PoolBase.java:165)
	at io.vertx.sqlclient.impl.PoolBase.getConnection(PoolBase.java:132)
```

calling code looks like:

```
PgConnectOptions connectOptions = new PgConnectOptions()
                            .setPort(dbConfiguration.port)
                            .setHost(dbConfiguration.host)
                            .setDatabase(dbConfiguration.db)
                            .setUser(dbConfiguration.user)
                            .setPassword(dbConfiguration.password)
                            .setCachePreparedStatements(true);

                    PoolOptions poolOptions = new PoolOptions()
                            .setMaxWaitQueueSize(concurrency * 4)
                            .setMaxSize(concurrency);

                    PgPool pool = PgPool.pool(vertx, connectOptions, poolOptions);
```

```
pool.getConnection().onComplete(ar -> {
                    if (DEBUG) {
                        if (ar.succeeded()) {
                            logger.warn("pool connect succeeded " + ar.result());
                        } else {
                            logger.warn("pool connect failed.");
                        }
                    }
                    complete.handle(ar);
                });
```

**Comment by amb1ent** [comment]
If you implemented DISCARD ALL then I will need something different just pg_advisory_unlock_all() as I want to keep the cached prepared statements, for part of my s/w the SQL is quite long and a lot of work for the query planner.  Hopefully this is something the developer can choose at pool creation?

**Comment by amb1ent** [comment]
> I got a failure using this with unmodified code on my side and the 4.1.0-SNAPSHOT via s01 repo:

This exception has now been resolved with the current snapshot, which appears to work fine with unchanged code on my side now.

**Comment by vietj** [comment]
I will resolve this issue then.
