### ISSUE TITLE
ProxySQL drops connections

### ISSUE THREAD

**Issue by dangfan** [eclipse-vertx/vertx-sql-client#915]
### Version

Vert.x Sql Client 4.0.0 Beta1 & 4.0.2

### Context

I occasionally see exceptions saying that `io.vertx.core.VertxException: closed`. At the same time, I also see logs in ProxySQL as

```
2021-03-14 11:13:23 MySQL_Session.cpp:3854:handler(): [ERROR] Unexpected packet from client 192.168.x.x . Session_status: 33 , client_status: 538976288 Disconnecting it
```

### Do you have a reproducer?

I'm sorry that I cannot reproduce this issue, but I've made some research. Here are what I found:

1. When ProxySQL disconnects, it received two consecutive `Request Execute Statement`. Usually, a `Request Execute Statement` follows a `Response`, which are most cases in the captured data.

![image](https://user-images.githubusercontent.com/1330913/111074402-b27cc800-851d-11eb-9035-45fdf0af31ac.png)

2. I tried to reproduce such cases, however, I failed. Here are snippets that I tried:

```kotlin
    SqlTemplate.forQuery(pool, "select sleep(5)").executeBatch(listOf(mapOf(), mapOf(), mapOf(), mapOf()))
```

```kotlin
    val conn = pool.connection.await()
    conn.query("select sleep(5)").execute()
    conn.query("select sleep(5)").execute()
    conn.query("select sleep(5)").execute()
```

In both cases, the queries were executed one by one.

I currently assume that this might be a bug. Please correct me if this is on purpose.

**Comment by BillyYccc** [comment]
it looks like a bug, do you access the `conn` object concurrently or from a different vertx context?

and do you execute queries concurrently like this in your code?
```
    val conn = pool.connection.await()
    conn.query("select sleep(5)").execute()
    conn.query("select sleep(5)").execute()
    conn.query("select sleep(5)").execute()
```

**Comment by dangfan** [comment]
> it looks like a bug, do you access the conn object concurrently or from a different vertx context?

I reviewed the code. Most of them are written like this:

```kotlin
SqlTemplate
    .forQuery(pool, sql)
    .mapTo(Model::class.java)
    .execute()
    .await()
```

Other usages are like this:

```kotlin
pool.getConnectionAwait()
      .use { it.preparedQuery(sql).execute(Tuple.of(data)).await() }

inline fun <R> SqlConnection.use(block: (SqlConnection) -> R): R {
  var exception: Throwable? = null
  try {
    return block(this)
  } catch (e: Throwable) {
    exception = e
    throw e
  } finally {
    when (exception) {
      null -> close()
      else -> try {
        close()
      } catch (closeException: Throwable) {
        // ignored here
      }
    }
  }
}
```

> and do you execute queries concurrently like this in your code?

When I tried to reproduce, I tested the following code:

```kotlin
  val conn = pool.connection.await()
  conn.query("select sleep(5)").execute()
  println("test")
  conn.query("select sleep(5)").execute()
  println("test")
  conn.query("select sleep(5)").execute()
  println("test")
```

and `test` is printed three times without any delay.

**Comment by vietj** [comment]
it is very hard for us consider this as a bug because the connection might be used incorrectly, please reopen when you a reproducer that exhibits a bug and then we can fix it
