### ISSUE TITLE
[vertx4] RowMapper generation fails with gradle

### ISSUE THREAD

**Issue by deedarb** [eclipse-vertx/vertx-sql-client#919]
vertx-sql-client example for RowMapper generation not working with gradle

gradle warns:

**warning: Unclosed files for the types 'PathForCodeGenProcessor'; these types will not undergo annotation processing**

reproducer: https://github.com/deedarb/vertx-sql-client-gradle

`./gradlew compileJava`

environment: 
java 11 (adoptopenjdk)
gradle 6.8.3
vertx 4.0.3

**Comment by jponge** [comment]
The `implementation`  and `annotationProcessor` scopes are distinct, so you need to repeat the dependencies that you need for code generation in `annotationProcessor`.

See https://github.com/jponge/vertx-in-action/blob/master/chapter6/build.gradle.kts as an example.
