### ISSUE TITLE
[MySQL] Parameters of type Binary must match the size of the type defined for the table

### ISSUE THREAD

**Issue by DavideD** [eclipse-vertx/vertx-sql-client#922]
It seems a bug because the same query works for all the other databases.
If the table defines a column of type `Binary(255)` but the query uses a `Binary(16)`, it won't find the row.

It happens in Vert.x 3.9.6 and 4.0.2

```
  @Test
  public void testBinaryAsParameter(TestContext ctx) {
    // The column is defined as binary(5)
    byte[] b = new byte[2];
    new Random().nextBytes( b);
    Buffer buffer = Buffer.buffer( b );
    MySQLConnection.connect(vertx, options, ctx.asyncAssertSuccess(conn -> {
      conn.preparedQuery("INSERT INTO datatype (`Binary`, id) VALUES (?,?)").execute( Tuple.of( buffer, 678 ), ctx.asyncAssertSuccess( updateResult -> {
        conn.preparedQuery("SELECT `Binary` FROM datatype WHERE `Binary` = ?").execute( Tuple.of( buffer ), ctx.asyncAssertSuccess( result -> {
          ctx.assertEquals(1, result.size());
          Row row = result.iterator().next();
          ctx.assertEquals( buffer, row.getValue( 0 ) );
          conn.close();
        }));
      }));
    }));
  }
```

The commit with the change to add the test on the main branch is here: https://github.com/DavideD/vertx-sql-client/commit/1abdfe82af233327d03401418c9840791a57e3b1

**Comment by BillyYccc** [comment]
The BINARY data type value stored in the MySQL database is right padded with zero bytes to the specific length, you will get the same result if you are using jdbc. So you have to pad the param array by yourself in the code to make it correct.

**Comment by DavideD** [comment]
> you will get the same result if you are using jdbc

This seemed to work when I tested it with JDBC. But I will double check.

**Comment by DavideD** [comment]
> This seemed to work when I tested it with JDBC. But I will double check.

I was wrong, it doesn't work with JDBC. Uff...ok, thanks
