### ISSUE TITLE
Undesirable transaction error response

### ISSUE THREAD

**Issue by bhowell2** [eclipse-vertx/vertx-sql-client#930]
Hi All,

Have an issue with the error messages returned in a transaction. I've attached a reproducer.

When creating a transaction and running multiple commands simultaneously if an error occurs the error message will not be returned, but the error message "Transaction already completed." will be returned instead. This makes it difficult to trace the source of the issue.

Accidentally repeated myself when copying in the code to the README. Forgive that!

https://github.com/bhowell2/vertx-sql-transaction-reproducer

**Comment by vietj** [comment]
thanks I'll have a look

**Comment by vietj** [comment]
@bhowell2 what you posted does not seem like an issue because you are using a CompositeFuture and the original failure will also be reported on the CompositeFuture. The future 3 and 4 are failing because the transaction rolled back and not because of the query 2 since they are not related

**Comment by vietj** [comment]
@bhowell2 can you provide a reproducer without `CompositeFuture` ?

**Comment by bhowell2** [comment]
Hey Julien, sorry about this. That makes complete. It's not an issue then, but more ergonomic than anything. I encountered it when using the rxified API and it was from `Completable.merge(...)` or `Single.merge(...).lastOrError()` to obtain a completable or single from the transaction operations, but it was returning the last error rather than the first and I didn't notice.

**Comment by vietj** [comment]
well I believe there are some with with `withTransaction` that can hide the original transaction, but in this case it seems to be like a race issue due to `CompositeFuture`
