### ISSUE TITLE
PrepareStatementCommandCodec should handle message ParameterStatus

### ISSUE THREAD

**Issue by marsbergen** [eclipse-vertx/vertx-sql-client#934]
### Version

Which version(s) did you encounter this bug ?

Postgres on RDS v12.5
vertx-pg-client v3.9.2
jooq v3.13.1

### Context

We have Sentry reporting that `io.vertx.pgclient.impl.codec.PgCommandCodec` has thrown the following exception: `PrepareStatementCommandCodec should handle message ParameterStatus`

### Do you have a reproducer?

Not particularly, since Sentry gave no further context for now, I have no clue where it went wrong in our code. If I get more context of future events I'll add it to this issue.

The following snippet is part of our Kotlin code to execute a query:

```kotlin
private fun prepareBindValues(values: List<Any>) = values.map {
  if (it.javaClass.isEnum) {
    return@map (it.javaClass.enumConstants as Array<Enum<*>>).first { enum -> enum == it }.name
  }
  return@map it
}

suspend fun Pool.executeAwaitPreparedJooqQuery(query: Query): RowSet<Row>? {
  val q = preparedQuery(query.sql)
  return q.executeAwait(Tuple.wrap(prepareBindValues(query.bindValues)))
}

client!!.executeAwaitPreparedJooqQuery(Postgres.JooqQuery
    .select()
    .from(TABLE)
    .where(TABLE.ID.eq(id))
    .and(TABLE.EXPIRES_AT.ge(DSL.currentOffsetDateTime()))
    .limit(1))

```

**Comment by vietj** [comment]
it seems like you can ignore there messages, according to the PG frontend/backend protocol:

_This message informs the frontend about the current (initial) setting of backend parameters, such as client_encoding or DateStyle. The frontend can ignore this message, or record the settings for its future use; see Section 46.2.6 for more details. The frontend should not respond to this message, but should continue listening for a ReadyForQuery message._

did you see any actual misbehavior related to this ?

**Comment by vietj** [comment]
I will simply remove the logging of this in the actual codebase.

**Comment by vietj** [comment]
I changed logging to

```
    logger.warn("Parameter " + key + " changed to " + value);
```

so we know what has changed and we can determine whether this has an impact or not on the client.

**Comment by marsbergen** [comment]
@vietj Ah that's great, thanks for the fast response!
I indeed didn't see any other failures, that was also why I was surprised to see this message being reported.
