### ISSUE TITLE
Connection leak when using idle-timeout on PoolOptions

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-sql-client#935]
This applies to 3.9.6, 3.9.7 and 4.0.3. It does not apply to 4.1.0 (snapshot with new pool implementation).

When an idle-timeout is set on `PoolOptions`, the pooled connection is not closed properly.
It is removed from the list of available connections but stays open.

On PostgreSQL, this can be observed by inspecting `pg_stat_activity` and finding connections in `IDLE` state.

**Comment by tsegismont** [comment]
cc @pjgg

**Comment by vietj** [comment]
we should

- recommend not using this option in current releases (keeping in mind that in 3.x this code is *tech preview*)
- remove this option from 3.9 and file it as a breaking change
- check whether this issue happens with the new pool for 4.1

**Comment by gsmet** [comment]
Isn't it the feature that was very recently introduced to fix an issue reported in Quarkus?

**Comment by vietj** [comment]
it was introduced to add a new feature that was asked by the user, we should have refrained ourselves and not implement it and instead wait this was implemented in Vert.x 4.1
