### ISSUE TITLE
[vertx-pg-client] PreparedQuery hangs if UUID does not have dashes

### ISSUE THREAD

**Issue by rgmz** [eclipse-vertx/vertx-sql-client#938]
### Version

4.0.3

### Context

When using the PG client, passing a malformed UUID to a `preparedQuery` will cause the execution to hang indefinitely, _without_ throwing an exception.

This is unexpected because -- although UUIDs without dashes are technically invalid -- PostgreSQL accepts both  `971cff9c-f325-4e12-a9c5-6a7f27131d06` and `971cff9cf3254e12a9c56a7f27131d06`.

### Do you have a reproducer?

https://github.com/rgmz/vertx-pg-client-uuid-bug

### Steps to reproduce

1. Clone the repository above
    ```sh
    git clone https://github.com/rgmz/vertx-pg-client-uuid-bug && cd vertx-pg-client-uuid-bug
    ```
2. Start PostgreSQL
    ```sh
    docker-compose up -d
    ```
3. Start the application
    ```sh
    ./mvnw compile vertx:run
    ```

4. The application will run and only create 3 people:
    ```sh
    Creating people...
    Failed to insert person: timed out after 10s
    >>>>>>>>> PEOPLE <<<<<<<<<
     > id=3c8ea5b9-638e-4946-bc9e-e0a13e4b5a2c, name=Tom
     > id=5a65e891-7b4e-4c6f-b2c0-c35fbb9d87dc, name=Dick
     > id=5a5ad8a4-8230-476c-98a6-a27b7f70f4e9, name=Harry
    ```

### Extra

This error is likely caused by `UUID.fromString(...)` throwing an exception that is never caught, either:
https://github.com/eclipse-vertx/vertx-sql-client/blob/d03f06806a1aad71f078259861f7705fb50200bb/vertx-sql-client/src/main/java/io/vertx/sqlclient/Tuple.java#L600-L611
https://github.com/eclipse-vertx/vertx-sql-client/blob/a6dba023704e922b02ce6c7dd8e1bb6c23acb417/vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataTypeCodec.java#L1291-L1293

If an IllegalArgumentException is thrown we would ideally parse to determine if it's a valid UUID. For example, here's my helper method (UUIDv4 only):
```kotlin
private val pattern = """^(\w{8})(\w{4})(\w{4})(\w{4})(\w{12})$""".toRegex()

fun fromString(value: String): UUID {
    // Parse the UUID segments from the given string.
    // https://en.wikipedia.org/wiki/Universally_unique_identifier#Format
    val segments = pattern.matchEntire(value.trim())
        ?.groupValues
        ?.drop(1) // Match groups include the original string, which we don't need.
        ?:  throw IllegalArgumentException("String does not match UUIDv4 pattern: $value")

    // Reformat the segments to the proper UUID format.
    val uuid = segments.joinToString("-")
    return UUID.fromString(uuid)
}
```

P.S. If you're curious why someone would remove the dashes from a UUID, the answer is questionable vendor software. :)

**Comment by vietj** [comment]
is a special case of https://github.com/eclipse-vertx/vertx-sql-client/issues/942
