### ISSUE TITLE
Vertx MySQL 3.9.2 returning empty data intermittently

### ISSUE THREAD

**Issue by hitesh-kansal** [eclipse-vertx/vertx-sql-client#953]
We have been facing intermittent issue with Vertx MySQL 3.9.2 version where we are getting empty result set for a normal Select query using prepared statement. Issue is happening intermittently and hard to reproduce. Vertx version is 3.9.2.

MySql is running on Amazon Aurora.

**Comment by BillyYccc** [comment]
It's not clear what mysql client you're using because `io.vertx:vertx-mysql-client` is never released with a `3.5.0` version.

**Comment by hitesh-kansal** [comment]
Below is code snippet from our pom.xml file:
`  <properties>
    <mysql.version>3.5.0</mysql.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-mysql-client</artifactId>
    </dependency>
  </dependencies>`

**Comment by hitesh-kansal** [comment]
@BillyYccc sorry my bad.. we are using `3.9.2` version.

**Comment by vietj** [comment]
do you have more details ? without them it is pretty hard for us to figure out

**Comment by tsegismont** [comment]
Closing as we need more info to look into this. Please reopen if you can provide some details.
