### ISSUE TITLE
PG client: errors are not getting propagated in transactions

### ISSUE THREAD

**Issue by ashertarno** [eclipse-vertx/vertx-sql-client#974]
### Version

4.1.0

### Context

A query running without transaction throws a foreign key constraint violation error. While running the same query in a transaction - nothing happens, transaction is successfully  committed.

### Do you have a reproducer?

https://gist.github.com/ashertarno/d4672df84676168b82d8fa2f4abb2c6b

### Steps to reproduce

1. Create a table to work with and fill in a single row. Column parent is a foreign key to the column name:

_create schema public;
create table public.test (name varchar(50) primary key, parent varchar(50));
alter table public.test ADD CONSTRAINT the_parent_key FOREIGN KEY (parent) REFERENCES public.test(name) DEFERRABLE INITIALLY DEFERRED;
insert into public.test (name, parent) values ('adam', null);_

2. The code in gist executes the following query:

**insert into public.test (name, parent) values ('john', 'mike');**

The query should fail because primary key 'mike' doesn't exist in the name column;

3. In the gist run the noTransaction(pool); method (make sure withTransaction() is commented). The query will throw an error as expected:

`io.vertx.pgclient.PgException: { "message": "insert or update on table \"test\" violates foreign key constraint \"the_parent_key\"", "severity": "ERROR", "code": "23503", "detail": "Key (parent)=(mike) is not present in table \"test\".", "file": "ri_triggers.c", "line": "3266", "routine": "ri_ReportViolation", "schema": "public", "table": "test", "constraint": "the_parent_key" }` 

4. Comment noTransaction(pool);  method and uncomment withTransaction(pool). The same query will be executed in transaction, the transaction will be committed and no error will be thrown.

### Extra

I tried to run the same tests with a query that throws "duplicate key value" error instead of foreign key constraint violation and it DOES work

"insert into public.test (name, parent) values (**'adam'**, 'mike');" 

`io.vertx.pgclient.PgException: { "message": "duplicate key value violates unique constraint \"test_pkey\"", "severity": "ERROR", "code": "23505", "detail": "Key (name)=(adam) already exists.", "file": "nbtinsert.c", "line": "434", "routine": "_bt_check_unique", "schema": "public", "table": "test", "constraint": "test_pkey" }
`
I don't know what is the difference in handling error 23503 vs 23505, but something is wrong here.

### Environment 
CentOS8
jdk11
PostgreSQL 10.7

**Comment by vietj** [comment]
can you provide a reproducer with RX JAVA ?

**Comment by ashertarno** [comment]
@vietj it is with rxjava

**Comment by vietj** [comment]
I mean without Rx java

**Comment by ashertarno** [comment]
@vietj gotcha :) i've added two non-rxfied methods to the same gist. please use them in the same manner. the result is the same, noTransactionNoRx() works as expected, withTransactionNoRx() again doesn't work with foreign key constraint violation and works with the duplicate key. 
thanks for looking into this!

**Comment by ashertarno** [comment]
@vietj just checking if you could reproduce the issue using the gist.

**Comment by vietj** [comment]
no time yet to look at it

**Comment by vietj** [comment]
I found the issue @ashertarno a fix will be done soon

**Comment by ashertarno** [comment]
@vietj thanks, julien, as always - you rock.

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vertx-sql-client/issues/996
