### ISSUE TITLE
Idletimeout kills active statements and doesn't do cleanup, leading to leaks

### ISSUE THREAD

**Issue by akleiman** [eclipse-vertx/vertx-sql-client#984]
### Version

4.1.0 vertx-pg-client

### Context

When executing a long-running statement their connections will be evicted from the pool if their execution time exceeds the idletimeout set on the client. On top of that, when evicting a connection it doesn't seem like proper cleanup is being done, which leads to leaked connections. I observed this watching pg_stat_activity as my application was running.

### Steps to reproduce

1. Set your idletimeout to something slow, like 1 minute.
2. In a loop saturate your pool with slow-running queries (e.g. `select pg_sleep(3600)`)
3. Watch pg_stat_activity, like: `select application_name, state, count(1) from pg_stat_activity group by application_name, state \watch 10`
4. The count of active queries should steadily go up, pretty much on the interval set in your idletimeout

Even if killing active/running statements is the desired behavior (seems strange to me) they should at least be cleaned up.

**Comment by akleiman** [comment]
@vietj I haven't been able to reproduce this on 4.3.1, has there been a change to idleTimeout behavior? I could try and get an older version to try and reproduce but I don't know if there's any point to that.

**Comment by vietj** [comment]
I can't remember anything precisely.

I don't think there is any point if that does not happen anymore, it means the bug was fixed.
